/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file foreach_addcdiv_scalar.cpp
 * \brief Kernel entry point for foreach_addcdiv_scalar operator (arch35/Ascend950).
 *        Dispatches to SIMT Process based on TilingKey (dtype combination).
 *        Scalar value is stored in TilingData (MDE 3.1).
 */

#include "foreach_addcdiv_scalar_simt.h"

using namespace AscendC;
using namespace NsForeachAddcdivScalar;

enum class ForeachAddcdivScalarTilingKey : uint32_t {
    TILING_KEY_FP16 = 0, // x1/x2/x3: float16, scalar: float16 -> y: float16
    TILING_KEY_FP32 = 1, // x1/x2/x3: float32, scalar: float32 -> y: float32
    TILING_KEY_BF16 = 2, // x1/x2/x3: bfloat16, scalar: float32 -> y: bfloat16
};

template <uint32_t schMode>
__global__ __aicore__ void foreach_addcdiv_scalar(GM_ADDR x1, GM_ADDR x2, GM_ADDR x3, GM_ADDR scalar, GM_ADDR y,
                                                  GM_ADDR workspace, GM_ADDR tiling)
{
    KERNEL_TASK_TYPE_DEFAULT(KERNEL_TYPE_AIV_ONLY);
    REGISTER_TILING_DEFAULT(ForeachAddcdivScalarTilingData);
    GET_TILING_DATA_WITH_STRUCT(ForeachAddcdivScalarTilingData, tilingData, tiling);

    if constexpr (schMode == static_cast<uint32_t>(ForeachAddcdivScalarTilingKey::TILING_KEY_FP16)) {
        NsForeachAddcdivScalar::Process<half>(x1, x2, x3, scalar, y, &tilingData);
    } else if constexpr (schMode == static_cast<uint32_t>(ForeachAddcdivScalarTilingKey::TILING_KEY_FP32)) {
        NsForeachAddcdivScalar::Process<float>(x1, x2, x3, scalar, y, &tilingData);
    } else if constexpr (schMode == static_cast<uint32_t>(ForeachAddcdivScalarTilingKey::TILING_KEY_BF16)) {
        NsForeachAddcdivScalar::Process<bfloat16_t>(x1, x2, x3, scalar, y, &tilingData);
    }
}
