/**
 * Copyright (c) 2025 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* !
 * \file fused_quant_mat_mul_kernel_tilingkey.h
 * \brief
 */
#ifndef FUSED_QUANT_MAT_MUL_KERNEL_TILINGKEY_H
#define FUSED_QUANT_MAT_MUL_KERNEL_TILINGKEY_H

#include "ascendc/host_api/tiling/template_argument.h"

#define QUANT_BATCH_MATMUL_V3_NOT_TRANS 0
#define QUANT_BATCH_MATMUL_V3_B_TRANS 1
#define QUANT_BATCH_MATMUL_V3_A_TRANS 2
#define QUANT_BATCH_MATMUL_V3_ALL_TRANS 3

#define QUANT_BATCH_MATMUl_V3_KERNEL_TEMPLATE_TYPE_TBE 0
#define QUANT_BATCH_MATMUl_V3_KERNEL_TEMPLATE_TYPE_BASIC 1
#define QUANT_BATCH_MATMUl_V3_KERNEL_TEMPLATE_TYPE_OPT 2

#define QUANT_BATCH_MATMUL_V3_NOT_PERTOKEN 0
#define QUANT_BATCH_MATMUL_V3_IS_PERTOKEN 1

#define QUANT_BATCH_MATMUL_V3_OPTION_ATTR_NONE 0
#define QUANT_BATCH_MATMUL_V3_NEED_ATOMICLEAN 1
#define QUANT_BATCH_MATMUL_V3_IS_AICAIV_1_2 2

#define FUSED_OPTYPE_NONE 0 // unsupported
#define FUSED_OPTYPE_RELU 1 // unsupported
#define FUSED_OPTYPE_SWIGLU 2 // unsupported
#define FUSED_OPTYPE_GELU_TANH 3
#define FUSED_OPTYPE_GELU_ERF 4    

#define SET_CV11_ATTR_NONE(trans, kernel_template_type, pertoken)                                                         \
            ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_MIX_AIC_1_1),                                                                    \
            ASCENDC_TPL_UINT_SEL(TRANS, ASCENDC_TPL_UI_LIST, trans),                                    \
            ASCENDC_TPL_UINT_SEL(KERNEL_TEMPLATE_TYPE, ASCENDC_TPL_UI_LIST, QUANT_BATCH_MATMUl_V3_KERNEL_TEMPLATE_TYPE_##kernel_template_type),      \
            ASCENDC_TPL_UINT_SEL(PERTOKEN, ASCENDC_TPL_UI_LIST, QUANT_BATCH_MATMUL_V3_##pertoken),               \
            ASCENDC_TPL_UINT_SEL(OPTION_ATTRS, ASCENDC_TPL_UI_LIST, QUANT_BATCH_MATMUL_V3_OPTION_ATTR_NONE)      

ASCENDC_TPL_ARGS_DECL(
    FusedQuantMatMul,
    ASCENDC_TPL_UINT_DECL(
        TRANS, ASCENDC_TPL_2_BW, ASCENDC_TPL_UI_LIST, QUANT_BATCH_MATMUL_V3_NOT_TRANS, QUANT_BATCH_MATMUL_V3_B_TRANS, QUANT_BATCH_MATMUL_V3_A_TRANS, QUANT_BATCH_MATMUL_V3_ALL_TRANS),
    ASCENDC_TPL_UINT_DECL(
        KERNEL_TEMPLATE_TYPE, ASCENDC_TPL_2_BW, ASCENDC_TPL_UI_LIST, QUANT_BATCH_MATMUl_V3_KERNEL_TEMPLATE_TYPE_TBE, QUANT_BATCH_MATMUl_V3_KERNEL_TEMPLATE_TYPE_BASIC, QUANT_BATCH_MATMUl_V3_KERNEL_TEMPLATE_TYPE_OPT),
    ASCENDC_TPL_UINT_DECL(
        PERTOKEN, ASCENDC_TPL_1_BW, ASCENDC_TPL_UI_LIST, QUANT_BATCH_MATMUL_V3_NOT_PERTOKEN, QUANT_BATCH_MATMUL_V3_IS_PERTOKEN),
    ASCENDC_TPL_UINT_DECL(
        OPTION_ATTRS, ASCENDC_TPL_2_BW, ASCENDC_TPL_UI_LIST, QUANT_BATCH_MATMUL_V3_OPTION_ATTR_NONE, QUANT_BATCH_MATMUL_V3_NEED_ATOMICLEAN, QUANT_BATCH_MATMUL_V3_IS_AICAIV_1_2),
    ASCENDC_TPL_UINT_DECL(
        FUSED_OPTYPE, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST, FUSED_OPTYPE_NONE, FUSED_OPTYPE_RELU, FUSED_OPTYPE_SWIGLU, FUSED_OPTYPE_GELU_TANH, FUSED_OPTYPE_GELU_ERF), );

ASCENDC_TPL_SEL(
#if defined(__CCE_AICORE__)

#if defined(__CCE_AICORE__) && __CCE_AICORE__ == 220

#if (ORIG_DTYPE_Y == DT_FLOAT16)  // fp16

#if (ORIG_DTYPE_SCALE == DT_FLOAT)
    ASCENDC_TPL_ARGS_SEL(SET_CV11_ATTR_NONE(QUANT_BATCH_MATMUL_V3_NOT_TRANS, BASIC, IS_PERTOKEN),
                        ASCENDC_TPL_UINT_SEL(FUSED_OPTYPE, ASCENDC_TPL_UI_LIST, FUSED_OPTYPE_GELU_TANH, FUSED_OPTYPE_GELU_ERF),),
    ASCENDC_TPL_ARGS_SEL(SET_CV11_ATTR_NONE(QUANT_BATCH_MATMUL_V3_A_TRANS, BASIC, IS_PERTOKEN),
                        ASCENDC_TPL_UINT_SEL(FUSED_OPTYPE, ASCENDC_TPL_UI_LIST, FUSED_OPTYPE_GELU_TANH, FUSED_OPTYPE_GELU_ERF),),
    ASCENDC_TPL_ARGS_SEL(SET_CV11_ATTR_NONE(QUANT_BATCH_MATMUL_V3_B_TRANS, BASIC, IS_PERTOKEN),
                        ASCENDC_TPL_UINT_SEL(FUSED_OPTYPE, ASCENDC_TPL_UI_LIST, FUSED_OPTYPE_GELU_TANH, FUSED_OPTYPE_GELU_ERF),),
    ASCENDC_TPL_ARGS_SEL(SET_CV11_ATTR_NONE(QUANT_BATCH_MATMUL_V3_ALL_TRANS, BASIC, IS_PERTOKEN),
                        ASCENDC_TPL_UINT_SEL(FUSED_OPTYPE, ASCENDC_TPL_UI_LIST, FUSED_OPTYPE_GELU_TANH, FUSED_OPTYPE_GELU_ERF),),
#endif // ORIG_DTYPE_SCALE

#else  //  bf16
    ASCENDC_TPL_ARGS_SEL(SET_CV11_ATTR_NONE(QUANT_BATCH_MATMUL_V3_NOT_TRANS, BASIC, IS_PERTOKEN),
                        ASCENDC_TPL_UINT_SEL(FUSED_OPTYPE, ASCENDC_TPL_UI_LIST, FUSED_OPTYPE_GELU_TANH, FUSED_OPTYPE_GELU_ERF),),
    ASCENDC_TPL_ARGS_SEL(SET_CV11_ATTR_NONE(QUANT_BATCH_MATMUL_V3_A_TRANS, BASIC, IS_PERTOKEN),
                        ASCENDC_TPL_UINT_SEL(FUSED_OPTYPE, ASCENDC_TPL_UI_LIST, FUSED_OPTYPE_GELU_TANH, FUSED_OPTYPE_GELU_ERF),),
    ASCENDC_TPL_ARGS_SEL(SET_CV11_ATTR_NONE(QUANT_BATCH_MATMUL_V3_B_TRANS, BASIC, IS_PERTOKEN),
                        ASCENDC_TPL_UINT_SEL(FUSED_OPTYPE, ASCENDC_TPL_UI_LIST, FUSED_OPTYPE_GELU_TANH, FUSED_OPTYPE_GELU_ERF),),
    ASCENDC_TPL_ARGS_SEL(SET_CV11_ATTR_NONE(QUANT_BATCH_MATMUL_V3_ALL_TRANS, BASIC, IS_PERTOKEN),
                        ASCENDC_TPL_UINT_SEL(FUSED_OPTYPE, ASCENDC_TPL_UI_LIST, FUSED_OPTYPE_GELU_TANH, FUSED_OPTYPE_GELU_ERF),),
#endif // ORIG_DTYPE_Y
#endif
#else  // compile tiling only
    ASCENDC_TPL_ARGS_SEL(SET_CV11_ATTR_NONE(QUANT_BATCH_MATMUL_V3_NOT_TRANS, BASIC, IS_PERTOKEN),
                        ASCENDC_TPL_UINT_SEL(FUSED_OPTYPE, ASCENDC_TPL_UI_LIST, FUSED_OPTYPE_GELU_TANH, FUSED_OPTYPE_GELU_ERF),),
    ASCENDC_TPL_ARGS_SEL(SET_CV11_ATTR_NONE(QUANT_BATCH_MATMUL_V3_A_TRANS, BASIC, IS_PERTOKEN),
                        ASCENDC_TPL_UINT_SEL(FUSED_OPTYPE, ASCENDC_TPL_UI_LIST, FUSED_OPTYPE_GELU_TANH, FUSED_OPTYPE_GELU_ERF),),
    ASCENDC_TPL_ARGS_SEL(SET_CV11_ATTR_NONE(QUANT_BATCH_MATMUL_V3_B_TRANS, BASIC, IS_PERTOKEN),
                        ASCENDC_TPL_UINT_SEL(FUSED_OPTYPE, ASCENDC_TPL_UI_LIST, FUSED_OPTYPE_GELU_TANH, FUSED_OPTYPE_GELU_ERF),),
    ASCENDC_TPL_ARGS_SEL(SET_CV11_ATTR_NONE(QUANT_BATCH_MATMUL_V3_ALL_TRANS, BASIC, IS_PERTOKEN),
                        ASCENDC_TPL_UINT_SEL(FUSED_OPTYPE, ASCENDC_TPL_UI_LIST, FUSED_OPTYPE_GELU_TANH, FUSED_OPTYPE_GELU_ERF),),
#endif
);
#endif // FUSED_QUANT_MAT_MUL_KERNEL_TILINGKEY_H