/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

#ifndef FOREACH_ABS_SIMT_H
#define FOREACH_ABS_SIMT_H

#include "kernel_operator.h"
#include "kernel_tiling/kernel_tiling.h"
#include "foreach_abs_tiling_data.h"
#include "foreach_abs_tiling_key.h"

namespace NsForeachAbs {

using namespace AscendC;

constexpr uint32_t THREAD_NUM = 1024;

template <typename T>
struct AbsCompute {
    __simt_callee__ static inline T Compute(T val)
    {
        return (val >= static_cast<T>(0)) ? val : (static_cast<T>(0) - val);
    }
};

template <>
struct AbsCompute<bfloat16_t> {
    __simt_callee__ static inline bfloat16_t Compute(bfloat16_t val)
    {
        float f32 = static_cast<float>(val);
        float absF32 = (f32 >= 0.0f) ? f32 : (0.0f - f32);
        return static_cast<bfloat16_t>(absF32);
    }
};

template <typename T>
__simt_callee__ inline __gm__ T* SimtGetTensorAddr(GM_ADDR tensorListPtr, int64_t idx)
{
    __gm__ uint64_t* dataAddr = reinterpret_cast<__gm__ uint64_t*>(tensorListPtr);
    uint64_t tensorPtrOffset = *dataAddr;
    __gm__ uint64_t* tensorPtr = dataAddr + (tensorPtrOffset >> 3);
    return reinterpret_cast<__gm__ T*>(*(tensorPtr + idx));
}

template <typename T, typename IDX_T>
__simt_vf__ __aicore__ LAUNCH_BOUND(THREAD_NUM)
inline void OpForeachAbsSimtKernel(
    IDX_T totalElements,
    int32_t tensorCount,
    __gm__ const int64_t* cumOffsets,
    GM_ADDR xList,
    GM_ADDR yList)
{
    for (IDX_T flatIdx = static_cast<IDX_T>(
            AscendC::Simt::GetBlockIdx() * AscendC::Simt::GetThreadNum()
            + AscendC::Simt::GetThreadIdx());
         flatIdx < totalElements;
         flatIdx += static_cast<IDX_T>(
            AscendC::Simt::GetThreadNum() * AscendC::Simt::GetBlockNum())) {
        int32_t tensorId = tensorCount - 1;
        IDX_T prevCumSum = 0;
        for (int32_t t = 0; t < tensorCount; t++) {
            if (flatIdx < static_cast<IDX_T>(cumOffsets[t])) {
                tensorId = t;
                prevCumSum = (t > 0) ? static_cast<IDX_T>(cumOffsets[t - 1]) : static_cast<IDX_T>(0);
                break;
            }
        }
        IDX_T localIdx = flatIdx - prevCumSum;

        __gm__ T* inputPtr = SimtGetTensorAddr<T>(xList, tensorId);
        __gm__ T* outputPtr = SimtGetTensorAddr<T>(yList, tensorId);

        T val = inputPtr[localIdx];
        outputPtr[localIdx] = AbsCompute<T>::Compute(val);
    }
}

template <typename T>
__aicore__ inline void Process(GM_ADDR x, GM_ADDR y, GM_ADDR workspace, GM_ADDR tiling)
{
    __gm__ const ForeachAbsTilingData* tilingGM =
        reinterpret_cast<__gm__ const ForeachAbsTilingData*>(tiling);

    int64_t totalElements = tilingGM->totalElements;
    int32_t tensorCount = tilingGM->tensorCount;
    __gm__ const int64_t* cumOffsets = tilingGM->cumulativeOffsets;

    if (totalElements <= static_cast<int64_t>(INT32_MAX)) {
        using IDX_T = int32_t;
        AscendC::Simt::VF_CALL<OpForeachAbsSimtKernel<T, IDX_T>>(
            AscendC::Simt::Dim3(THREAD_NUM),
            static_cast<IDX_T>(totalElements), tensorCount,
            cumOffsets, x, y);
    } else {
        using IDX_T = int64_t;
        AscendC::Simt::VF_CALL<OpForeachAbsSimtKernel<T, IDX_T>>(
            AscendC::Simt::Dim3(THREAD_NUM),
            totalElements, tensorCount,
            cumOffsets, x, y);
    }
}

} // namespace NsForeachAbs

#endif // FOREACH_ABS_SIMT_H