/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 *
 * Generated By CANNBot
 */

// SoftplusV2Grad Tiling UT — 纯函数 + 框架级全覆盖

#include <iostream>
#include <vector>
#include <sstream>

#include <gtest/gtest.h>
#include "log/log.h"
#include "kernel_run_context_facker.h"
#include "test_cube_util.h"
#include "exe_graph/runtime/storage_format.h"
#include "exe_graph/runtime/storage_shape.h"
#include "platform/platform_infos_def.h"
#include "ut_op_util.h"
#include "../../../../op_host/arch35/softplus_v2_grad_tiling_arch35.h"
#include "../../../../op_kernel/arch35/softplus_v2_grad_struct.h"

using namespace std;
using namespace ut_util;

class SoftplusV2GradTilingTest : public testing::Test {
protected:
    static void SetUpTestCase() { std::cout << "SoftplusV2GradTilingTest SetUp" << std::endl; }
    static void TearDownTestCase() { std::cout << "SoftplusV2GradTilingTest TearDown" << std::endl; }
};

// ============================================================
// 1. CheckBroadcastShape
// ============================================================
TEST_F(SoftplusV2GradTilingTest, broadcast_same_shape_single_in_out)
{
    // input {2,3}, output {2,3} — 完全一致
    std::vector<std::vector<int64_t>> padded_in = {{2, 3}};
    std::vector<std::vector<int64_t>> padded_out = {{2, 3}};
    EXPECT_TRUE(softplus_v2_grad::CheckBroadcastShape(padded_in, padded_out, 2));
}

TEST_F(SoftplusV2GradTilingTest, broadcast_two_inputs_same)
{
    // 2 个 input 都是 {4,4}, 1 个 output {4,4}
    std::vector<std::vector<int64_t>> padded_in = {{4, 4}, {4, 4}};
    std::vector<std::vector<int64_t>> padded_out = {{4, 4}};
    EXPECT_TRUE(softplus_v2_grad::CheckBroadcastShape(padded_in, padded_out, 2));
}

TEST_F(SoftplusV2GradTilingTest, broadcast_input_dim_is_one)
{
    // input {1,4}, output {4,4} — input=1 的维度不冲突
    std::vector<std::vector<int64_t>> padded_in = {{1, 4}};
    std::vector<std::vector<int64_t>> padded_out = {{4, 4}};
    EXPECT_TRUE(softplus_v2_grad::CheckBroadcastShape(padded_in, padded_out, 2));
}

TEST_F(SoftplusV2GradTilingTest, broadcast_output_dim_is_one)
{
    // input {4,4}, output {1,4} — output=1 的维度不冲突
    std::vector<std::vector<int64_t>> padded_in = {{4, 4}};
    std::vector<std::vector<int64_t>> padded_out = {{1, 4}};
    EXPECT_TRUE(softplus_v2_grad::CheckBroadcastShape(padded_in, padded_out, 2));
}

TEST_F(SoftplusV2GradTilingTest, broadcast_two_inputs_different_non_one)
{
    // 两个 input 在同一维上取值不同且都不是 1 → 不兼容
    std::vector<std::vector<int64_t>> padded_in = {{2, 3}, {4, 3}};
    std::vector<std::vector<int64_t>> padded_out = {{4, 3}};
    EXPECT_FALSE(softplus_v2_grad::CheckBroadcastShape(padded_in, padded_out, 2));
}

TEST_F(SoftplusV2GradTilingTest, broadcast_input_output_diff_non_one)
{
    // input {2,3}, output {4,3} 且 input dim0=2 ≠ 1, output dim0=4 ≠ 1 → 不兼容
    std::vector<std::vector<int64_t>> padded_in = {{2, 3}};
    std::vector<std::vector<int64_t>> padded_out = {{4, 3}};
    EXPECT_FALSE(softplus_v2_grad::CheckBroadcastShape(padded_in, padded_out, 2));
}

// ============================================================
// 2. PadAndSqueeze
// ============================================================

TEST_F(SoftplusV2GradTilingTest, pad_squeeze_same_rank)
{
    // 两个 input 同 rank，output 同 rank → 无需补
    std::vector<std::vector<int64_t>> in_shapes = {{2, 3}, {2, 3}};
    std::vector<std::vector<int64_t>> out_shapes = {{2, 3}};
    std::vector<int64_t> max_bro;
    std::vector<std::vector<int64_t>> norm_in, norm_out;
    EXPECT_TRUE(softplus_v2_grad::PadAndSqueeze(in_shapes, out_shapes, max_bro, norm_in, norm_out));
    EXPECT_EQ(max_bro, std::vector<int64_t>({2, 3}));
    EXPECT_EQ(norm_in.size(), 2u);
    EXPECT_EQ(norm_out.size(), 1u);
    EXPECT_EQ(norm_in[0], std::vector<int64_t>({2, 3}));
    EXPECT_EQ(norm_out[0], std::vector<int64_t>({2, 3}));
}

TEST_F(SoftplusV2GradTilingTest, pad_squeeze_different_rank)
{
    // input: {2,3} (rank 2), output: {2} (rank 1) → output 右对齐补 1
    std::vector<std::vector<int64_t>> in_shapes = {{2, 3}};
    std::vector<std::vector<int64_t>> out_shapes = {{3}};
    std::vector<int64_t> max_bro;
    std::vector<std::vector<int64_t>> norm_in, norm_out;
    EXPECT_TRUE(softplus_v2_grad::PadAndSqueeze(in_shapes, out_shapes, max_bro, norm_in, norm_out));
    // max_rank=2: input {2,3}, output padded to {1,3}
    // broadcast result should be {2,3}
    EXPECT_EQ(max_bro, std::vector<int64_t>({2, 3}));
    EXPECT_EQ(norm_in[0], std::vector<int64_t>({2, 3}));
    // output padded dim0=1 不挤压（因为有非1的输入维）→ 保持 {1,3}
    EXPECT_EQ(norm_out[0], std::vector<int64_t>({1, 3}));
}

TEST_F(SoftplusV2GradTilingTest, pad_squeeze_all_ones)
{
    // 全部是 1 → max_bro_shape 为 {1}
    std::vector<std::vector<int64_t>> in_shapes = {{1}};
    std::vector<std::vector<int64_t>> out_shapes = {{1}};
    std::vector<int64_t> max_bro;
    std::vector<std::vector<int64_t>> norm_in, norm_out;
    EXPECT_TRUE(softplus_v2_grad::PadAndSqueeze(in_shapes, out_shapes, max_bro, norm_in, norm_out));
    EXPECT_EQ(max_bro, std::vector<int64_t>({1}));
    EXPECT_EQ(norm_in[0], std::vector<int64_t>({1}));
    EXPECT_EQ(norm_out[0], std::vector<int64_t>({1}));
}

TEST_F(SoftplusV2GradTilingTest, pad_squeeze_4d)
{
    // 4D tensor: {1,4,4,8}
    std::vector<std::vector<int64_t>> in_shapes = {{1, 4, 4, 8}};
    std::vector<std::vector<int64_t>> out_shapes = {{1, 4, 4, 8}};
    std::vector<int64_t> max_bro;
    std::vector<std::vector<int64_t>> norm_in, norm_out;
    EXPECT_TRUE(softplus_v2_grad::PadAndSqueeze(in_shapes, out_shapes, max_bro, norm_in, norm_out));
    // dim0=1 squeezed out, 剩下 {4,4,8}
    EXPECT_EQ(max_bro, std::vector<int64_t>({4, 4, 8}));
}

// ============================================================
// 3. FindSplitAxis
// ============================================================

TEST_F(SoftplusV2GradTilingTest, split_axis_small_shape_no_split)
{
    // shape {2,3}, dtype_size=4, ub=262144, phys_nodes=4
    // per_buf_bytes = (262144/4) & ~31 = 65504
    // per_buf_elems = 65504/4 = 16376
    // inner: k=1: 3*1=3 ≤ 16376, inner*=3 → k=0: 2*3=6 ≤ 16376
    // 不切: a_i=2, a_o=1, a_i_tail=2, axis=0
    std::vector<int64_t> shape = {2, 3};
    SplitResult out;
    EXPECT_TRUE(softplus_v2_grad::FindSplitAxis(shape, /*dtype_size=*/4, /*ub=*/262144, /*phys_nodes=*/4, out));
    EXPECT_EQ(out.axis, 0);
    EXPECT_EQ(out.a_o, 1);
    EXPECT_EQ(out.a_i, 2);
    EXPECT_EQ(out.a_i_tail, 2);
}

TEST_F(SoftplusV2GradTilingTest, split_axis_large_shape_needs_split)
{
    // shape {1, 65536}, dtype_size=4, ub=262144, phys_nodes=4
    // per_buf_bytes = (262144/4) & ~31 = 65536; per_buf_elems = 65536/4 = 16384
    // k=1: 65536 > 16384 → split on axis 1
    // a_i = 16384/1 = 16384; a_o = ceil(65536/16384) = 4; rem = 0 → a_i_tail = 16384
    std::vector<int64_t> shape = {1, 65536};
    SplitResult out;
    EXPECT_TRUE(softplus_v2_grad::FindSplitAxis(shape, /*dtype_size=*/4, /*ub=*/262144, /*phys_nodes=*/4, out));
    EXPECT_EQ(out.axis, 1);
    EXPECT_EQ(out.a_o, 4);
    EXPECT_EQ(out.a_i, 16384);
    EXPECT_EQ(out.a_i_tail, 16384);
}

TEST_F(SoftplusV2GradTilingTest, split_axis_invalid_dtype_size)
{
    std::vector<int64_t> shape = {2, 3};
    SplitResult out;
    EXPECT_FALSE(softplus_v2_grad::FindSplitAxis(shape, /*dtype_size=*/0, /*ub=*/262144, /*phys_nodes=*/4, out));
}

TEST_F(SoftplusV2GradTilingTest, split_axis_invalid_phys_nodes)
{
    std::vector<int64_t> shape = {2, 3};
    SplitResult out;
    EXPECT_FALSE(softplus_v2_grad::FindSplitAxis(shape, /*dtype_size=*/4, /*ub=*/262144, /*phys_nodes=*/0, out));
}

TEST_F(SoftplusV2GradTilingTest, split_axis_very_small_ub)
{
    // ub=64: per_buf_bytes = (64/4) & ~31 = 0 → per_buf_elems = 0 → 直接失败
    std::vector<int64_t> shape = {2, 3};
    SplitResult out;
    EXPECT_FALSE(softplus_v2_grad::FindSplitAxis(shape, /*dtype_size=*/4, /*ub=*/64, /*phys_nodes=*/4, out));
}

// ============================================================
// 4. MultiCoreSplit
// ============================================================

TEST_F(SoftplusV2GradTilingTest, multicore_few_tiles)
{
    // split.axis=0, shape {2,3}: outer_prod=1, total_tiles = 1*1 = 1
    // max_cores=64, num_cores = min(1,64) = 1
    SplitResult split = {0, 2, 1, 2};
    std::vector<int64_t> shape = {2, 3};
    MultiCoreResult out;
    EXPECT_TRUE(softplus_v2_grad::MultiCoreSplit(shape, split, 64, out));
    EXPECT_EQ(out.num_cores, 1);
    EXPECT_EQ(out.total_tiles, 1);
    EXPECT_EQ(out.tiles_main, 1);
    EXPECT_EQ(out.cores_tail, 0);
}

TEST_F(SoftplusV2GradTilingTest, multicore_many_tiles)
{
    // split.axis=1, shape {1,65536}: outer_prod=1, a_o=5
    // total_tiles = 1*5 = 5, num_cores=5
    SplitResult split = {1, 16376, 5, 4};
    std::vector<int64_t> shape = {1, 65536};
    MultiCoreResult out;
    EXPECT_TRUE(softplus_v2_grad::MultiCoreSplit(shape, split, 64, out));
    EXPECT_EQ(out.num_cores, 5);
    EXPECT_EQ(out.total_tiles, 5);
    EXPECT_EQ(out.tiles_main, 1);
    EXPECT_EQ(out.cores_tail, 0);
}

TEST_F(SoftplusV2GradTilingTest, multicore_caps_at_max_cores)
{
    // shape {100, 8}: axis=0, a_o=5, outer_prod=1, total_tiles=5
    // max_cores=3: num_cores=min(5,3)=3 → tiles_main=5/3=1, cores_tail=5%3=2
    SplitResult split = {0, 2, 5, 2};
    std::vector<int64_t> shape = {100, 8};
    MultiCoreResult out;
    EXPECT_TRUE(softplus_v2_grad::MultiCoreSplit(shape, split, 3, out));
    EXPECT_EQ(out.num_cores, 3);
    EXPECT_EQ(out.total_tiles, 5);
    EXPECT_EQ(out.tiles_main, 1);
    EXPECT_EQ(out.cores_tail, 2);
}

TEST_F(SoftplusV2GradTilingTest, multicore_tail_cores)
{
    // shape {5}: split.axis=0, a_o=1, total_tiles=1 → outer_prod=1
    // max_cores=3: num_cores=1 → tiles_main=1, cores_tail=0
    SplitResult split = {0, 3, 2, 2}; // 5 元素: a_o=2, a_i=3, a_i_tail=2
    std::vector<int64_t> shape = {5};
    MultiCoreResult out;
    EXPECT_TRUE(softplus_v2_grad::MultiCoreSplit(shape, split, 3, out));
    EXPECT_EQ(out.total_tiles, 2); // outer_prod(1)*a_o(2)=2
    EXPECT_EQ(out.num_cores, 2);   // min(2,3)=2
    EXPECT_EQ(out.tiles_main, 1);  // 2/2=1
    EXPECT_EQ(out.cores_tail, 0);  // 2%2=0
}

TEST_F(SoftplusV2GradTilingTest, multicore_zero_total_tiles)
{
    // shape {0} (空 tensor): outer_prod=1, a_o=0 → total_tiles=0, num_cores=0 → false
    SplitResult split = {0, 1, 0, 1};
    std::vector<int64_t> shape = {0};
    MultiCoreResult out;
    EXPECT_FALSE(softplus_v2_grad::MultiCoreSplit(shape, split, 64, out));
}

// ============================================================
// 5. PrecomputeStrides
// ============================================================

TEST_F(SoftplusV2GradTilingTest, strides_1d)
{
    std::vector<int64_t> shape = {5};
    std::vector<int64_t> strides;
    EXPECT_TRUE(softplus_v2_grad::PrecomputeStrides(shape, strides));
    // 1D: 最内维 stride=1
    EXPECT_EQ(strides, std::vector<int64_t>({1}));
}

TEST_F(SoftplusV2GradTilingTest, strides_2d)
{
    std::vector<int64_t> shape = {3, 4};
    std::vector<int64_t> strides;
    EXPECT_TRUE(softplus_v2_grad::PrecomputeStrides(shape, strides));
    // d=1: s[1]=4 → prod=1 → stride[1]=1; d=0: prod=s[1]=4 → stride[0]=4
    EXPECT_EQ(strides, std::vector<int64_t>({4, 1}));
}

TEST_F(SoftplusV2GradTilingTest, strides_dim_one_yields_zero_stride)
{
    // dim=1 → stride=0 (broadcast dim)
    std::vector<int64_t> shape = {1, 8, 1};
    std::vector<int64_t> strides;
    EXPECT_TRUE(softplus_v2_grad::PrecomputeStrides(shape, strides));
    // d=2: s[2]=1 → 0; d=1: s[1]=8 → prod=1 → 1; d=0: s[0]=1 → 0
    EXPECT_EQ(strides, std::vector<int64_t>({0, 1, 0}));
}

TEST_F(SoftplusV2GradTilingTest, strides_3d)
{
    std::vector<int64_t> shape = {2, 3, 4};
    std::vector<int64_t> strides;
    EXPECT_TRUE(softplus_v2_grad::PrecomputeStrides(shape, strides));
    // d=2: s[2]=4 → 1; d=1: prod=4 → 4; d=0: prod=3*4=12 → 12
    EXPECT_EQ(strides, std::vector<int64_t>({12, 4, 1}));
}

// ============================================================
// 集成: PadAndSqueeze + CheckBroadcastShape 联合正确性
// ============================================================

TEST_F(SoftplusV2GradTilingTest, integration_pad_and_check)
{
    // 确保 PadAndSqueeze 产出的归一化 shape 能通过 CheckBroadcastShape
    std::vector<std::vector<int64_t>> in_shapes = {{4, 8}, {4, 8}};
    std::vector<std::vector<int64_t>> out_shapes = {{4, 8}};
    std::vector<int64_t> max_bro;
    std::vector<std::vector<int64_t>> norm_in, norm_out;
    ASSERT_TRUE(softplus_v2_grad::PadAndSqueeze(in_shapes, out_shapes, max_bro, norm_in, norm_out));
    EXPECT_TRUE(softplus_v2_grad::CheckBroadcastShape(norm_in, norm_out, max_bro.size()));
}

// ============================================================
// 集成: FindSplitAxis + MultiCoreSplit 一致性
// ============================================================

TEST_F(SoftplusV2GradTilingTest, integration_split_and_multicore)
{
    // 验证 split 和 multicore 对同一 shape 的结果一致性
    std::vector<int64_t> shape = {32, 128};
    SplitResult split;
    ASSERT_TRUE(softplus_v2_grad::FindSplitAxis(shape, /*dtype_size=*/4, /*ub=*/262144, /*phys_nodes=*/4, split));
    MultiCoreResult mc;
    ASSERT_TRUE(softplus_v2_grad::MultiCoreSplit(shape, split, 64, mc));
    // 确保多核划分 cover 所有 tile
    EXPECT_EQ(mc.total_tiles, mc.num_cores * mc.tiles_main + mc.cores_tail);
    // num_cores ≤ 64
    EXPECT_LE(mc.num_cores, 64);
}

// ============================================================
// 框架级 Tiling UT — 使用 TilingContextFaker
// 覆盖 GetShapeInfo / DoTilingAndSet / RunTiling / FillShapesAndStrides / LogTilingData
// ============================================================

class SoftplusV2GradTilingIntegrationTest : public testing::Test {
protected:
    static void SetUpTestCase() { std::cout << "SoftplusV2GradTilingIntegration SetUp" << std::endl; }
    static void TearDownTestCase() { std::cout << "SoftplusV2GradTilingIntegration TearDown" << std::endl; }
};

// 辅助: 验证 TilingData 基本合法性
// SoftplusV2GradTilingData 内存布局:
//   SplitResult(4xint64) + MultiCoreResult(4xint64) + rank(1) + per_buf_bytes(1) = 10 个 int64
// raw[8] = rank, raw[9] = per_buf_bytes, raw[4] = multicore.num_cores
static void VerifyTilingDataValid(const gert::TilingData* tiling_data)
{
    ASSERT_NE(tiling_data, nullptr);
    ASSERT_GT(tiling_data->GetDataSize(), (size_t)0);
    auto* raw = reinterpret_cast<const int64_t*>(tiling_data->GetData());
    int64_t rank_val = raw[8];
    int64_t per_buf = raw[9];
    int64_t num_cores = raw[4];
    EXPECT_GT(rank_val, 0);
    EXPECT_GT(per_buf, 0);
    EXPECT_GE(num_cores, 1);
    EXPECT_LE(num_cores, 64);
}

// 通用 tiling 全链路测试模板
static void RunTilingIntegrationTest(const gert::StorageShape& in_a, const gert::StorageShape& in_b,
                                     const gert::StorageShape& out, ge::DataType dtype, ge::DataType out_dtype,
                                     ge::graphStatus expect_status)
{
    gert::StorageShape in_copy_a = in_a;
    gert::StorageShape in_copy_b = in_b;
    gert::StorageShape out_copy = out;
    std::map<std::string, std::string> soc_infos, aicore_spec, intrinsics;
    std::map<std::string, std::string> soc_version = {{"Short_SoC_version", "Ascend950"}, {"NpuArch", "3510"}};
    std::string compile_str = R"({
        "hardware_info": {
            "BT_SIZE": 0, "load3d_constraints": "1",
            "Intrinsic_fix_pipe_l0c2out": false, "Intrinsic_data_move_l12ub": true,
            "Intrinsic_data_move_l0c2ub": true, "Intrinsic_data_move_out2l1_nd2nz": false,
            "UB_SIZE": 245760, "L2_SIZE": 33554432, "L1_SIZE": 524288,
            "L0A_SIZE": 65536, "L0B_SIZE": 65536, "L0C_SIZE": 131072, "CORE_NUM": 64
        }
    })";
    GetPlatFormInfos(compile_str.c_str(), soc_infos, aicore_spec, intrinsics);

    fe::PlatFormInfos platform_info;
    platform_info.Init();
    optiling::SoftplusV2GradCompileInfo compile_info;
    std::string op_type("SoftplusV2Grad");

    auto op_impl = gert::OpImplRegistry::GetInstance().GetOpImpl(op_type.c_str());
    ASSERT_NE(op_impl, nullptr);
    auto tiling_func = op_impl->tiling;
    auto tiling_parse_func = op_impl->tiling_parse;

    auto kernel_holder = gert::KernelRunContextFaker()
                             .KernelIONum(1, 1)
                             .Inputs({const_cast<char*>(compile_str.c_str()), reinterpret_cast<void*>(&platform_info)})
                             .Outputs({&compile_info})
                             .Build();
    ASSERT_TRUE(kernel_holder.GetContext<gert::TilingParseContext>()->GetPlatformInfo()->Init());
    kernel_holder.GetContext<gert::TilingParseContext>()->GetPlatformInfo()->SetPlatformRes("SoCInfo", soc_infos);
    kernel_holder.GetContext<gert::TilingParseContext>()->GetPlatformInfo()->SetPlatformRes("AICoreSpec", aicore_spec);
    kernel_holder.GetContext<gert::TilingParseContext>()->GetPlatformInfo()->SetCoreNumByCoreType("AICore");
    kernel_holder.GetContext<gert::TilingParseContext>()->GetPlatformInfo()->SetPlatformRes("AICoreintrinsicDtypeMap",
                                                                                            intrinsics);
    kernel_holder.GetContext<gert::TilingParseContext>()->GetPlatformInfo()->SetPlatformRes("version", soc_version);
    ASSERT_EQ(tiling_parse_func(kernel_holder.GetContext<gert::KernelContext>()), ge::GRAPH_SUCCESS);

    auto param = gert::TilingData::CreateCap(8192);
    ASSERT_NE(param, nullptr);
    auto ws_holder = gert::ContinuousVector::Create<size_t>(4096);
    auto ws_size = reinterpret_cast<gert::ContinuousVector*>(ws_holder.get());

    auto holder = gert::TilingContextFaker()
                      .SetOpType(op_type)
                      .NodeIoNum(2, 1)
                      .IrInstanceNum({1})
                      .InputShapes({&in_copy_a, &in_copy_b})
                      .OutputShapes({&out_copy})
                      .CompileInfo(&compile_info)
                      .PlatformInfo(reinterpret_cast<char*>(&platform_info))
                      .NodeInputTd(0, dtype, ge::FORMAT_ND, ge::FORMAT_ND)
                      .NodeInputTd(1, dtype, ge::FORMAT_ND, ge::FORMAT_ND)
                      .NodeOutputTd(0, out_dtype, ge::FORMAT_ND, ge::FORMAT_ND)
                      .TilingData(param.get())
                      .Workspace(ws_size)
                      .Build();
    auto* ctx = holder.GetContext<gert::TilingContext>();
    ASSERT_NE(ctx->GetPlatformInfo(), nullptr);
    ctx->GetPlatformInfo()->SetPlatformRes("SoCInfo", soc_infos);
    ctx->GetPlatformInfo()->SetPlatformRes("AICoreSpec", aicore_spec);
    ctx->GetPlatformInfo()->SetCoreNumByCoreType("AICore");
    ctx->GetPlatformInfo()->SetPlatformRes("AICoreintrinsicDtypeMap", intrinsics);

    EXPECT_EQ(tiling_func(ctx), expect_status);
    if (expect_status == ge::GRAPH_SUCCESS) {
        VerifyTilingDataValid(ctx->GetRawTilingData());
    }
}

TEST_F(SoftplusV2GradTilingIntegrationTest, tiling_fp32_2d)
{
    gert::StorageShape shape = {{4, 8}, {4, 8}};
    RunTilingIntegrationTest(shape, shape, shape, ge::DT_FLOAT, ge::DT_FLOAT, ge::GRAPH_SUCCESS);
}

TEST_F(SoftplusV2GradTilingIntegrationTest, tiling_fp16_4d)
{
    gert::StorageShape shape = {{1, 4, 4, 8}, {1, 4, 4, 8}};
    RunTilingIntegrationTest(shape, shape, shape, ge::DT_FLOAT16, ge::DT_FLOAT16, ge::GRAPH_SUCCESS);
}

TEST_F(SoftplusV2GradTilingIntegrationTest, tiling_bf16_5d_rank8)
{
    gert::StorageShape shape = {{1, 1, 2, 3, 4}, {1, 1, 2, 3, 4}};
    RunTilingIntegrationTest(shape, shape, shape, ge::DT_BF16, ge::DT_BF16, ge::GRAPH_SUCCESS);
}

TEST_F(SoftplusV2GradTilingIntegrationTest, tiling_fp32_1d)
{
    gert::StorageShape shape = {{256}, {256}};
    RunTilingIntegrationTest(shape, shape, shape, ge::DT_FLOAT, ge::DT_FLOAT, ge::GRAPH_SUCCESS);
}

TEST_F(SoftplusV2GradTilingIntegrationTest, tiling_fp32_large_2d)
{
    gert::StorageShape shape = {{1, 65536}, {1, 65536}};
    RunTilingIntegrationTest(shape, shape, shape, ge::DT_FLOAT, ge::DT_FLOAT, ge::GRAPH_SUCCESS);
}

TEST_F(SoftplusV2GradTilingIntegrationTest, tiling_unsupported_dtype_failed)
{
    gert::StorageShape shape = {{2, 3}, {2, 3}};
    RunTilingIntegrationTest(shape, shape, shape, ge::DT_INT32, ge::DT_INT32, ge::GRAPH_FAILED);
}
