/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

#include "arch35/bnll.h"

#ifdef __CCE_KT_TEST__
extern "C" __global__ __aicore__ void bnll(GM_ADDR x, GM_ADDR y, GM_ADDR workspace, GM_ADDR tiling)
{
    GET_TILING_DATA_WITH_STRUCT(BNLLTilingData, tilingData, tiling);
    NsBNLL::KernelBNLL<DTYPE_X, float, 0> op;
    op.Init(x, y, &tilingData);
    op.Process();
}
#else
template <typename D_T_X, int BUFFER_MODE>
__global__ __aicore__ void bnll(GM_ADDR x, GM_ADDR y, GM_ADDR workspace, GM_ADDR tiling)
{
    REGISTER_TILING_DEFAULT(BNLLTilingData);
    GET_TILING_DATA_WITH_STRUCT(BNLLTilingData, tilingData, tiling);
    NsBNLL::KernelBNLL<D_T_X, float, BUFFER_MODE> op;
    op.Init(x, y, &tilingData);
    op.Process();
}
#endif
