/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file inplace_update_simt.h
 * \brief SIMT kernel implementation for InplaceUpdate
 */

#ifndef __INPLACE_UPDATE_SIMT_H__
#define __INPLACE_UPDATE_SIMT_H__

#include "kernel_operator.h"
#include "kernel_tiling/kernel_tiling.h"
#include "simt_api/common_functions.h"
#include "simt_api/asc_simt.h"
#include "inplace_update_tiling_data.h"
#include "inplace_update_tiling_key.h"

namespace NsInplaceUpdate {
using namespace AscendC;

static constexpr uint32_t THREAD_NUM = 1024;

/**
 * @brief InplaceUpdate SIMT 核函数
 * 根据索引将 v 中的行更新到输出 y 中。
 */
template <typename T>
__simt_vf__ __aicore__ __launch_bounds__(THREAD_NUM) inline void OpInplaceUpdateSimt(int32_t needCoreNum, int32_t n,
                                                                                     int32_t k, int64_t innerSize,
                                                                                     int32_t perCoreN, __gm__ T* x_gm,
                                                                                     __gm__ int32_t* indices_gm,
                                                                                     __gm__ T* v_gm, __gm__ T* y_gm)
{
    int32_t coreId = blockIdx.x;
    int32_t startRow = coreId * perCoreN;
    int32_t endRow = startRow + perCoreN;
    if (endRow > n) {
        endRow = n;
    }
    if (startRow >= endRow) {
        return;
    }

    // Phase 1: 拷贝 x → y（Per-Core Continuous）
    int64_t startElem = static_cast<int64_t>(startRow) * innerSize;
    int64_t endElem = static_cast<int64_t>(endRow) * innerSize;
    for (int64_t idx = startElem + static_cast<int64_t>(threadIdx.x); idx < endElem;
         idx += static_cast<int64_t>(THREAD_NUM)) {
        y_gm[idx] = x_gm[idx];
    }

    // Phase 2: 索引更新 v → y
    for (int32_t kIdx = 0; kIdx < k; kIdx++) {
        int32_t dstRow = indices_gm[kIdx];
        if (dstRow >= startRow && dstRow < endRow) {
            int64_t vBase = static_cast<int64_t>(kIdx) * innerSize;
            int64_t yBase = static_cast<int64_t>(dstRow) * innerSize;
            for (int64_t offset = static_cast<int64_t>(threadIdx.x); offset < innerSize;
                 offset += static_cast<int64_t>(THREAD_NUM)) {
                y_gm[yBase + offset] = v_gm[vBase + offset];
            }
        }
    }
}

/**
 * @brief 算子 Process 入口
 * 从 tiling 数据中提取参数，启动 SIMT VF。
 */
template <typename T>
__aicore__ inline void Process(GM_ADDR x, GM_ADDR indices, GM_ADDR v, GM_ADDR y, GM_ADDR workspace,
                               const InplaceUpdateTilingData* tilingData)
{
    __gm__ T* x_gm = (__gm__ T*)x;
    __gm__ int32_t* indices_gm = (__gm__ int32_t*)indices;
    __gm__ T* v_gm = (__gm__ T*)v;
    __gm__ T* y_gm = (__gm__ T*)y;

    asc_vf_call<OpInplaceUpdateSimt<T>>(dim3(THREAD_NUM), tilingData->needCoreNum, tilingData->n, tilingData->k,
                                        tilingData->innerSize, tilingData->perCoreN, x_gm, indices_gm, v_gm, y_gm);
}

} // namespace NsInplaceUpdate

#endif // __INPLACE_UPDATE_SIMT_H__
