/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

#include <vector>
#include <algorithm>
#include "util/math_util.h"
#include "register/op_def_registry.h"
#include "tiling/tiling_api.h"
#include "platform/platform_info.h"
#include "log/log.h"
#include "foreach_lerp_list_tiling.h"

using namespace AscendC;

namespace optiling {

constexpr int64_t DCACHE_SIZE = 128 * 1024;
constexpr int64_t SINGLE_CORE_MIN_ELEMENTS = 1024;
constexpr int64_t ALIGN_SIZE = 32;
constexpr int64_t INPUT_IDX_SELF = 0;
constexpr int64_t INPUT_IDX_END = 1;
constexpr int64_t INPUT_IDX_WEIGHT = 2;

static uint64_t GetTilingKeyByDtype(ge::DataType dtype)
{
    switch (dtype) {
        case ge::DT_FLOAT16:
            return 0;
        case ge::DT_FLOAT:
            return 1;
        case ge::DT_BF16:
            return 2;
        default:
            return 0;
    }
}

static ge::graphStatus GetPlatformInfoFallback(
    gert::TilingContext* context, int64_t& coreNum, int64_t& ubSize)
{
    auto compileInfo = reinterpret_cast<const ForeachLerpListCompileInfo*>(context->GetCompileInfo());
    if (compileInfo != nullptr && compileInfo->coreNum > 0 && compileInfo->ubSize > 0) {
        coreNum = compileInfo->coreNum;
        ubSize = compileInfo->ubSize;
        return ge::GRAPH_SUCCESS;
    }
    fe::PlatFormInfos* platformInfoPtr = context->GetPlatformInfo();
    if (platformInfoPtr != nullptr) {
        auto ascendcPlatform = platform_ascendc::PlatformAscendC(platformInfoPtr);
        coreNum = ascendcPlatform.GetCoreNumAiv();
        uint64_t ub = 0;
        ascendcPlatform.GetCoreMemSize(platform_ascendc::CoreMemType::UB, ub);
        ubSize = static_cast<int64_t>(ub);
        if (coreNum > 0 && ubSize > 0) {
            return ge::GRAPH_SUCCESS;
        }
    }
    return ge::GRAPH_FAILED;
}

static ge::graphStatus ForeachLerpListTilingFunc(gert::TilingContext* context)
{
    int64_t coreNum = 0;
    int64_t ubSize = 0;
    OP_CHECK_IF(GetPlatformInfoFallback(context, coreNum, ubSize) != ge::GRAPH_SUCCESS,
        OP_LOGE(context, "Failed to get platform info"),
        return ge::GRAPH_FAILED);

    if (ubSize <= DCACHE_SIZE) {
        ubSize = DCACHE_SIZE + 128 * 1024;
    }
    int64_t usableUbSize = ubSize - DCACHE_SIZE;

    auto computeNodeInfoPtr = context->GetComputeNodeInfo();
    OP_CHECK_NULL_WITH_CONTEXT(context, computeNodeInfoPtr);
    auto selfInstanceInfoPtr = computeNodeInfoPtr->GetInputInstanceInfo(INPUT_IDX_SELF);
    OP_CHECK_NULL_WITH_CONTEXT(context, selfInstanceInfoPtr);
    uint64_t tensorNum = selfInstanceInfoPtr->GetInstanceNum();

    OP_CHECK_IF((static_cast<int32_t>(tensorNum) > MAX_TENSOR_NUM_FOREACH_LERP_LIST_TILING),
        OP_LOGE(context, "tensorNum %lu exceeds max %d", tensorNum, MAX_TENSOR_NUM_FOREACH_LERP_LIST_TILING),
        return ge::GRAPH_FAILED);

    auto weightInstanceInfoPtr = computeNodeInfoPtr->GetInputInstanceInfo(INPUT_IDX_WEIGHT);
    OP_CHECK_NULL_WITH_CONTEXT(context, weightInstanceInfoPtr);
    uint64_t weightTensorNum = weightInstanceInfoPtr->GetInstanceNum();
    OP_CHECK_IF((weightTensorNum != tensorNum),
        OP_LOGE(context, "weight tensor count %lu != self tensor count %lu", weightTensorNum, tensorNum),
        return ge::GRAPH_FAILED);

    ForeachLerpListTilingDataHost* tilingData =
        context->GetTilingData<ForeachLerpListTilingDataHost>();
    OP_CHECK_NULL_WITH_CONTEXT(context, tilingData);

    int64_t totalElements = 0;
    ge::DataType dataType = ge::DT_FLOAT;

    for (int32_t i = 0; i < MAX_TENSOR_NUM_FOREACH_LERP_LIST_TILING; i++) {
        tilingData->cumulativeOffsets[i] = 0;
    }

    for (uint64_t i = 0; i < tensorNum; i++) {
        auto tensorShapePtr = context->GetDynamicInputShape(INPUT_IDX_SELF, i);
        OP_CHECK_NULL_WITH_CONTEXT(context, tensorShapePtr);
        auto tensorShape = tensorShapePtr->GetStorageShape();
        int64_t numel = tensorShape.GetShapeSize();
        totalElements += numel;
        tilingData->cumulativeOffsets[i] = totalElements;

        if (i == 0) {
            auto tensorDtypePtr = context->GetDynamicInputDesc(INPUT_IDX_SELF, i);
            if (tensorDtypePtr != nullptr) {
                dataType = tensorDtypePtr->GetDataType();
            } else {
                OP_LOGW(context, "GetDynamicInputDesc returned null, using default dtype DT_FLOAT");
            }
        }
    }

    int64_t perCoreElements = std::max(SINGLE_CORE_MIN_ELEMENTS,
        (totalElements + coreNum - 1) / coreNum);
    perCoreElements = ((perCoreElements + ALIGN_SIZE - 1) / ALIGN_SIZE) * ALIGN_SIZE;
    int64_t needCoreNum = Ops::Base::CeilDiv(totalElements, perCoreElements);
    needCoreNum = std::max(needCoreNum, static_cast<int64_t>(1));
    needCoreNum = std::min(needCoreNum, coreNum);

    tilingData->needCoreNum = static_cast<int32_t>(needCoreNum);
    tilingData->tensorCount = static_cast<int32_t>(tensorNum);
    tilingData->totalElements = totalElements;
    tilingData->perCoreElements = perCoreElements;

    context->SetBlockDim(needCoreNum);
    context->SetTilingKey(GetTilingKeyByDtype(dataType));

    auto res = context->SetLocalMemorySize(usableUbSize);
    OP_CHECK_IF((res != ge::GRAPH_SUCCESS),
        OP_LOGE(context, "SetLocalMemorySize ubSize=%ld failed", usableUbSize),
        return ge::GRAPH_FAILED);

    size_t* currentWorkspace = context->GetWorkspaceSizes(1);
    currentWorkspace[0] = 0;

    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus TilingParseForForeachLerpList(gert::TilingParseContext* context)
{
    auto compileInfo = context->GetCompiledInfo<ForeachLerpListCompileInfo>();
    OP_CHECK_NULL_WITH_CONTEXT(context, compileInfo);
    auto platformInfo = context->GetPlatformInfo();
    OP_CHECK_NULL_WITH_CONTEXT(context, platformInfo);
    auto ascendcPlatform = platform_ascendc::PlatformAscendC(platformInfo);
    compileInfo->coreNum = ascendcPlatform.GetCoreNumAiv();
    OP_CHECK_IF((compileInfo->coreNum <= 0),
        OP_LOGE(context, "Failed to get core num."),
        return ge::GRAPH_FAILED);
    uint64_t ubSize;
    ascendcPlatform.GetCoreMemSize(platform_ascendc::CoreMemType::UB, ubSize);
    compileInfo->ubSize = static_cast<int64_t>(ubSize);
    OP_CHECK_IF((compileInfo->ubSize <= 0),
        OP_LOGE(context, "Failed to get ub size."),
        return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

IMPL_OP_OPTILING(ForeachLerpList)
    .Tiling(ForeachLerpListTilingFunc)
    .TilingParse<ForeachLerpListCompileInfo>(TilingParseForForeachLerpList);

} // namespace optiling