/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file sparse_apply_ftrl_tiling_data.h
 * \brief tiling data struct for sparse_apply_ftrl
 */

#ifndef SPARSE_APPLY_FTRL_TILING_DATA_H
#define SPARSE_APPLY_FTRL_TILING_DATA_H

struct SparseApplyFtrlTilingData {
    int64_t numIndices;       // indices count (N = grad.shape[0])
    int64_t innerSize;        // elements per row (D1*D2*... = var.shape[1:] product)
    int64_t varDim0;          // var.shape[0] = total rows in var/accum/linear
    // lr/l1/l2/lrPower are read from GM scalar tensors at kernel runtime,
    // not stored in tiling data (GetData unavailable in binary compile mode)
};

#endif // SPARSE_APPLY_FTRL_TILING_DATA_H
