/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file sparse_apply_ftrl_tiling_key.h
 * \brief tiling key definition for sparse_apply_ftrl
 *
 * TilingKey only encodes indices dtype scene (int32/int64).
 * Tensor dtype is always float32, no dtype enumeration needed.
 * Total: 2 kernel variants (schMode: 1 bit)
 */

#ifndef SPARSE_APPLY_FTRL_TILING_KEY_H
#define SPARSE_APPLY_FTRL_TILING_KEY_H

#include "ascendc/host_api/tiling/template_argument.h"

#define SPARSE_APPLY_FTRL_SCH_MODE_INT32 0
#define SPARSE_APPLY_FTRL_SCH_MODE_INT64 1

ASCENDC_TPL_ARGS_DECL(SparseApplyFtrl,
                      ASCENDC_TPL_UINT_DECL(schMode, 1, ASCENDC_TPL_UI_LIST, SPARSE_APPLY_FTRL_SCH_MODE_INT32,
                                            SPARSE_APPLY_FTRL_SCH_MODE_INT64));

ASCENDC_TPL_SEL(
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
                         ASCENDC_TPL_UINT_SEL(schMode, ASCENDC_TPL_UI_LIST, SPARSE_APPLY_FTRL_SCH_MODE_INT32),
                         ASCENDC_TPL_TILING_STRUCT_SEL(SparseApplyFtrlTilingData)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
                         ASCENDC_TPL_UINT_SEL(schMode, ASCENDC_TPL_UI_LIST, SPARSE_APPLY_FTRL_SCH_MODE_INT64),
                         ASCENDC_TPL_TILING_STRUCT_SEL(SparseApplyFtrlTilingData)));

#endif // SPARSE_APPLY_FTRL_TILING_KEY_H
