#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
# ----------------------------------------------------------------------------
# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.
# ----------------------------------------------------------------------------
# Generated By CANNBot

import numpy as np

__golden__ = {
    "kernel": {
        "sparse_apply_ftrl": "sparse_apply_ftrl_golden"
    }
}


def sparse_apply_ftrl_golden(var, accum, linear, grad, indices, lr, l1, l2, lr_power, **kwargs):
    '''
    Kernel golden for SparseApplyFtrl.
    Parameters follow REG_OP definition order:
    - Input parameters: var, accum, linear, grad, indices, lr, l1, l2, lr_power (numpy.ndarray)
    - Output placeholder: * (var_out, accum_out, linear_out not passed)
    - Attr parameters: use_locking (not used)
    kwargs may contain: short_soc_version, input_ori_shapes, output_ori_shapes,
      input_formats, output_formats, input_ori_formats, output_ori_formats,
      input_dtypes, output_dtypes.
    '''
    var_out = var.copy()
    accum_out = accum.copy()
    linear_out = linear.copy()

    # Extract scalar values
    lr_val = float(lr) if hasattr(lr, '__float__') else float(lr.flat[0]) if hasattr(lr, 'flat') else float(lr)
    l1_val = float(l1) if hasattr(l1, '__float__') else float(l1.flat[0]) if hasattr(l1, 'flat') else float(l1)
    l2_val = float(l2) if hasattr(l2, '__float__') else float(l2.flat[0]) if hasattr(l2, 'flat') else float(l2)
    lr_power_val = float(lr_power) if hasattr(lr_power, '__float__') else float(lr_power.flat[0]) if hasattr(lr_power, 'flat') else float(lr_power)

    # Ensure indices is 1-D
    indices_flat = indices.flatten().astype(np.int64)

    for i in range(len(indices_flat)):
        idx = indices_flat[i]
        g = grad[i]

        # accum_new = accum + grad^2
        accum_new = accum_out[idx] + g * g

        # sigma = (accum^(-lr_power) - accum_new^(-lr_power)) / lr
        accum_neg_lr_power = np.power(accum_out[idx], -lr_power_val)
        accum_new_neg_lr_power = np.power(accum_new, -lr_power_val)
        sigma = (accum_neg_lr_power - accum_new_neg_lr_power) / lr_val

        # linear_new = linear + grad + sigma * var
        linear_new = linear_out[idx] + g + sigma * var_out[idx]

        # x = clamp(linear_new, -l1, l1) - linear_new
        x = np.clip(linear_new, -l1_val, l1_val) - linear_new

        # y = accum_new^(-lr_power) / lr + 2 * l2
        y = accum_new_neg_lr_power / lr_val + 2.0 * l2_val

        # var_new = x / y
        var_new = x / y

        var_out[idx] = var_new
        accum_out[idx] = accum_new
        linear_out[idx] = linear_new

    return var_out, accum_out, linear_out
