/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/*!
 * \file matmul_fp32_tiling_key.h
 * \brief matmul_fp32 tiling key declare
 */

#ifndef __MATMUL_FP32_TILING_KEY_H__
#define __MATMUL_FP32_TILING_KEY_H__

#include "ascendc/host_api/tiling/template_argument.h"

#define MAT_MUL_FP32_NO_FULLLOAD 0
#define MAT_MUL_FP32_AL1_FULLLOAD 1
#define MAT_MUL_FP32_BL1_FULLLOAD 2

#define MAT_MUL_FP32_BASE_SPLIT_K 0

#define MAT_MUL_FP32_BASE_FIXOPTI 0

#define MAT_MUL_FP32_MIXND2NZ_TRUE 0

ASCENDC_TPL_ARGS_DECL(
    MatmulFp32,
    ASCENDC_TPL_UINT_DECL(
        LOADMODE, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST, MAT_MUL_FP32_NO_FULLLOAD, MAT_MUL_FP32_AL1_FULLLOAD, MAT_MUL_FP32_BL1_FULLLOAD),
    ASCENDC_TPL_UINT_DECL(SPLITCOREMODE, ASCENDC_TPL_8_BW, ASCENDC_TPL_UI_LIST, MAT_MUL_FP32_BASE_SPLIT_K),
    ASCENDC_TPL_UINT_DECL(FIXOPTI, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST, MAT_MUL_FP32_BASE_FIXOPTI),
    ASCENDC_TPL_UINT_DECL(MIXND2NZ, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST, MAT_MUL_FP32_MIXND2NZ_TRUE), );

ASCENDC_TPL_SEL(
    ASCENDC_TPL_ARGS_SEL(
    ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIC_ONLY),
    ASCENDC_TPL_UINT_SEL(LOADMODE, ASCENDC_TPL_UI_LIST, MAT_MUL_FP32_NO_FULLLOAD),
    ASCENDC_TPL_UINT_SEL(SPLITCOREMODE, ASCENDC_TPL_UI_LIST, MAT_MUL_FP32_BASE_SPLIT_K),
    ASCENDC_TPL_UINT_SEL(FIXOPTI, ASCENDC_TPL_UI_LIST, MAT_MUL_FP32_BASE_FIXOPTI),
    ASCENDC_TPL_UINT_SEL(MIXND2NZ, ASCENDC_TPL_UI_LIST, MAT_MUL_FP32_MIXND2NZ_TRUE), ),

ASCENDC_TPL_ARGS_SEL(
    ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIC_ONLY),
    ASCENDC_TPL_UINT_SEL(LOADMODE, ASCENDC_TPL_UI_LIST, MAT_MUL_FP32_BL1_FULLLOAD),
    ASCENDC_TPL_UINT_SEL(SPLITCOREMODE, ASCENDC_TPL_UI_LIST, MAT_MUL_FP32_BASE_SPLIT_K),
    ASCENDC_TPL_UINT_SEL(FIXOPTI, ASCENDC_TPL_UI_LIST, MAT_MUL_FP32_BASE_FIXOPTI),
    ASCENDC_TPL_UINT_SEL(MIXND2NZ, ASCENDC_TPL_UI_LIST, MAT_MUL_FP32_MIXND2NZ_TRUE),),);
#endif