/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/**
 * NOTE: Portions of this code were AI-generated and have been
 * technically reviewed for functional accuracy and security
 * Generated By CANNBot
 */

/**
 * \file apply_proximal_adagrad.h
 * \brief ApplyProximalAdagrad kernel class (arch35 / Ascend950).
 *
 * Implements the Proximal Adagrad update per element:
 *
 *   accum = accum + grad * grad
 *   eta   = lr * rsqrt(accum)
 *   prox  = var - eta * grad
 *   if (l1 > 0):
 *     var = sign(prox) * max(|prox| - eta*l1, 0) / (1 + eta*l2)
 *   else:
 *     var = prox / (1 + eta*l2)
 *
 * Routes (D_T_VAR, PAD_TAIL, HAS_L1):
 *   - D_T_VAR = float       : direct fp32 compute, no Cast.
 *   - D_T_VAR = half        : fp16 input -> Cast to fp32 (CAST_NONE) on CopyIn,
 *       compute in fp32, Cast back to fp16 (CAST_RINT) on CopyOut.
 *       This mirrors canndev A2 TBE (apply_proximal_adagrad_d.py:97-131).
 *   - D_T_VAR = bfloat16_t  : bf16 input -> Cast to fp32 (CAST_NONE) on CopyIn,
 *       compute in fp32, Cast back to bf16 (CAST_ROUND) on CopyOut.
 *       LoadScalar uses a 32B-aligned LocalTensor + Vector Cast to convert
 *       lr/l1/l2 from bf16 GM to fp32 register, avoiding the scalar-path
 *       bf16->float cast that triggers "not support bf16 type cast" on the
 *       bisheng backend.
 *
 *   - PAD_TAIL: 0 (aligned tail) / 1 (non-aligned tail).  Both branches use
 *     DataCopyPad which is alignment-tolerant; the flag is preserved so future
 *     iterations can swap in a faster pure-DataCopy fast path on PAD_TAIL=0.
 *   - HAS_L1: 1 (general path with sign + soft-threshold).  The kernel also
 *     applies a runtime fast-path when l1Scalar_ == 0 inside this branch (this
 *     is the path taken when host cannot read l1 from GM at tiling time).
 *   - HAS_L1: 0 (dedicated fast path - sign / soft-threshold statically
 *     dropped).  Reachable via host-side hint or UT.
 */

#ifndef APPLY_PROXIMAL_ADAGRAD_H
#define APPLY_PROXIMAL_ADAGRAD_H

#include "kernel_operator.h"
#include "kernel_tiling/kernel_tiling.h"
#include "apply_proximal_adagrad_tiling_data.h"
#include "apply_proximal_adagrad_tiling_key.h"

namespace NsApplyProximalAdagrad {

using AscendC::TPipe;
using AscendC::TQue;
using AscendC::TBuf;
using AscendC::QuePosition;
using AscendC::GlobalTensor;
using AscendC::LocalTensor;
using AscendC::DataCopyParams;
using AscendC::DataCopyPad;
using AscendC::DataCopyExtParams;
using AscendC::DataCopyPadExtParams;
using AscendC::GetBlockIdx;
using AscendC::Add;
using AscendC::Sub;
using AscendC::Mul;
using AscendC::Muls;
using AscendC::Adds;
using AscendC::Abs;
using AscendC::Div;
using AscendC::Rsqrt;
using AscendC::Maxs;
using AscendC::Compare;
using AscendC::Compares;
using AscendC::CompareScalar;
using AscendC::Select;
using AscendC::Duplicate;
using AscendC::CMPMODE;
using AscendC::SELMODE;
using AscendC::Cast;
using AscendC::RoundMode;
using AscendC::Duplicate;
using AscendC::HardEvent;
using AscendC::SetFlag;
using AscendC::WaitFlag;
// NOTE: GetTPipePtr() and event_t are declared in the global namespace by
// kernel_common.h / cce_aicore_intrinsics.h, NOT inside namespace AscendC.
// We therefore reference them via ::GetTPipePtr / ::event_t below.

template <typename T, bool PAD_TAIL = true, bool HAS_L1 = true>
class ApplyProximalAdagrad {
public:
    __aicore__ inline ApplyProximalAdagrad() {}

    __aicore__ inline void Init(GM_ADDR var, GM_ADDR accum,
                                GM_ADDR lr, GM_ADDR l1, GM_ADDR l2,
                                GM_ADDR grad,
                                GM_ADDR varOut, GM_ADDR accumOut,
                                const ApplyProximalAdagradTilingData* tilingData);
    __aicore__ inline void Process();

private:
    __aicore__ inline void CopyInTile(int64_t gmOffset, int64_t currentNum);
    __aicore__ inline void Compute(int64_t currentNum);
    __aicore__ inline void CopyOutTile(int64_t gmOffset, int64_t currentNum);

    // Per-tile fp32 compute kernel shared by both fp32 native and fp16/bf16
    // cast paths. Inputs/outputs are all LocalTensor<float>; the cast path
    // wraps this with Cast(native -> fp32) on entry and Cast(fp32 -> native)
    // on exit.
    __aicore__ inline void ComputeFp32Core(
        const LocalTensor<float>& varF32,
        const LocalTensor<float>& accumF32,
        const LocalTensor<float>& gradF32,
        const LocalTensor<float>& varOutF32,
        const LocalTensor<float>& accumOutF32,
        int32_t n);

    // Init helpers split out of Init() to keep each step under the NBNC
    // limit. All require ubFactor_ to be already set.
    __aicore__ inline void InitUbBuffers();
    __aicore__ inline void BuildBf16OneConstant();

    // NOTE: deliberately non-const: the bfloat16_t specialisation writes into
    // scalarLoadBuf_ / scalarLoadF32Buf_ to perform a vector-side Cast that
    // avoids the unsupported scalar-path bf16 -> float conversion.
    __aicore__ inline float LoadScalar(const GlobalTensor<T>& src);

private:
    TPipe pipe_;
    // IN queues: var / accum / grad, double-buffered.
    TQue<QuePosition::VECIN, 2> varInQue_;
    TQue<QuePosition::VECIN, 2> accumInQue_;
    TQue<QuePosition::VECIN, 2> gradInQue_;
    // OUT queues: var / accum, double-buffered.
    TQue<QuePosition::VECOUT, 2> varOutQue_;
    TQue<QuePosition::VECOUT, 2> accumOutQue_;
    // fp32 cast-buffers (only allocated on the fp16/bf16 path).
    TBuf<QuePosition::VECCALC> varF32Buf_;
    TBuf<QuePosition::VECCALC> accumF32Buf_;
    TBuf<QuePosition::VECCALC> gradF32Buf_;
    // fp32 scratch compute buffers (both paths share).
    TBuf<QuePosition::VECCALC> etaBuf_;       // lr * rsqrt(accum)
    TBuf<QuePosition::VECCALC> proxBuf_;      // var - eta * grad
    TBuf<QuePosition::VECCALC> threshBuf_;    // max(|prox| - eta*l1, 0) and helpers
    TBuf<QuePosition::VECCALC> scaleBuf_;     // 1 + eta * l2

    // Scratch buffers for bf16 scalar loading via LocalTensor + Vector Cast.
    // Only allocated on the bf16 path; both buffers are 32B (one DMA block).
    // See LoadScalar() for the rationale.
    TBuf<QuePosition::VECCALC> scalarLoadBuf_;     // bf16 LocalTensor (32B)
    TBuf<QuePosition::VECCALC> scalarLoadF32Buf_;  // fp32 LocalTensor (32B)

    GlobalTensor<T> varGm_;
    GlobalTensor<T> accumGm_;
    GlobalTensor<T> gradGm_;
    GlobalTensor<T> lrGm_;
    GlobalTensor<T> l1Gm_;
    GlobalTensor<T> l2Gm_;
    GlobalTensor<T> varOutGm_;
    GlobalTensor<T> accumOutGm_;

    // Scalars loaded from GM at Init time, always promoted to float for
    // intra-kernel use regardless of dtype path.
    float lrScalar_ = 0.0f;
    float l1Scalar_ = 0.0f;
    float l2Scalar_ = 0.0f;

    // Pre-built bf16 constant buffer (32B = 16 bf16 elements). Slot [0] holds
    // a bf16 1.0 value constructed once in Init() via the supported
    // vector-path fp32 -> bf16 Cast. Used by CopyInTile() to pre-fill
    // accumLocal's tail without ever invoking scalar-side bf16 construction.
    // Only allocated on the bf16 path.
    TBuf<QuePosition::VECCALC> bf16ConstBuf_;

    int64_t blockOffset_ = 0;
    int64_t blockLen_ = 0;
    int64_t ubFactor_ = 0;
};

// =============================================================================
// LoadScalar: pick the first element of a 1-element GM tensor into a float
// register.
//
// fp32 / fp16: direct GetValue + static_cast<float>. The bisheng backend
//   supports scalar-path half -> float and float -> float conversions.
//
// bfloat16_t: the scalar-path bf16 -> float conversion is NOT supported by
//   the current bisheng backend ("not support bf16 type cast"). Instead, we
//   DMA the 1-element scalar into a 32B-aligned bf16 LocalTensor, run a
//   vector Cast (CAST_NONE) to a 32B fp32 LocalTensor, and then read element
//   [0] -- this hits the supported vector-path bf16 -> float instruction.
//
// Memory cost: two 32B UB buffers (allocated only on bf16 path).
// Sync: MTE2_V (after DataCopyPad) then V_S (after Cast) to flush each stage
//       before the next reads its result.
// =============================================================================
template <typename T, bool PAD_TAIL, bool HAS_L1>
__aicore__ inline float ApplyProximalAdagrad<T, PAD_TAIL, HAS_L1>::LoadScalar(
    const GlobalTensor<T>& src)
{
    if constexpr (std::is_same_v<T, bfloat16_t>) {
        LocalTensor<T> tmp = scalarLoadBuf_.template Get<T>();
        LocalTensor<float> tmpF32 = scalarLoadF32Buf_.template Get<float>();

        // DMA exactly 1 bf16 element from GM into UB. blockLen counts bytes
        // (sizeof(bf16) = 2), DataCopyPad zero-pads the trailing lanes inside
        // the 32B block. We do NOT use a custom pad value (avoids the
        // static_cast<T>(0) scalar-path issue): the integer literal `0` in
        // DataCopyPadExtParams<bf16> is the documented usage (see
        // log_softmax_v2.h:1418 and friends).
        DataCopyExtParams params;
        params.blockCount = 1;
        params.blockLen = static_cast<uint32_t>(sizeof(T));
        params.srcStride = 0;
        params.dstStride = 0;
        DataCopyPadExtParams<T> pad{false, 0, 0, 0};
        DataCopyPad(tmp, src, params, pad);

        // Sync MTE2 -> Vector before Cast reads tmp.
        event_t evtMte2V = static_cast<event_t>(
            GetTPipePtr()->FetchEventID(HardEvent::MTE2_V));
        SetFlag<HardEvent::MTE2_V>(evtMte2V);
        WaitFlag<HardEvent::MTE2_V>(evtMte2V);

        // Vector Cast bf16 -> fp32. Repeat counts in elements; 32B / sizeof(fp32)
        // = 8 elements covers the full 32B UB block.
        constexpr int32_t kBlockF32 = 32 / sizeof(float);
        Cast(tmpF32, tmp, RoundMode::CAST_NONE, kBlockF32);

        // Sync Vector -> Scalar before scalar-path GetValue reads tmpF32.
        event_t evtVS = static_cast<event_t>(
            GetTPipePtr()->FetchEventID(HardEvent::V_S));
        SetFlag<HardEvent::V_S>(evtVS);
        WaitFlag<HardEvent::V_S>(evtVS);

        return tmpF32.GetValue(0);
    } else {
        return static_cast<float>(src.GetValue(0));
    }
}

// =============================================================================
// InitUbBuffers: allocate every UB buffer needed by the chosen dtype path.
//   - All paths: 3 IN queues + 2 OUT queues + 4 fp32 scratch buffers.
//   - fp16/bf16 path: + 3 fp32 cast buffers.
//   - bf16 path: + 3 x 32B scratch (scalar load + bf16 const buffer).
//   The bf16 scratch buffers must be allocated BEFORE LoadScalar runs in Init().
// =============================================================================
template <typename T, bool PAD_TAIL, bool HAS_L1>
__aicore__ inline void
ApplyProximalAdagrad<T, PAD_TAIL, HAS_L1>::InitUbBuffers()
{
    // Queue tensors at native dtype.
    pipe_.InitBuffer(varInQue_,   2, ubFactor_ * sizeof(T));
    pipe_.InitBuffer(accumInQue_, 2, ubFactor_ * sizeof(T));
    pipe_.InitBuffer(gradInQue_,  2, ubFactor_ * sizeof(T));
    pipe_.InitBuffer(varOutQue_,   2, ubFactor_ * sizeof(T));
    pipe_.InitBuffer(accumOutQue_, 2, ubFactor_ * sizeof(T));

    // fp32 cast buffers only allocated on fp16/bf16 path (fp32 path operates
    // directly on the queue tensors).
    if constexpr (!std::is_same_v<T, float>) {
        pipe_.InitBuffer(varF32Buf_,   ubFactor_ * sizeof(float));
        pipe_.InitBuffer(accumF32Buf_, ubFactor_ * sizeof(float));
        pipe_.InitBuffer(gradF32Buf_,  ubFactor_ * sizeof(float));
    }

    // bf16 path scratch buffers for LoadScalar's vector-Cast workaround +
    // bf16 constant buffer for tail-padding.
    if constexpr (std::is_same_v<T, bfloat16_t>) {
        pipe_.InitBuffer(scalarLoadBuf_,    32);
        pipe_.InitBuffer(scalarLoadF32Buf_, 32);
        pipe_.InitBuffer(bf16ConstBuf_,     32);
    }

    // fp32 scratch (both paths share).
    pipe_.InitBuffer(etaBuf_,    ubFactor_ * sizeof(float));
    pipe_.InitBuffer(proxBuf_,   ubFactor_ * sizeof(float));
    pipe_.InitBuffer(threshBuf_, ubFactor_ * sizeof(float));
    pipe_.InitBuffer(scaleBuf_,  ubFactor_ * sizeof(float));
}

// =============================================================================
// BuildBf16OneConstant: build a bf16(1.0) constant once via the supported
//   vector Cast path (scalar-side float -> bf16 is unsupported by bisheng).
//   CopyInTile reads slot [0] via GetValue(0) on every tile to pre-fill the
//   accumLocal tail.  No-op for non-bf16 paths.
// =============================================================================
template <typename T, bool PAD_TAIL, bool HAS_L1>
__aicore__ inline void
ApplyProximalAdagrad<T, PAD_TAIL, HAS_L1>::BuildBf16OneConstant()
{
    if constexpr (std::is_same_v<T, bfloat16_t>) {
        LocalTensor<float> oneF32   = scalarLoadF32Buf_.template Get<float>();
        LocalTensor<T>     oneConst = bf16ConstBuf_.template Get<T>();
        constexpr int32_t kBlockF32 = 32 / sizeof(float);
        Duplicate(oneF32, 1.0f, kBlockF32);
        AscendC::PipeBarrier<PIPE_V>();
        Cast(oneConst, oneF32, RoundMode::CAST_ROUND, kBlockF32);
        // Sync V -> S so subsequent CopyInTile::GetValue reads the new value.
        event_t evtVS = static_cast<event_t>(
            GetTPipePtr()->FetchEventID(HardEvent::V_S));
        SetFlag<HardEvent::V_S>(evtVS);
        WaitFlag<HardEvent::V_S>(evtVS);
    }
}

// =============================================================================
// Init
// =============================================================================
template <typename T, bool PAD_TAIL, bool HAS_L1>
__aicore__ inline void ApplyProximalAdagrad<T, PAD_TAIL, HAS_L1>::Init(
    GM_ADDR var, GM_ADDR accum,
    GM_ADDR lr, GM_ADDR l1, GM_ADDR l2,
    GM_ADDR grad,
    GM_ADDR varOut, GM_ADDR accumOut,
    const ApplyProximalAdagradTilingData* tilingData)
{
    ubFactor_ = tilingData->ubFactor;

    // Empty-tensor / degenerate tiling -> just record zero length; Process()
    // will short-circuit.
    if (tilingData->totalElements == 0 || tilingData->blockFactor == 0) {
        blockOffset_ = 0;
        blockLen_ = 0;
        return;
    }

    blockOffset_ = tilingData->blockFactor * static_cast<int64_t>(GetBlockIdx());
    int64_t remaining = tilingData->totalElements - blockOffset_;
    if (remaining <= 0) {
        blockLen_ = 0;
        return;
    }
    blockLen_ = (remaining > tilingData->blockFactor)
                    ? tilingData->blockFactor
                    : remaining;

    // Main vectorised tensors -- slice each core's view.
    varGm_.SetGlobalBuffer((__gm__ T*)var + blockOffset_, blockLen_);
    accumGm_.SetGlobalBuffer((__gm__ T*)accum + blockOffset_, blockLen_);
    gradGm_.SetGlobalBuffer((__gm__ T*)grad + blockOffset_, blockLen_);
    varOutGm_.SetGlobalBuffer((__gm__ T*)varOut + blockOffset_, blockLen_);
    accumOutGm_.SetGlobalBuffer((__gm__ T*)accumOut + blockOffset_, blockLen_);

    // Scalar tensors: single element broadcast-read.
    lrGm_.SetGlobalBuffer((__gm__ T*)lr, 1);
    l1Gm_.SetGlobalBuffer((__gm__ T*)l1, 1);
    l2Gm_.SetGlobalBuffer((__gm__ T*)l2, 1);

    InitUbBuffers();

    // LoadScalar requires the bf16 scratch buffers (allocated by
    // InitUbBuffers) to be ready on the bf16 path.
    lrScalar_ = LoadScalar(lrGm_);
    l1Scalar_ = LoadScalar(l1Gm_);
    l2Scalar_ = LoadScalar(l2Gm_);

    BuildBf16OneConstant();
}

// =============================================================================
// CopyInTile: pad-aware DataCopyPad of var / accum / grad.
//   DataCopyPad transparently handles aligned and non-aligned blockLen, so the
//   same primitive serves both PAD_TAIL=0 (aligned tile) and PAD_TAIL=1
//   (non-aligned tail) routes.
//
// Tail-padding strategy:
//   var / grad: pad with 0    -> grad=0 keeps accum unchanged, prox=var.
//   accum:      pad with 1    -> Rsqrt(accum + grad^2) = Rsqrt(1) = 1,
//                                avoiding Rsqrt(0)=+Inf -> NaN cascade.
//
// dtype-specific construction:
//   fp32 / fp16: padValue can be constructed via `static_cast<T>(0)` /
//     `static_cast<T>(1.0f)` - both are supported scalar conversions.
//   bf16: scalar `static_cast<bfloat16_t>(0|1.0f)` triggers the bisheng
//     "not support bf16 type cast" backend error. We instead Duplicate-fill
//     the LocalTensor in UB BEFORE DataCopyPad (which only overwrites the
//     first `currentNum` lanes), and pass `{false, 0, 0, 0}` (no padding)
//     to DataCopyPadExtParams - the int literal `0` is the documented
//     bf16-safe spelling (see log_softmax_v2.h:1418).
// =============================================================================
template <typename T, bool PAD_TAIL, bool HAS_L1>
__aicore__ inline void ApplyProximalAdagrad<T, PAD_TAIL, HAS_L1>::CopyInTile(
    int64_t gmOffset, int64_t currentNum)
{
    LocalTensor<T> varLocal   = varInQue_.template AllocTensor<T>();
    LocalTensor<T> accumLocal = accumInQue_.template AllocTensor<T>();
    LocalTensor<T> gradLocal  = gradInQue_.template AllocTensor<T>();

    DataCopyExtParams copyParams;
    copyParams.blockCount = 1;
    copyParams.blockLen = static_cast<uint32_t>(currentNum * sizeof(T));
    copyParams.srcStride = 0;
    copyParams.dstStride = 0;

    constexpr int64_t kAlignBlock = 32 / sizeof(T);
    int64_t alignedNum =
        ((currentNum + kAlignBlock - 1) / kAlignBlock) * kAlignBlock;

    if constexpr (std::is_same_v<T, bfloat16_t>) {
        // ----- bf16 path: scalar-construction-free padding ------------------
        // Why this is structured differently from fp32/fp16:
        //   The scalar conversions `static_cast<bfloat16_t>(0)` and
        //   `static_cast<bfloat16_t>(1.0f)` route through the bisheng
        //   scalar-path bf16 type-cast instruction, which is not
        //   implemented ("not support bf16 type cast"). So we must
        //   construct any bf16 fill value via the supported VECTOR-path
        //   Cast instruction instead.
        //
        // Strategy for var / grad (fill with bf16 0): use DataCopyPad with
        //   pad value `0` (int literal) - DataCopyPadExtParams<bf16>
        //   stores this via the integer-zero bit pattern of bf16, no
        //   explicit float->bf16 cast happens (this is the spelling used
        //   by log_softmax_v2.h:1418 and friends).
        //
        // Strategy for accum (fill with bf16 1.0): integer `1` does NOT
        //   match the bf16 bit pattern for 1.0, so we cannot use the same
        //   shortcut. Instead:
        //     1. Read a cached bf16(1.0) value from bf16ConstBuf_ (built
        //        once in Init() via the supported vector-path Cast).
        //     2. Duplicate-fill accumLocal[0..alignedNum) before DMA.
        //     3. DataCopyPad with padding=false so the DMA does not
        //        overwrite the pre-filled tail.
        uint8_t rightPadCount = static_cast<uint8_t>(alignedNum - currentNum);
        DataCopyPadExtParams<T> padIntZeroParams{true, 0, rightPadCount, 0};
        DataCopyPadExtParams<T> padNoneParams{false, 0, 0, 0};

        // Read pre-built bf16(1.0) (no scalar-side construction) and
        // Duplicate across accumLocal.
        LocalTensor<T> oneConst = bf16ConstBuf_.template Get<T>();
        T oneVal = oneConst.GetValue(0);
        // Sync S -> V before Duplicate reads oneVal.
        event_t evtSV = static_cast<event_t>(
            GetTPipePtr()->FetchEventID(HardEvent::S_V));
        SetFlag<HardEvent::S_V>(evtSV);
        WaitFlag<HardEvent::S_V>(evtSV);
        Duplicate(accumLocal, oneVal, static_cast<int32_t>(alignedNum));
        // Sync V -> MTE2 before DataCopyPad overwrites accumLocal[0..currentNum).
        event_t evtVMte2 = static_cast<event_t>(
            GetTPipePtr()->FetchEventID(HardEvent::V_MTE2));
        SetFlag<HardEvent::V_MTE2>(evtVMte2);
        WaitFlag<HardEvent::V_MTE2>(evtVMte2);

        DataCopyPad(varLocal,   varGm_[gmOffset],   copyParams, padIntZeroParams);
        DataCopyPad(accumLocal, accumGm_[gmOffset], copyParams, padNoneParams);
        DataCopyPad(gradLocal,  gradGm_[gmOffset],  copyParams, padIntZeroParams);
    } else {
        // fp32 / fp16 path: original DataCopyPad pad-value mechanism is
        // safe (both half and float scalar conversions are supported).
        uint8_t rightPadCount = static_cast<uint8_t>(alignedNum - currentNum);
        DataCopyPadExtParams<T> padZeroParams{true, 0, rightPadCount, static_cast<T>(0)};
        DataCopyPadExtParams<T> padOneParams{true, 0, rightPadCount, static_cast<T>(1.0f)};

        DataCopyPad(varLocal,   varGm_[gmOffset],   copyParams, padZeroParams);
        DataCopyPad(accumLocal, accumGm_[gmOffset], copyParams, padOneParams);
        DataCopyPad(gradLocal,  gradGm_[gmOffset],  copyParams, padZeroParams);
    }

    varInQue_.EnQue(varLocal);
    accumInQue_.EnQue(accumLocal);
    gradInQue_.EnQue(gradLocal);
}

// =============================================================================
// CopyOutTile: write back var / accum to their inplace GM slots.  DataCopyPad
//   honours the exact byte length, so non-aligned tails do not over-write
//   neighbouring cores' data.
// =============================================================================
template <typename T, bool PAD_TAIL, bool HAS_L1>
__aicore__ inline void ApplyProximalAdagrad<T, PAD_TAIL, HAS_L1>::CopyOutTile(
    int64_t gmOffset, int64_t currentNum)
{
    LocalTensor<T> varOutLocal = varOutQue_.template DeQue<T>();
    LocalTensor<T> accumOutLocal = accumOutQue_.template DeQue<T>();

    DataCopyExtParams copyParams;
    copyParams.blockCount = 1;
    copyParams.blockLen = static_cast<uint32_t>(currentNum * sizeof(T));
    copyParams.srcStride = 0;
    copyParams.dstStride = 0;

    DataCopyPad(varOutGm_[gmOffset],   varOutLocal,   copyParams);
    DataCopyPad(accumOutGm_[gmOffset], accumOutLocal, copyParams);

    varOutQue_.FreeTensor(varOutLocal);
    accumOutQue_.FreeTensor(accumOutLocal);
}

// =============================================================================
// Compute: per-tile compute body. Always operates in fp32 internally.
//
// fp32 path (D_T_VAR = float):
//   Direct fp32 compute on the queue tensors (LocalTensor<float>).
//
// fp16 / bf16 path (D_T_VAR = half / bfloat16_t):
//   1. Cast(varF32, varLocal,  CAST_NONE) ... same for accum/grad
//   2. compute in fp32 on (varF32, accumF32, gradF32) -> (varOutF32, accumOutF32)
//   3. Cast(varOutLocal, varOutF32, CAST_RINT) ... same for accum
//
// Common compute body (fp32):
//   accum' = accum + grad*grad
//   eta    = lr * rsqrt(accum')
//   prox   = var - eta * grad
// HAS_L1 branch detail is documented inline at the call sites below.
// =============================================================================
template <typename T, bool PAD_TAIL, bool HAS_L1>
__aicore__ inline void ApplyProximalAdagrad<T, PAD_TAIL, HAS_L1>::ComputeFp32Core(
    const LocalTensor<float>& varF32,
    const LocalTensor<float>& accumF32,
    const LocalTensor<float>& gradF32,
    const LocalTensor<float>& varOutF32,
    const LocalTensor<float>& accumOutF32,
    int32_t n)
{
    LocalTensor<float> etaTmp    = etaBuf_.template Get<float>();
    LocalTensor<float> proxTmp   = proxBuf_.template Get<float>();
    LocalTensor<float> threshTmp = threshBuf_.template Get<float>();
    LocalTensor<float> scaleTmp  = scaleBuf_.template Get<float>();

    // S1: accumOut = accum + grad*grad. etaTmp is reused immediately by S2.
    Mul(etaTmp, gradF32, gradF32, n);
    Add(accumOutF32, accumF32, etaTmp, n);

    // S2: eta = lr * rsqrt(accumOut)
    // Caller contract guarantees accum >= 0 (typically > 0). If
    // accum + grad^2 == 0, Rsqrt returns +Inf and downstream eta*grad becomes
    // Inf*0 = NaN. This matches PyTorch / TensorFlow semantics; the
    // safe-input contract is the caller's responsibility. CopyInTile pads
    // the [currentNum, alignedNum) tail with accum=1, so padding lanes never
    // trigger this path.
    Rsqrt(etaTmp, accumOutF32, n);
    Muls(etaTmp, etaTmp, lrScalar_, n);

    // S3: prox = var - eta * grad
    Mul(proxTmp, etaTmp, gradF32, n);
    Sub(proxTmp, varF32, proxTmp, n);

    if constexpr (HAS_L1) {
        if (l1Scalar_ == 0.0f) {
            // Runtime fast-path: sign + soft-threshold collapse.
            // var = prox / (1 + eta*l2)
            Muls(scaleTmp, etaTmp, l2Scalar_, n);
            Adds(scaleTmp, scaleTmp, 1.0f, n);
            Div(varOutF32, proxTmp, scaleTmp, n);
        } else {
            // S4a: thresh = max(|prox| - eta*l1, 0)
            Abs(threshTmp, proxTmp, n);
            Muls(scaleTmp, etaTmp, l1Scalar_, n);
            Sub(threshTmp, threshTmp, scaleTmp, n);
            Maxs(threshTmp, threshTmp, 0.0f, n);

            // S4b: signed_thresh = prox >= 0 ? thresh : -thresh.
            // Reuse varOutF32 storage as mask buffer; uint8_t mask occupies
            // 1/4 the bytes, so the alias does not overflow. Safe because
            // varOutF32 is not read again until the final Div writes it.
            Muls(scaleTmp, threshTmp, -1.0f, n);
            LocalTensor<uint8_t> maskTensor =
                varOutF32.template ReinterpretCast<uint8_t>();
            CompareScalar(maskTensor, proxTmp, 0.0f, CMPMODE::GE, n);
            Select(proxTmp, maskTensor, threshTmp, scaleTmp,
                   SELMODE::VSEL_TENSOR_TENSOR_MODE, n);

            // S5: var = signed_thresh / (1 + eta*l2)
            Muls(scaleTmp, etaTmp, l2Scalar_, n);
            Adds(scaleTmp, scaleTmp, 1.0f, n);
            Div(varOutF32, proxTmp, scaleTmp, n);
        }
    } else {
        // HAS_L1 == false: var = prox / (1 + eta*l2)
        Muls(scaleTmp, etaTmp, l2Scalar_, n);
        Adds(scaleTmp, scaleTmp, 1.0f, n);
        Div(varOutF32, proxTmp, scaleTmp, n);
    }
}

template <typename T, bool PAD_TAIL, bool HAS_L1>
__aicore__ inline void ApplyProximalAdagrad<T, PAD_TAIL, HAS_L1>::Compute(
    int64_t currentNum)
{
    LocalTensor<T> varLocal   = varInQue_.template DeQue<T>();
    LocalTensor<T> accumLocal = accumInQue_.template DeQue<T>();
    LocalTensor<T> gradLocal  = gradInQue_.template DeQue<T>();

    LocalTensor<T> varOutLocal   = varOutQue_.template AllocTensor<T>();
    LocalTensor<T> accumOutLocal = accumOutQue_.template AllocTensor<T>();

    // Align work count to 32B / sizeof(float) = 8 elements on the fp32 side.
    // ubFactor is already 32B-aligned for the native dtype, but the compute
    // body operates in fp32, so we use the fp32 block size here.
    constexpr int64_t kAlignBlockF32 = 32 / sizeof(float);
    int64_t alignedNum =
        ((currentNum + kAlignBlockF32 - 1) / kAlignBlockF32) * kAlignBlockF32;
    int32_t n = static_cast<int32_t>(alignedNum);

    if constexpr (std::is_same_v<T, float>) {
        // fp32 native path: queue tensors are already LocalTensor<float>.
        ComputeFp32Core(varLocal, accumLocal, gradLocal,
                        varOutLocal, accumOutLocal, n);
    } else {
        // fp16 / bf16 cast path: Cast in -> compute in fp32 (in-place on the
        // cast buffers) -> Cast back to native dtype.
        LocalTensor<float> varF32   = varF32Buf_.template Get<float>();
        LocalTensor<float> accumF32 = accumF32Buf_.template Get<float>();
        LocalTensor<float> gradF32  = gradF32Buf_.template Get<float>();

        // CAST_NONE for both half/bfloat16 -> float.
        Cast(varF32,   varLocal,   RoundMode::CAST_NONE, n);
        Cast(accumF32, accumLocal, RoundMode::CAST_NONE, n);
        Cast(gradF32,  gradLocal,  RoundMode::CAST_NONE, n);

        // varF32 / accumF32 used as both input and output (in-place).
        ComputeFp32Core(varF32, accumF32, gradF32, varF32, accumF32, n);

        // Cast back fp32 -> native dtype on output queue tensors.
        // Round mode is dtype-specific:
        //   half: CAST_RINT (round-half-to-even, matches IEEE half).
        //   bf16: CAST_ROUND (matches PyTorch / apply_adam_w_v2_b16.h).
        if constexpr (std::is_same_v<T, bfloat16_t>) {
            Cast(varOutLocal,   varF32,   RoundMode::CAST_ROUND, n);
            Cast(accumOutLocal, accumF32, RoundMode::CAST_ROUND, n);
        } else {
            Cast(varOutLocal,   varF32,   RoundMode::CAST_RINT, n);
            Cast(accumOutLocal, accumF32, RoundMode::CAST_RINT, n);
        }
    }

    varOutQue_.template EnQue<T>(varOutLocal);
    accumOutQue_.template EnQue<T>(accumOutLocal);

    varInQue_.FreeTensor(varLocal);
    accumInQue_.FreeTensor(accumLocal);
    gradInQue_.FreeTensor(gradLocal);
}

// =============================================================================
// Process: main loop over UB-sized chunks.
// =============================================================================
template <typename T, bool PAD_TAIL, bool HAS_L1>
__aicore__ inline void ApplyProximalAdagrad<T, PAD_TAIL, HAS_L1>::Process()
{
    if (blockLen_ <= 0) {
        return;
    }
    int64_t loopCount = (blockLen_ + ubFactor_ - 1) / ubFactor_;
    for (int64_t i = 0; i < loopCount; i++) {
        int64_t gmOffset = i * ubFactor_;
        int64_t currentNum = (i == (loopCount - 1))
                                 ? (blockLen_ - gmOffset)
                                 : ubFactor_;
        CopyInTile(gmOffset, currentNum);
        Compute(currentNum);
        CopyOutTile(gmOffset, currentNum);
    }
}

} // namespace NsApplyProximalAdagrad

#endif // APPLY_PROXIMAL_ADAGRAD_H
