/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file apply_centered_rms_prop_tiling.cpp
 * \brief ApplyCenteredRMSProp tiling logic (arch35 / Ascend950)
 *
 * UB budget analysis:
 *   fp16/bf16: 9 T-queues (2B) + 7 FP32 queues (4B) = 18+28 = 46 B/elem
 *   fp32:      9 T-queues (4B) + 7 FP32 queues (4B) = 36+28 = 64 B/elem
 *              (FP32 queues are allocated but unused for fp32 path; simplifies kernel code)
 */
#include "register/op_def_registry.h"
#include "op_common/log/log.h"
#include "op_common/op_host/util/math_util.h"
#include "op_common/op_host/util/platform_util.h"
#include "exe_graph/runtime/tiling_context.h"
#include "exe_graph/runtime/tensor.h"
#include "../../op_kernel/arch35/apply_centered_rms_prop_tiling_data.h"

namespace optiling {

using Ops::Base::CeilDiv;
using Ops::Base::CeilAlign;
using Ops::Base::FloorDiv;
using Ops::Base::FloorAlign;
using Ops::Base::GetUbBlockSize;

constexpr uint32_t WS_SYS_SIZE = 0U;
constexpr size_t WORKSPACE_NUM = 1;

// Buffer counts in kernel:
//   Input queues (T):  var, mg, ms, mom, grad = 5
//   Output queues (T): var_out, mg_out, ms_out, mom_out = 4
//   FP32 queues:       varF32, mgF32, msF32, momF32, gradF32, tmp1, tmp2 = 7
constexpr int64_t T_QUEUE_COUNT = 9;   // 5 input + 4 output
constexpr int64_t FP32_QUEUE_COUNT = 7;

static const gert::Shape g_vec_1_shape = {1};

static inline const gert::Shape EnsureNotScalar(const gert::Shape& in_shape) {
    if (in_shape.GetDimNum() == 0) {
        return g_vec_1_shape;
    }
    return in_shape;
}

static ge::graphStatus GetPlatformInfo(gert::TilingContext* context, uint64_t* ubSize, int64_t* coreNum)
{
    fe::PlatFormInfos* platformInfoPtr = context->GetPlatformInfo();
    OP_CHECK_NULL_WITH_CONTEXT(context, platformInfoPtr);
    auto ascendcPlatform = platform_ascendc::PlatformAscendC(platformInfoPtr);
    *coreNum = ascendcPlatform.GetCoreNumAiv();
    OP_CHECK_IF(*coreNum == 0, OP_LOGE(context, "coreNum is 0"), return ge::GRAPH_FAILED);
    ascendcPlatform.GetCoreMemSize(platform_ascendc::CoreMemType::UB, *ubSize);
    OP_CHECK_IF(*ubSize == 0, OP_LOGE(context, "ubSize is 0"), return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus GetShapeAttrsInfo(gert::TilingContext* context, int64_t* totalIdx, ge::DataType* dataType)
{
    // Get var shape (input 0)
    auto inputVar = context->GetInputShape(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, inputVar);
    auto varShape = EnsureNotScalar(inputVar->GetStorageShape());

    // Verify all ND inputs have same shape
    for (int idx : {1, 2, 3, 8}) {  // mg=1, ms=2, mom=3, grad=8
        auto inputShape = context->GetInputShape(idx);
        OP_CHECK_NULL_WITH_CONTEXT(context, inputShape);
        auto shape = EnsureNotScalar(inputShape->GetStorageShape());
        OP_CHECK_IF(
            varShape.GetShapeSize() != shape.GetShapeSize(),
            OP_LOGE(context, "ApplyCenteredRMSProp: shape mismatch: var=%ld, input[%d]=%ld",
                    varShape.GetShapeSize(), idx, shape.GetShapeSize()),
            return ge::GRAPH_FAILED);
    }

    *totalIdx = varShape.GetShapeSize();

    // Dtype whitelist: only FP16/FP32/BF16 supported. Reject int16/int32/etc.
    // Check ALL 9 inputs (var,mg,ms,mom,lr,rho,momentum,epsilon,grad), not just
    // var: int dtype on mg/ms/grad slots otherwise silently miscomputes instead
    // of being rejected. Non-whitelisted dtype -> clean GRAPH_FAILED reject.
    const std::set<ge::DataType> supportedDtype = {ge::DT_FLOAT16, ge::DT_FLOAT, ge::DT_BF16};
    auto inputDesc = context->GetInputDesc(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, inputDesc);
    *dataType = inputDesc->GetDataType();
    for (int idx = 0; idx < 9; idx++) {
        auto desc = context->GetInputDesc(idx);
        OP_CHECK_NULL_WITH_CONTEXT(context, desc);
        ge::DataType dt = desc->GetDataType();
        OP_CHECK_IF(supportedDtype.count(dt) == 0,
                    OP_LOGE(context, "ApplyCenteredRMSProp: unsupported dtype %d at input[%d], only FP16/FP32/BF16 allowed",
                            static_cast<int>(dt), idx),
                    return ge::GRAPH_FAILED);
    }

    return ge::GRAPH_SUCCESS;
}

// ReadScalarInput - DISABLED for NPU Real mode.
//
// ROOT CAUSE: In the aclnn tiling context, tensor->GetAddr() returns a DEVICE
// address (NPU GM). Dereferencing it on the host causes a segfault.
// GetData<T>() also returns the same device address or nullptr.
//
// SOLUTION: Always return 0.0f with ok=false. The kernel will read scalar
// values from GM via GlobalTensor::GetValue() when scalarsValid == 0.
// This is the safe fallback path that works in both Mock and Real modes.
static float ReadScalarInput(gert::TilingContext* context, size_t flatIndex,
                             ge::DataType dataType, bool& ok)
{
    ok = false;
    // Do NOT attempt to read device memory from host side.
    // The kernel will read scalars from GM when scalarsValid == 0.
    return 0.0f;
}

static ge::graphStatus GetWorkspaceSize(gert::TilingContext* context)
{
    size_t* currentWorkspace = context->GetWorkspaceSizes(WORKSPACE_NUM);
    OP_CHECK_NULL_WITH_CONTEXT(context, currentWorkspace);
    currentWorkspace[0] = WS_SYS_SIZE;
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus ApplyCenteredRMSPropTilingFunc(gert::TilingContext* context)
{
    // 1. Get platform info
    uint64_t ubSize;
    int64_t coreNum;
    OP_CHECK_IF(
        GetPlatformInfo(context, &ubSize, &coreNum) != ge::GRAPH_SUCCESS,
        OP_LOGE(context, "GetPlatformInfo error"), return ge::GRAPH_FAILED);

    // 2. Get shape and dtype
    int64_t totalIdx;
    ge::DataType dataType;
    OP_CHECK_IF(
        GetShapeAttrsInfo(context, &totalIdx, &dataType) != ge::GRAPH_SUCCESS,
        OP_LOGE(context, "GetShapeAttrsInfo error"), return ge::GRAPH_FAILED);

    // 3. Workspace
    OP_CHECK_IF(
        GetWorkspaceSize(context) != ge::GRAPH_SUCCESS,
        OP_LOGE(context, "GetWorkspaceSize error"), return ge::GRAPH_FAILED);

    // 4. Set tiling data
    ApplyCenteredRMSPropTilingData* tiling = context->GetTilingData<ApplyCenteredRMSPropTilingData>();
    OP_CHECK_NULL_WITH_CONTEXT(context, tiling);
    OP_CHECK_IF(
        memset_s(tiling, sizeof(ApplyCenteredRMSPropTilingData), 0, sizeof(ApplyCenteredRMSPropTilingData)) != EOK,
        OP_LOGE(context, "set tiling data error"), return ge::GRAPH_FAILED);

    // 4b. Read scalar values from 0-D input tensors and store in TilingData.
    // Input indices: var=0, mg=1, ms=2, mom=3, lr=4, rho=5, momentum=6, epsilon=7, grad=8
    // Uses GetInputTensor() + GetData<T>() — canonical CANN pattern.
    // If reading fails (e.g. data not available in tiling context), kernel
    // falls back to reading from GM via GlobalTensor::GetValue().
    {
        bool lrOk = false, rhoOk = false, momOk = false, epsOk = false;
        tiling->lr       = ReadScalarInput(context, 4U, dataType, lrOk);
        tiling->rho      = ReadScalarInput(context, 5U, dataType, rhoOk);
        tiling->momentum = ReadScalarInput(context, 6U, dataType, momOk);
        tiling->epsilon  = ReadScalarInput(context, 7U, dataType, epsOk);
        tiling->scalarsValid = (lrOk && rhoOk && momOk && epsOk) ? 1 : 0;
    }

    // Empty tensor: return early
    if (totalIdx == 0) {
        context->SetBlockDim(1);
        return ge::GRAPH_SUCCESS;
    }

    // 5. Calculate UB tile size
    int64_t ubBlockSize = Ops::Base::GetUbBlockSize(context);
    int64_t typeSize = (dataType == ge::DT_FLOAT) ? 4 : 2;

    // Total bytes per element = T_QUEUE_COUNT * typeSize + FP32_QUEUE_COUNT * 4
    int64_t bytesPerElem = T_QUEUE_COUNT * typeSize + FP32_QUEUE_COUNT * 4;
    int64_t tileElements = FloorAlign(FloorDiv(static_cast<int64_t>(ubSize), bytesPerElem), ubBlockSize);

    // Ensure tileElements >= 1
    if (tileElements < 1) {
        tileElements = 1;
    }

    // 6. Multi-core split
    tiling->totalNum = totalIdx;
    tiling->blockFactor = CeilAlign(CeilDiv(totalIdx, coreNum), ubBlockSize);
    tiling->ubFactor = tileElements;

    int64_t usedCoreNum = CeilDiv(totalIdx, tiling->blockFactor);
    context->SetBlockDim(usedCoreNum);

    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus TilingParseForApplyCenteredRMSProp([[maybe_unused]] gert::TilingParseContext* context)
{
    return ge::GRAPH_SUCCESS;
}

struct ApplyCenteredRMSPropCompileInfo {};

IMPL_OP_OPTILING(ApplyCenteredRMSProp)
    .Tiling(ApplyCenteredRMSPropTilingFunc)
    .TilingParse<ApplyCenteredRMSPropCompileInfo>(TilingParseForApplyCenteredRMSProp);

} // namespace optiling
