/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/**
 * NOTE: Portions of this code were AI-generated and have been
 * technically reviewed for functional accuracy and security
 * Generated By CANNBot
 */

/*!
 * \file apply_adagrad_v2d.cpp
 * \brief ApplyAdagradV2d 算子 Kernel 入口（arch35 / DAV_3510 架构）
 *
 * 对齐 CANNDEV ApplyAdagradV2D：2 输出（var, accum），仅支持 FLOAT。
 * lr 为标量 Tensor 输入，kernel 从 GM_ADDR 运行时读取，不存入 TilingData。
 * epsilon 为 REQUIRED_ATTR(Float)，存入 TilingData。
 *
 * 模板参数：
 *   - UPDATE_SLOTS: 是否更新 accum（bool），编码到 TilingKey
 *
 * 构建系统根据 tiling_key.h 和 def.cpp 自动生成 2 个模板实例
 * （2 updateSlots = 2 个 Kernel 二进制）。
 */

#include "apply_adagrad_v2d.h"

// 提取参数列表为宏，避免双入口签名重复
#define APPLY_ADAGRAD_V2D_PARAMS                                                  \
    GM_ADDR var, GM_ADDR accum, GM_ADDR lr, GM_ADDR grad,                        \
    GM_ADDR var_out, GM_ADDR accum_out, GM_ADDR workspace, GM_ADDR tiling

// NPU 入口：template + UPDATE_SLOTS 模板参数，由 ASCENDC_TPL 机制实例化多 binary。
template <bool UPDATE_SLOTS>
__global__ __aicore__ void apply_adagrad_v2d(APPLY_ADAGRAD_V2D_PARAMS)
{
    REGISTER_TILING_DEFAULT(ApplyAdagradV2dTilingData);
    GET_TILING_DATA_WITH_STRUCT(ApplyAdagradV2dTilingData, tilingData, tiling);
    NsApplyAdagradV2d::ApplyAdagradV2dKernel<float, UPDATE_SLOTS> op;
    op.Init(var, accum, lr, grad, var_out, accum_out, &tilingData);
    op.Process();
}

#undef APPLY_ADAGRAD_V2D_PARAMS
