/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/**
 * NOTE: Portions of this code were AI-generated and have been
 * technically reviewed for functional accuracy and security
 * Generated By CANNBot
 */

/*!
 * \file apply_adagrad_v2d_tiling_key.h
 * \brief TilingKey 模板参数定义（ASCENDC_TPL_ARGS_DECL 方式）
 *
 * lr 为标量 Tensor 输入，kernel 从 GM_ADDR 运行时读取，
 * 无需 TilingKey 编码 lr 值。
 *
 * 模板参数：
 *   - UPDATE_SLOTS: 是否更新 accum（bool, 0=false / 1=true）
 *
 * 仅支持 FLOAT（对齐 CANNDEV ApplyAdagradV2D），无需 DTYPE 维度。
 * TilingKey 编码：1 updateSlots × 1 = 2 个 Kernel 二进制
 *
 * 禁止使用 TILING_KEY_IS 宏。
 */

#ifndef __APPLY_ADAGRAD_V2D_TILING_KEY_H__
#define __APPLY_ADAGRAD_V2D_TILING_KEY_H__

#include "ascendc/host_api/tiling/template_argument.h"

ASCENDC_TPL_ARGS_DECL(ApplyAdagradV2d,
    ASCENDC_TPL_BOOL_DECL(UPDATE_SLOTS, 0, 1)
);

// 2 个 TilingKey 组合（updateSlots true/false）
ASCENDC_TPL_SEL(
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_BOOL_SEL(UPDATE_SLOTS, 1)
    ),
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_BOOL_SEL(UPDATE_SLOTS, 0)
    ),
);

#endif // __APPLY_ADAGRAD_V2D_TILING_KEY_H__
