/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file softplus_grad_tiling.h
 * \brief softplus_grad_tiling 头文件声明
 *
 * softplus_grad 使用 BroadcastBaseTiling 框架，Tiling 入口通过
 * IMPL_OP_OPTILING 注册，无需定义 TilingBaseClass 子类。
 */
#ifndef OPS_BUILD_IN_OP_TILING_RUNTIME_SOFTPLUS_GRAD_TILING_H_
#define OPS_BUILD_IN_OP_TILING_RUNTIME_SOFTPLUS_GRAD_TILING_H_

#include "atvoss/broadcast/broadcast_tiling.h"

#endif  // OPS_BUILD_IN_OP_TILING_RUNTIME_SOFTPLUS_GRAD_TILING_H_
