/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file sparse_apply_rms_prop_graph_infer.cpp
 * \brief sparse_apply_rms_prop operater graph infer resource
 */

#include "register/op_impl_registry.h"
#include "op_common/log/log.h"

namespace ops {
using namespace ge;

static constexpr int64_t IDX_0 = 0;
static constexpr int64_t IDX_1 = 1;
static constexpr int64_t IDX_2 = 2;

static ge::graphStatus InferDataTypeSparseApplyRMSProp(gert::InferDataTypeContext* context)
{
    OP_LOGD(context->GetNodeName(), "Begin to do InferDataTypeSparseApplyRMSProp");

    // 输出 var 的 dtype 与输入 var 相同
    ge::DataType varDtype = context->GetInputDataType(IDX_0);
    context->SetOutputDataType(IDX_0, varDtype);

    // 输出 ms 的 dtype 与输入 ms 相同
    ge::DataType msDtype = context->GetInputDataType(IDX_1);
    context->SetOutputDataType(IDX_1, msDtype);

    // 输出 mom 的 dtype 与输入 mom 相同
    ge::DataType momDtype = context->GetInputDataType(IDX_2);
    context->SetOutputDataType(IDX_2, momDtype);

    OP_LOGD(context->GetNodeName(), "End to do InferDataTypeSparseApplyRMSProp");
    return GRAPH_SUCCESS;
}

IMPL_OP(SparseApplyRMSProp).InferDataType(InferDataTypeSparseApplyRMSProp);

}; // namespace ops
