/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file foreach_pow_scalar.cpp
 * \brief kernel entry for foreach_pow_scalar
 */

#include "foreach_pow_scalar_simt.h"

enum class ForeachPowScalarTilingKey : uint32_t {
    TILING_KEY_FLOAT = 0,
    TILING_KEY_FLOAT16 = 1,
    TILING_KEY_INT32 = 2,
    TILING_KEY_BF16 = 3,
};

template <uint32_t schMode>
__global__ __aicore__ void foreach_pow_scalar(GM_ADDR x, GM_ADDR scalar, GM_ADDR y, GM_ADDR workspace, GM_ADDR tiling)
{
    REGISTER_TILING_DEFAULT(ForeachPowScalarTilingData);
    GET_TILING_DATA_WITH_STRUCT(ForeachPowScalarTilingData, tilingData, tiling);

    // Access tiling data via GM pointer to avoid stack overflow with large struct
    const __gm__ ForeachPowScalarTilingData* tilingGm = reinterpret_cast<const __gm__ ForeachPowScalarTilingData*>(
        tiling);

    if constexpr (schMode == static_cast<uint32_t>(ForeachPowScalarTilingKey::TILING_KEY_FLOAT)) {
        NsForeachPowScalar::Process<float, float>(x, scalar, y, tilingGm);
    } else if constexpr (schMode == static_cast<uint32_t>(ForeachPowScalarTilingKey::TILING_KEY_FLOAT16)) {
        NsForeachPowScalar::Process<half, half>(x, scalar, y, tilingGm);
    } else if constexpr (schMode == static_cast<uint32_t>(ForeachPowScalarTilingKey::TILING_KEY_INT32)) {
        NsForeachPowScalar::Process<int32_t, int32_t>(x, scalar, y, tilingGm);
    } else if constexpr (schMode == static_cast<uint32_t>(ForeachPowScalarTilingKey::TILING_KEY_BF16)) {
        NsForeachPowScalar::Process<bfloat16_t, float>(x, scalar, y, tilingGm);
    }
}