/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file sparse_apply_proximal_adagrad_graph_infer.cpp
 * \brief sparse_apply_proximal_adagrad operator graph infer resource
 */

#include "register/op_impl_registry.h"
#include "op_common/log/log.h"

namespace ops {
using namespace ge;

static constexpr int64_t IDX_VAR = 0;
static constexpr int64_t IDX_ACCUM = 1;

static ge::graphStatus InferDataTypeSparseApplyProximalAdagrad(gert::InferDataTypeContext* context)
{
    OP_LOGD(context->GetNodeName(), "Begin to do InferDataTypeSparseApplyProximalAdagrad");

    // 输出的var dtype = 输入的var dtype
    ge::DataType varDtype = context->GetInputDataType(IDX_VAR);
    context->SetOutputDataType(IDX_VAR, varDtype);

    // 输出的accum dtype = 输入的accum dtype
    ge::DataType accumDtype = context->GetInputDataType(IDX_ACCUM);
    context->SetOutputDataType(IDX_ACCUM, accumDtype);

    OP_LOGD(context->GetNodeName(), "End to do InferDataTypeSparseApplyProximalAdagrad");
    return GRAPH_SUCCESS;
}

IMPL_OP(SparseApplyProximalAdagrad).InferDataType(InferDataTypeSparseApplyProximalAdagrad);

}; // namespace ops
