/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot - Iter2 Fix */

/*!
 * \file selu_grad_arch35.cpp
 * \brief SeluGrad 算子 Kernel 入口（arch35 架构）
 *
 * 6 dtype × 2 SCH_MODE = 12 TilingKey
 *
 * 分发策略：
 *   - float                                  → Direct  直算路径（T 原地计算）
 *   - half/bfloat16/int32/int8/uint8         → Transit FP32 中转路径
 *   SCH_MODE=0 (OneDim) 与 SCH_MODE=1 (Broadcast) 分别选用对应的 OneDim/Broadcast 类。
 */

#include "arch35/selu_grad.h"

template <typename Op>
__aicore__ inline void RunSeluGrad(GM_ADDR gradients, GM_ADDR outputs, GM_ADDR y,
                                   const SeluGradTilingData* tilingData)
{
    Op op;
    op.Init(gradients, outputs, y, tilingData);
    op.Process();
}

template <typename D_T_X, int SCH_MODE>
__global__ __aicore__ void selu_grad(GM_ADDR gradients, GM_ADDR outputs, GM_ADDR y,
                                      GM_ADDR workspace, GM_ADDR tiling)
{
    REGISTER_TILING_DEFAULT(SeluGradTilingData);
    GET_TILING_DATA_WITH_STRUCT(SeluGradTilingData, tilingData, tiling);

    if constexpr (SCH_MODE == SELU_GRAD_ONE_DIM) {
        RunSeluGrad<NsSeluGrad::SeluGradOneDimOp<D_T_X>>(gradients, outputs, y, &tilingData);
    } else if constexpr (SCH_MODE == SELU_GRAD_BROADCAST) {
        RunSeluGrad<NsSeluGrad::SeluGradBroadcastOp<D_T_X>>(gradients, outputs, y, &tilingData);
    }
}
