/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file foreach_maximum_scalar_list.cpp
 * \brief kernel entry for foreach_maximum_scalar_list
 */

#include "foreach_maximum_scalar_list_simt.h"

enum class ForeachMaximumScalarListTilingKey : uint32_t {
    TILING_KEY_FLOAT = 0,
    TILING_KEY_FLOAT16 = 1,
    TILING_KEY_INT32 = 2,
    TILING_KEY_BF16 = 3,
};

template <uint32_t schMode>
__global__ __aicore__ void foreach_maximum_scalar_list(GM_ADDR x, GM_ADDR scalars, GM_ADDR y, GM_ADDR workspace,
                                                       GM_ADDR tiling)
{
    REGISTER_TILING_DEFAULT(ForeachMaximumScalarListTilingData);
    GET_TILING_DATA_WITH_STRUCT(ForeachMaximumScalarListTilingData, tilingData, tiling);

    const __gm__ ForeachMaximumScalarListTilingData*
        tilingGm = reinterpret_cast<const __gm__ ForeachMaximumScalarListTilingData*>(tiling);

    if constexpr (schMode == static_cast<uint32_t>(ForeachMaximumScalarListTilingKey::TILING_KEY_FLOAT)) {
        NsForeachMaximumScalarList::Process<float, float>(x, scalars, y, tilingGm);
    } else if constexpr (schMode == static_cast<uint32_t>(ForeachMaximumScalarListTilingKey::TILING_KEY_FLOAT16)) {
        NsForeachMaximumScalarList::Process<half, float>(x, scalars, y, tilingGm);
    } else if constexpr (schMode == static_cast<uint32_t>(ForeachMaximumScalarListTilingKey::TILING_KEY_INT32)) {
        NsForeachMaximumScalarList::Process<int32_t, int64_t>(x, scalars, y, tilingGm);
    } else if constexpr (schMode == static_cast<uint32_t>(ForeachMaximumScalarListTilingKey::TILING_KEY_BF16)) {
        NsForeachMaximumScalarList::Process<bfloat16_t, float>(x, scalars, y, tilingGm);
    }
}
