#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (c) 2026 Huawei Technologies Co., Ltd.
# This program is free software, you can redistribute it and/or modify it under the terms and conditions of
# CANN Open Software License Agreement Version 2.0 (the "License").
# Please refer to the License for details. You may not use this file except in compliance with the License.
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
# See LICENSE in the root of the software repository for the full text of the License.

# Generated By CANNBot
#
# SoftplusV2Grad golden data generator.
#   gradInput = gradOut * ( 1/(1+exp(-beta*self))  if beta*self <= threshold
#                           else 1 )
# Broadcasting of gradOut / features to out shape is supported (numpy semantics).
#
# Usage:
#   python3 gen_data.py <tag> <grad_shape> <feat_shape> <out_shape> <dtype> <beta> <threshold>
# Example:
#   python3 gen_data.py case1 '(4,64)' '(4,64)' '(4,64)' float32 1.0 20.0
#
# Files written (in cwd):
#   <tag>_grad.bin, <tag>_features.bin, <tag>_golden.bin

import sys
import numpy as np


def parse_shape(shape_str):
    s = shape_str.strip().strip("'").strip('"').strip("(").strip(")")
    parts = [p for p in s.replace(" ", "").split(",") if p != ""]
    return tuple(int(x) for x in parts)


def fp32_to_bf16_u16(arr_fp32):
    # Truncate fp32 to bf16 by taking the high 16 bits (little-endian: bytes 2..4).
    arr_fp32 = np.ascontiguousarray(arr_fp32.astype(np.float32))
    u32 = arr_fp32.view(np.uint32)
    return (u32 >> 16).astype(np.uint16)


def bf16_u16_to_fp32(arr_u16):
    u32 = arr_u16.astype(np.uint32) << 16
    return u32.view(np.float32)


def softplus_v2_grad_golden(grad_f32, feat_f32, beta, threshold):
    bx = beta * feat_f32
    sig = 1.0 / (1.0 + np.exp(-bx))
    # where beta*self <= threshold use sigmoid, else pass gradient through (factor 1).
    factor = np.where(bx <= threshold, sig, np.ones_like(sig))
    return grad_f32 * factor


def gen(tag, grad_shape, feat_shape, out_shape, dtype, beta, threshold):
    np.random.seed(1234 + (abs(hash(tag)) % 100000))

    # features spread wide enough (with beta) to straddle the threshold on both sides.
    feat_fp32 = np.random.uniform(-6.0, 6.0, feat_shape).astype(np.float32)
    grad_fp32 = np.random.uniform(-2.0, 2.0, grad_shape).astype(np.float32)

    if dtype == "bfloat16":
        # Round inputs to bf16 first, then compute golden on the rounded values.
        feat_u16 = fp32_to_bf16_u16(feat_fp32)
        grad_u16 = fp32_to_bf16_u16(grad_fp32)
        feat_r = bf16_u16_to_fp32(feat_u16)
        grad_r = bf16_u16_to_fp32(grad_u16)
        golden = softplus_v2_grad_golden(grad_r, feat_r, beta, threshold)
        golden_b = np.broadcast_to(golden, out_shape)
        grad_u16.reshape(grad_shape).tofile(f"./{tag}_grad.bin")
        feat_u16.reshape(feat_shape).tofile(f"./{tag}_features.bin")
        fp32_to_bf16_u16(golden_b).reshape(out_shape).tofile(f"./{tag}_golden.bin")
        return

    np_dtype = {"float32": np.float32, "float16": np.float16}[dtype]
    feat_c = feat_fp32.astype(np_dtype)
    grad_c = grad_fp32.astype(np_dtype)
    golden = softplus_v2_grad_golden(
        grad_c.astype(np.float32), feat_c.astype(np.float32), beta, threshold
    ).astype(np_dtype)
    golden_b = np.broadcast_to(golden, out_shape)
    grad_c.tofile(f"./{tag}_grad.bin")
    feat_c.tofile(f"./{tag}_features.bin")
    np.ascontiguousarray(golden_b).tofile(f"./{tag}_golden.bin")


if __name__ == "__main__":
    if len(sys.argv) != 8:
        print(
            "Usage: python3 gen_data.py <tag> <grad_shape> <feat_shape> "
            "<out_shape> <dtype> <beta> <threshold>"
        )
        sys.exit(1)
    tag = sys.argv[1]
    gs = parse_shape(sys.argv[2])
    fs = parse_shape(sys.argv[3])
    os_ = parse_shape(sys.argv[4])
    dt = sys.argv[5]
    be = float(sys.argv[6])
    th = float(sys.argv[7])
    gen(tag, gs, fs, os_, dt, be, th)
