/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/*!
 * \file fused_bias_leaky_relu_grad_struct.h
 * \brief TilingKey template parameter definition for FusedBiasLeakyReluGrad
 *
 * TilingKey is RANK-only (dtype-independent).
 * RANK_4: rank <= 4 (common case, arrays dimensioned [4])
 * RANK_8: rank > 4  (fallback, arrays dimensioned [8])
 *
 * Generated By CANNBot
 */

#ifndef FUSED_BIAS_LEAKY_RELU_GRAD_STRUCT_H_
#define FUSED_BIAS_LEAKY_RELU_GRAD_STRUCT_H_

#include "ascendc/host_api/tiling/template_argument.h"

#define FUSED_BIAS_LEAKY_RELU_GRAD_RANK_4 4
#define FUSED_BIAS_LEAKY_RELU_GRAD_RANK_8 8

ASCENDC_TPL_ARGS_DECL(FusedBiasLeakyReluGrad,
    ASCENDC_TPL_UINT_DECL(RANK, 8, ASCENDC_TPL_UI_LIST,
        FUSED_BIAS_LEAKY_RELU_GRAD_RANK_4, FUSED_BIAS_LEAKY_RELU_GRAD_RANK_8)
);

ASCENDC_TPL_SEL(
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_UINT_SEL(RANK, ASCENDC_TPL_UI_LIST, FUSED_BIAS_LEAKY_RELU_GRAD_RANK_4)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_UINT_SEL(RANK, ASCENDC_TPL_UI_LIST, FUSED_BIAS_LEAKY_RELU_GRAD_RANK_8))
);

#endif // FUSED_BIAS_LEAKY_RELU_GRAD_STRUCT_H_
