/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/*!
 * \file fused_bias_leaky_relu_grad.cpp
 * \brief Kernel entry for FusedBiasLeakyReluGrad (Broadcast, RegBase, arch35)
 * Generated By CANNBot
 */

#include "kernel_operator.h"
#include "fused_bias_leaky_relu_grad_kernel.h"
#include "fused_bias_leaky_relu_grad_tiling_struct.h"

using TilingData4 = FusedBiasLeakyReluGradTilingData<4>;
using TilingData8 = FusedBiasLeakyReluGradTilingData<8>;

template<int RANK>
__global__ __aicore__ void fused_bias_leaky_relu_grad(
    GM_ADDR y_grad,
    GM_ADDR features,
    GM_ADDR x_grad,
    GM_ADDR workspace, GM_ADDR tiling)
{
    GM_ADDR ins[2]  = {y_grad, features};
    GM_ADDR outs[1] = {x_grad};

    REGISTER_NONE_TILING;
    KERNEL_TASK_TYPE_DEFAULT(KERNEL_TYPE_AIV_ONLY);

    if constexpr (RANK == 4) {
        GET_TILING_DATA_WITH_STRUCT(TilingData4, td, tiling);
        FusedBiasLeakyReluGradKernel<DTYPE_Y_GRAD, 4> kernel;
        kernel.Init(ins, outs, &td);
        kernel.Process();
    } else {
        GET_TILING_DATA_WITH_STRUCT(TilingData8, td, tiling);
        FusedBiasLeakyReluGradKernel<DTYPE_Y_GRAD, 8> kernel;
        kernel.Init(ins, outs, &td);
        kernel.Process();
    }
}
