/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

#include "register/op_def_registry.h"
#include "foreach_tiling_class.h"

namespace optiling {

static ge::graphStatus TilingPrepare4ForeachTiling([[maybe_unused]] gert::TilingParseContext* context)
{
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus Tiling4ForeachLog2Tiling(gert::TilingContext* context)
{
    ForeachCommonTiling tilingObject(context);
    if (tilingObject.Init(SOLO_LOG2_OP_CODE) != ge::GRAPH_SUCCESS) {
        return ge::GRAPH_FAILED;
    }
    return tilingObject.RunBigKernelTiling();
}

IMPL_OP_OPTILING(ForeachLog2)
    .Tiling(Tiling4ForeachLog2Tiling)
    .TilingParse<ForeachCompileInfo>(TilingPrepare4ForeachTiling);

} // namespace optiling
