/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/**
 * NOTE: Portions of this code were AI-generated and have been
 * technically reviewed for functional accuracy and security
 *
 * Generated By CANNBot
 */

/*!
 * \file softshrink_tiling_key.h
 * \brief Softshrink TilingKey 模板参数定义
 *
 * TilingKey 映射（单 schMode 模式，对齐 hard_shrink 样板）：
 *   SOFTSHRINK_TPL_SCH_MODE_FP32 (0) : float32 计算路径
 *   SOFTSHRINK_TPL_SCH_MODE_FP16 (1) : float16 计算路径
 *   SOFTSHRINK_TPL_SCH_MODE_BF16 (2) : bfloat16 计算路径（cast 到 fp32 计算）
 */

#ifndef __SOFTSHRINK_TILING_KEY_H__
#define __SOFTSHRINK_TILING_KEY_H__

#include "ascendc/host_api/tiling/template_argument.h"

#define SOFTSHRINK_TPL_SCH_MODE_FP32 0
#define SOFTSHRINK_TPL_SCH_MODE_FP16 1
#define SOFTSHRINK_TPL_SCH_MODE_BF16 2

ASCENDC_TPL_ARGS_DECL(
    Softshrink,
    ASCENDC_TPL_UINT_DECL(schMode, 2, ASCENDC_TPL_UI_LIST,
                          SOFTSHRINK_TPL_SCH_MODE_FP32,
                          SOFTSHRINK_TPL_SCH_MODE_FP16,
                          SOFTSHRINK_TPL_SCH_MODE_BF16));

ASCENDC_TPL_SEL(ASCENDC_TPL_ARGS_SEL(
    ASCENDC_TPL_UINT_SEL(schMode, ASCENDC_TPL_UI_LIST,
                         SOFTSHRINK_TPL_SCH_MODE_FP32,
                         SOFTSHRINK_TPL_SCH_MODE_FP16,
                         SOFTSHRINK_TPL_SCH_MODE_BF16)));

#endif // __SOFTSHRINK_TILING_KEY_H__
