/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/*!
 * \file fused_bias_leaky_relu_grad_tiling_arch35.cpp
 * \brief Tiling implementation for FusedBiasLeakyReluGrad (Broadcast, RegBase)
 * Generated By CANNBot
 */

#include "register/op_def_registry.h"
#include "register/op_impl_registry.h"
#include "register/tilingdata_base.h"
#include "op_common/log/log.h"
#include "op_common/op_host/util/math_util.h"
#include "op_common/op_host/util/platform_util.h"
#include "../../op_kernel/arch35/fused_bias_leaky_relu_grad_tiling_struct.h"
#include "../../op_kernel/arch35/fused_bias_leaky_relu_grad_struct.h"

namespace optiling {

using Ops::Base::CeilDiv;

constexpr int64_t kAlignBytes = 32;
constexpr float kDefaultNegativeSlope = 0.2f;
constexpr float kDefaultScale = 1.414213562373f;

// ===========================================================================
// PadShapesToMaxRank: left-pad every input/output shape with 1s to the max rank
// ===========================================================================
static void PadShapesToMaxRank(const std::vector<std::vector<int64_t>>& input_shapes,
                               const std::vector<std::vector<int64_t>>& output_shapes,
                               std::vector<std::vector<int64_t>>& padded_in,
                               std::vector<std::vector<int64_t>>& padded_out)
{
    int64_t max_rank = 0;
    for (auto& s : input_shapes)
        max_rank = std::max(max_rank, static_cast<int64_t>(s.size()));
    for (auto& s : output_shapes)
        max_rank = std::max(max_rank, static_cast<int64_t>(s.size()));

    auto pad = [&](const std::vector<int64_t>& s) {
        std::vector<int64_t> p;
        p.assign(max_rank - static_cast<int64_t>(s.size()), 1);
        p.insert(p.end(), s.begin(), s.end());
        return p;
    };

    padded_in.assign(input_shapes.size(), std::vector<int64_t>());
    padded_out.assign(output_shapes.size(), std::vector<int64_t>());
    for (size_t i = 0; i < input_shapes.size(); i++)
        padded_in[i] = pad(input_shapes[i]);
    for (size_t i = 0; i < output_shapes.size(); i++)
        padded_out[i] = pad(output_shapes[i]);
}

// ===========================================================================
// SqueezeAllOneDims: drop axes that are 1 across all tensors; keep broadcast max
// ===========================================================================
static void SqueezeAllOneDims(const std::vector<std::vector<int64_t>>& padded_in,
                              const std::vector<std::vector<int64_t>>& padded_out,
                              std::vector<int64_t>& maximum_bro_shape,
                              std::vector<std::vector<int64_t>>& normal_input_shapes,
                              std::vector<std::vector<int64_t>>& normal_output_shapes)
{
    int64_t num_inputs = static_cast<int64_t>(padded_in.size());
    int64_t num_outputs = static_cast<int64_t>(padded_out.size());
    int64_t max_rank = num_inputs > 0 ? static_cast<int64_t>(padded_in[0].size()) :
                                        (num_outputs > 0 ? static_cast<int64_t>(padded_out[0].size()) : 0);

    maximum_bro_shape.clear();
    normal_input_shapes.assign(num_inputs, std::vector<int64_t>());
    normal_output_shapes.assign(num_outputs, std::vector<int64_t>());

    for (int64_t d = 0; d < max_rank; d++) {
        bool all_one = true;
        int64_t max_dim = 0;
        for (int64_t i = 0; i < num_inputs; i++) {
            if (padded_in[i][d] != 1)
                all_one = false;
            max_dim = std::max(max_dim, padded_in[i][d]);
        }
        for (int64_t i = 0; i < num_outputs; i++) {
            if (padded_out[i][d] != 1)
                all_one = false;
            max_dim = std::max(max_dim, padded_out[i][d]);
        }
        if (!all_one) {
            maximum_bro_shape.push_back(max_dim);
            for (int64_t i = 0; i < num_inputs; i++)
                normal_input_shapes[i].push_back(padded_in[i][d]);
            for (int64_t i = 0; i < num_outputs; i++)
                normal_output_shapes[i].push_back(padded_out[i][d]);
        }
    }
    if (maximum_bro_shape.empty()) {
        maximum_bro_shape.push_back(1);
        for (int64_t i = 0; i < num_inputs; i++)
            normal_input_shapes[i].push_back(1);
        for (int64_t i = 0; i < num_outputs; i++)
            normal_output_shapes[i].push_back(1);
    }
}

// ===========================================================================
// PadAndSqueeze: pad shapes to max rank, squeeze all-1 dims
// ===========================================================================
static bool PadAndSqueeze(const std::vector<std::vector<int64_t>>& input_shapes,
                          const std::vector<std::vector<int64_t>>& output_shapes,
                          std::vector<int64_t>& maximum_bro_shape,
                          std::vector<std::vector<int64_t>>& normal_input_shapes,
                          std::vector<std::vector<int64_t>>& normal_output_shapes)
{
    std::vector<std::vector<int64_t>> padded_in, padded_out;
    PadShapesToMaxRank(input_shapes, output_shapes, padded_in, padded_out);
    SqueezeAllOneDims(padded_in, padded_out, maximum_bro_shape, normal_input_shapes, normal_output_shapes);
    return true;
}

// ===========================================================================
// FindSplitAxis: determine UB split axis and tile sizes
// ===========================================================================
static bool FindSplitAxis(const std::vector<int64_t>& max_bro_shape, int64_t ub_per_core, int64_t phys_nodes,
                          SplitResult& out)
{
    if (phys_nodes == 0)
        return false;
    int64_t per_buf_bytes = (ub_per_core / phys_nodes) & ~(kAlignBytes - 1);
    int64_t per_buf_elems = per_buf_bytes / static_cast<int64_t>(sizeof(float));
    int64_t rank = static_cast<int64_t>(max_bro_shape.size());
    int64_t inner = 1;
    for (int64_t k = rank - 1; k >= 0; k--) {
        if (max_bro_shape[k] * inner > per_buf_elems) {
            out.a_i = per_buf_elems / inner;
            out.a_o = (max_bro_shape[k] + out.a_i - 1) / out.a_i;
            int64_t rem = max_bro_shape[k] % out.a_i;
            out.a_i_tail = (rem == 0) ? out.a_i : rem;
            out.axis = k;
            return true;
        }
        if (k == 0) {
            out.axis = 0;
            out.a_i = max_bro_shape[0];
            out.a_o = 1;
            out.a_i_tail = max_bro_shape[0];
            return true;
        }
        inner *= max_bro_shape[k];
    }
    return true;
}

// ===========================================================================
// MultiCoreSplit: distribute tiles across cores
// ===========================================================================
static void MultiCoreSplit(int64_t total_tiles, int64_t num_cores, MultiCoreResult& out)
{
    out.total_tiles = total_tiles;
    if (total_tiles == 0 || num_cores <= 0) {
        // 空任务防御：避免 0/0 除零 (SEC-2.3)，单核不参与计算
        out.num_cores = 1;
        out.tiles_main = 0;
        out.cores_tail = 0;
        return;
    }
    out.num_cores = (total_tiles < num_cores) ? total_tiles : num_cores;
    out.tiles_main = total_tiles / out.num_cores;
    out.cores_tail = total_tiles % out.num_cores;
}

// ===========================================================================
// ComputeStrides: compute GM strides for a shape (broadcast axes get stride 0)
// ===========================================================================
static void ComputeStrides(const std::vector<int64_t>& shape, const std::vector<int64_t>& max_bro_shape, int64_t rank,
                           int64_t* strides)
{
    int64_t stride = 1;
    for (int64_t d = rank - 1; d >= 0; d--) {
        if (shape[d] == 1 && max_bro_shape[d] > 1) {
            strides[d] = 0; // broadcast axis
        } else {
            strides[d] = stride;
        }
        stride *= shape[d];
    }
}

// ===========================================================================
// FillIOStrides: fill input/output shapes and strides into TilingData
// ===========================================================================
template <int64_t kRank>
static void FillIOStrides(FusedBiasLeakyReluGradTilingData<kRank>* td, const std::vector<int64_t>& maximum_bro_shape,
                          const std::vector<std::vector<int64_t>>& normal_input_shapes,
                          const std::vector<std::vector<int64_t>>& normal_output_shapes, int64_t rank)
{
    for (int64_t inp = 0; inp < kMaxInputSlots; inp++) {
        int64_t inp_strides[kRank] = {};
        ComputeStrides(normal_input_shapes[inp], maximum_bro_shape, rank, inp_strides);
        for (int64_t d = 0; d < kRank; d++) {
            if (d < rank) {
                td->input_shapes[inp][d] = normal_input_shapes[inp][d];
                td->input_strides[inp][d] = inp_strides[d];
            } else {
                td->input_shapes[inp][d] = 1;
                td->input_strides[inp][d] = 0;
            }
        }
    }

    for (int64_t out = 0; out < kMaxOutputSlots; out++) {
        int64_t out_strides[kRank] = {};
        ComputeStrides(normal_output_shapes[out], maximum_bro_shape, rank, out_strides);
        for (int64_t d = 0; d < kRank; d++) {
            if (d < rank) {
                td->output_shapes[out][d] = normal_output_shapes[out][d];
                td->output_strides[out][d] = out_strides[d];
            } else {
                td->output_shapes[out][d] = 1;
                td->output_strides[out][d] = 0;
            }
        }
    }
}

// ===========================================================================
// Tiling main function
// ===========================================================================
template <int64_t kRank>
static ge::graphStatus DoTiling(gert::TilingContext* context, const std::vector<int64_t>& maximum_bro_shape,
                                const std::vector<std::vector<int64_t>>& normal_input_shapes,
                                const std::vector<std::vector<int64_t>>& normal_output_shapes, int64_t rank,
                                uint64_t ubSize, int64_t coreNum, float negativeSlope, float scale)
{
    SplitResult split;
    FindSplitAxis(maximum_bro_shape, static_cast<int64_t>(ubSize), kPhysNodes, split);

    int64_t outer_count = 1;
    for (int64_t d = 0; d < split.axis; d++) {
        outer_count *= maximum_bro_shape[d];
    }
    int64_t total_tiles = outer_count * split.a_o;

    MultiCoreResult multicore;
    MultiCoreSplit(total_tiles, coreNum, multicore);

    int64_t per_buf_bytes = (static_cast<int64_t>(ubSize) / kPhysNodes) & ~(kAlignBytes - 1);

    auto* td = context->GetTilingData<FusedBiasLeakyReluGradTilingData<kRank>>();
    if (td == nullptr) {
        OP_LOGE(context, "GetTilingData failed");
        return ge::GRAPH_FAILED;
    }
    if (memset_s(td, sizeof(FusedBiasLeakyReluGradTilingData<kRank>), 0,
                 sizeof(FusedBiasLeakyReluGradTilingData<kRank>)) != EOK) {
        OP_LOGE(context, "memset tiling data failed");
        return ge::GRAPH_FAILED;
    }

    td->split = split;
    td->multicore = multicore;
    td->rank = rank;
    td->per_buf_bytes = per_buf_bytes;
    td->num_inputs = kMaxInputSlots;
    td->num_outputs = kMaxOutputSlots;
    td->negative_slope = negativeSlope;
    td->scale = scale;

    for (int64_t d = 0; d < kRank; d++) {
        td->max_bro_shape[d] = (d < rank) ? maximum_bro_shape[d] : 1;
    }

    FillIOStrides<kRank>(td, maximum_bro_shape, normal_input_shapes, normal_output_shapes, rank);

    context->SetBlockDim(static_cast<uint32_t>(multicore.num_cores));
    size_t* ws = context->GetWorkspaceSizes(1);
    if (ws != nullptr) {
        ws[0] = 0;
    }

    return ge::GRAPH_SUCCESS;
}

// ===========================================================================
// ReadContextShapes: extract and convert shapes from TilingContext
// ===========================================================================
static ge::graphStatus ReadContextShapes(gert::TilingContext* context, std::vector<std::vector<int64_t>>& input_shapes,
                                         std::vector<std::vector<int64_t>>& output_shapes, ge::DataType& dtype)
{
    auto inShape0 = context->GetInputShape(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, inShape0);
    auto inShape1 = context->GetInputShape(1);
    OP_CHECK_NULL_WITH_CONTEXT(context, inShape1);
    auto outShape0 = context->GetOutputShape(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, outShape0);

    auto inputDesc = context->GetInputDesc(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, inputDesc);
    dtype = inputDesc->GetDataType();
    if (dtype != ge::DT_FLOAT16 && dtype != ge::DT_FLOAT) {
        OP_LOGE(context, "Unsupported dtype: %d", static_cast<int>(dtype));
        return ge::GRAPH_FAILED;
    }

    auto toVec = [](const gert::Shape& shape) {
        std::vector<int64_t> v;
        size_t n = shape.GetDimNum();
        if (n == 0) {
            v.push_back(1);
        } else {
            for (size_t i = 0; i < n; i++)
                v.push_back(shape.GetDim(i));
        }
        return v;
    };

    input_shapes = {toVec(inShape0->GetStorageShape()), toVec(inShape1->GetStorageShape())};
    output_shapes = {toVec(outShape0->GetStorageShape())};
    return ge::GRAPH_SUCCESS;
}

// ===========================================================================
// HandleEmptyTensor: initialize TilingData with safe defaults for empty input
// ===========================================================================
static ge::graphStatus HandleEmptyTensor(gert::TilingContext* context)
{
    context->SetBlockDim(1);
    ASCENDC_TPL_SEL_PARAM(context, static_cast<uint64_t>(FUSED_BIAS_LEAKY_RELU_GRAD_RANK_4));
    auto* td = context->GetTilingData<FusedBiasLeakyReluGradTilingData<4>>();
    if (td != nullptr) {
        if (memset_s(td, sizeof(FusedBiasLeakyReluGradTilingData<4>), 0, sizeof(FusedBiasLeakyReluGradTilingData<4>)) !=
            EOK) {
            OP_LOGE(context, "memset tiling data failed for empty tensor");
            return ge::GRAPH_FAILED;
        }
        td->per_buf_bytes = kAlignBytes;
        td->multicore.num_cores = 1;
    }
    return ge::GRAPH_SUCCESS;
}

// ===========================================================================
// Tiling entry
// ===========================================================================
static ge::graphStatus TilingFuncFusedBiasLeakyReluGrad(gert::TilingContext* context)
{
    OP_LOGD(context, "Enter TilingFuncFusedBiasLeakyReluGrad");

    fe::PlatFormInfos* platformInfoPtr = context->GetPlatformInfo();
    OP_CHECK_NULL_WITH_CONTEXT(context, platformInfoPtr);
    auto ascendcPlatform = platform_ascendc::PlatformAscendC(platformInfoPtr);
    int64_t coreNum = ascendcPlatform.GetCoreNumAiv();
    OP_CHECK_IF(coreNum == 0, OP_LOGE(context, "coreNum is 0"), return ge::GRAPH_FAILED);
    uint64_t ubSize = 0;
    ascendcPlatform.GetCoreMemSize(platform_ascendc::CoreMemType::UB, ubSize);
    OP_CHECK_IF(ubSize == 0, OP_LOGE(context, "ubSize is 0"), return ge::GRAPH_FAILED);

    std::vector<std::vector<int64_t>> input_shapes, output_shapes;
    ge::DataType dtype;
    ge::graphStatus ret = ReadContextShapes(context, input_shapes, output_shapes, dtype);
    if (ret != ge::GRAPH_SUCCESS)
        return ret;

    auto attrs = context->GetAttrs();
    OP_CHECK_NULL_WITH_CONTEXT(context, attrs);
    const float* negSlopePtr = attrs->GetAttrPointer<float>(0);
    float negativeSlope = (negSlopePtr != nullptr) ? *negSlopePtr : kDefaultNegativeSlope;
    const float* scalePtr = attrs->GetAttrPointer<float>(1);
    float scale = (scalePtr != nullptr) ? *scalePtr : kDefaultScale;

    std::vector<int64_t> maximum_bro_shape;
    std::vector<std::vector<int64_t>> normal_input_shapes, normal_output_shapes;
    PadAndSqueeze(input_shapes, output_shapes, maximum_bro_shape, normal_input_shapes, normal_output_shapes);

    int64_t rank = static_cast<int64_t>(maximum_bro_shape.size());

    // Squeezed rank must not exceed the maximum template rank (kRank=8); the
    // rank>4 dispatch below uses DoTiling<8>, whose TilingData arrays and the
    // stack buffers in FillIOStrides/ComputeStrides are sized kRank. A rank>8
    // shape would overflow those fixed-size arrays.
    OP_CHECK_IF(rank > FUSED_BIAS_LEAKY_RELU_GRAD_RANK_8,
                OP_LOGE(context, "Squeezed rank %ld exceeds maximum supported rank %d", rank,
                        FUSED_BIAS_LEAKY_RELU_GRAD_RANK_8),
                return ge::GRAPH_FAILED);

    bool isEmpty = false;
    for (auto d : maximum_bro_shape) {
        if (d == 0) {
            isEmpty = true;
            break;
        }
    }
    if (isEmpty) {
        return HandleEmptyTensor(context);
    }

    if (rank <= 4) {
        ASCENDC_TPL_SEL_PARAM(context, static_cast<uint64_t>(FUSED_BIAS_LEAKY_RELU_GRAD_RANK_4));
        return DoTiling<4>(context, maximum_bro_shape, normal_input_shapes, normal_output_shapes, rank, ubSize, coreNum,
                           negativeSlope, scale);
    } else {
        ASCENDC_TPL_SEL_PARAM(context, static_cast<uint64_t>(FUSED_BIAS_LEAKY_RELU_GRAD_RANK_8));
        return DoTiling<8>(context, maximum_bro_shape, normal_input_shapes, normal_output_shapes, rank, ubSize, coreNum,
                           negativeSlope, scale);
    }
}

static ge::graphStatus TilingPrepareForFusedBiasLeakyReluGrad([[maybe_unused]] gert::TilingParseContext* context)
{
    return ge::GRAPH_SUCCESS;
}

struct FusedBiasLeakyReluGradCompileInfo {};

IMPL_OP_OPTILING(FusedBiasLeakyReluGrad)
    .Tiling(TilingFuncFusedBiasLeakyReluGrad)
    .TilingParse<FusedBiasLeakyReluGradCompileInfo>(TilingPrepareForFusedBiasLeakyReluGrad);

} // namespace optiling
