/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file scatter_non_aliasing_add_proto.h
 * \brief Proto definition for ScatterNonAliasingAdd operator
 */
#ifndef OPS_OP_PROTO_INC_SCATTER_NON_ALIASING_ADD_H_
#define OPS_OP_PROTO_INC_SCATTER_NON_ALIASING_ADD_H_

#include "graph/operator_reg.h"
#include "graph/types.h"

namespace ge {

/**
 *@brief Scatter non-aliasing add: copy x to y, then scatter-add updates into y at positions specified by indices.
 *@par Inputs:
 *Three inputs, including:
 * @li x: A ND Tensor. Must be one of the following types: float32, float16, int32.
 * @li indices: A ND Tensor. Must be one of the following types: int32, int64.
 * @li updates: A ND Tensor. Must be one of the following types: float32, float16, int32.
 *@par Outputs:
 *y: A ND Tensor. Must be one of the following types: float32, float16, int32.
 */
REG_OP(ScatterNonAliasingAdd)
    .INPUT(x, TensorType({DT_FLOAT, DT_FLOAT16, DT_INT32}))
    .INPUT(indices, TensorType::IndexNumberType())
    .INPUT(updates, TensorType({DT_FLOAT, DT_FLOAT16, DT_INT32}))
    .OUTPUT(y, TensorType({DT_FLOAT, DT_FLOAT16, DT_INT32}))
    .OP_END_FACTORY_REG(ScatterNonAliasingAdd)

} // namespace ge

#endif // OPS_OP_PROTO_INC_SCATTER_NON_ALIASING_ADD_H_
