/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file sigmoid_cross_entropy_with_logits_grad_proto.h
 * \brief 定义 SigmoidCrossEntropyWithLogitsGrad 算子的原型注册接口
 */
#ifndef OPS_BUILT_IN_OP_PROTO_INC_NN_SIGMOID_CROSS_ENTROPY_WITH_LOGITS_GRAD_H_
#define OPS_BUILT_IN_OP_PROTO_INC_NN_SIGMOID_CROSS_ENTROPY_WITH_LOGITS_GRAD_H_

#include "graph/operator_reg.h"
#include "graph/types.h"

namespace ge {

/**
* @brief Computes gradients of sigmoid_cross_entropy_with_logits.

* @par Inputs:
* @li predict: An ND tensor of type float16, float32, bfloat16, specifying the predictive value.
* @li target: An ND tensor of type float16, float32, bfloat16, specifying the target value.
*     Shape must be the same as predict.
* @li dout: An ND tensor of type float16, float32, bfloat16, specifying the dout value.
*     Shape needs to satisfy the broadcast relationship with predict. \n

* @par Outputs:
* gradient: An ND tensor with the same shape and type as "predict". \n

* @par Third-party framework compatibility
* Compatible with the Pytorch operator SigmoidCrossEntropyWithLogitsGrad.
*/
REG_OP(SigmoidCrossEntropyWithLogitsGrad)
    .INPUT(predict, TensorType({DT_FLOAT16, DT_FLOAT, DT_BF16}))
    .INPUT(target, TensorType({DT_FLOAT16, DT_FLOAT, DT_BF16}))
    .INPUT(dout, TensorType({DT_FLOAT16, DT_FLOAT, DT_BF16}))
    .OUTPUT(gradient, TensorType({DT_FLOAT16, DT_FLOAT, DT_BF16}))
    .OP_END_FACTORY_REG(SigmoidCrossEntropyWithLogitsGrad)

} // namespace ge
#endif // OPS_BUILT_IN_OP_PROTO_INC_NN_SIGMOID_CROSS_ENTROPY_WITH_LOGITS_GRAD_H_
