/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

#ifndef OPS_BUILT_IN_OP_TILING_RUNTIME_SOFT_MARGIN_LOSS_TILING_H_
#define OPS_BUILT_IN_OP_TILING_RUNTIME_SOFT_MARGIN_LOSS_TILING_H_

#include "register/op_def_registry.h"
#include "register/tilingdata_base.h"
#include "op_host/tiling_base.h"
#include "tiling/tiling_api.h"
#include "util/math_util.h"
#include "soft_margin_loss_tiling.h"
#include "atvoss/elewise/elewise_base_struct.h"
#include "atvoss/reduce/reduce_tiling.h"
#include "soft_margin_loss/op_kernel/arch35/soft_margin_loss_tiling_def.h"

namespace optiling {

using namespace Ops::Base;

struct SoftMarginLossTilingKey {
    ReduceTilingKey ReduceTiling;
    uint32_t Reduction = 2;
    uint32_t Dtype = 20;
};

class SoftMarginLossTiling {
public:
    explicit SoftMarginLossTiling(gert::TilingContext* context) : tilingContext(context){};
    ge::graphStatus RunTiling(const SoftMarginLossCompileInfo* compileInfo);

protected:
    ge::graphStatus SetTilingData();
    ge::graphStatus CheckShape();
    ge::graphStatus TilingEle();
    ge::graphStatus TilingReduce(const SoftMarginLossCompileInfo* compileInfo);

private:
    ge::DataType outputDtype = ge::DT_FLOAT;
    gert::TilingContext* tilingContext;
    SoftMarginLossTilingKey key;
    SoftMarginLossTilingData* tiling = nullptr;
    uint32_t reduction = 0;
};
} // namespace optiling
#endif
