/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file apply_keras_momentum_proto.h
 * \brief ApplyKerasMomentum GE IR 原型注册
 */
#ifndef OPS_NN_OPTIM_APPLY_KERAS_MOMENTUM_PROTO_H
#define OPS_NN_OPTIM_APPLY_KERAS_MOMENTUM_PROTO_H

#include "graph/operator_reg.h"
#include "graph/types.h"

namespace ge {
/**
 *@brief Updates '*var' according to the momentum scheme.
 *   accum = accum * momentum - grad * lr
 *   if use_nesterov is True:
 *       var += accum * momentum - grad * lr
 *   else:
 *       var += accum
 *
 *@par Inputs:
 *@li var: A mutable tensor. Must be one of the data types defined in
 *    TensorType::NumberType(). Should be from a Variable().
 *@li accum: A mutable tensor. Has the same type as "var". Should be from a
 *    Variable().
 *@li lr: A tensor for the learning rate. Has the same type as "var". Should be
 *    from a Variable().
 *@li grad: A tensor for the gradient. Has the same type as "var". Should be
 *    from a Variable().
 *@li momentum: A scalar. Has the same type as "var".
 *
 *@par Attributes:
 *@li use_nesterov: An optional bool. Defaults to "False".
 *    If "True", var will be updated by using Nesterov momentum.
 *@li use_locking: An optional bool. Defaults to "False".
 *    If "True", updating of the "var" tensor is protected by a lock;
 *    otherwise the behavior is undefined, but may exhibit less contention.
 *
 *@par Outputs:
 * var: A mutable tensor. Has the same type as input "var".
 *
 *@attention Constraints:
 * The input tensors must have the same shape.
 *
 *@par Third-party framework compatibility
 * Compatible with the TensorFlow operator ResourceApplyKerasMomentum.
 *
 */

REG_OP(ApplyKerasMomentum)
    .INPUT(var, TensorType::NumberType())
    .INPUT(accum, TensorType::NumberType())
    .INPUT(lr, TensorType::NumberType())
    .INPUT(grad, TensorType::NumberType())
    .INPUT(momentum, TensorType::NumberType())
    .OUTPUT(var, TensorType::NumberType())
    .ATTR(use_locking, Bool, false)
    .ATTR(use_nesterov, Bool, false)
    .OP_END_FACTORY_REG(ApplyKerasMomentum)
} // namespace ge

#endif // OPS_NN_OPTIM_APPLY_KERAS_MOMENTUM_PROTO_H
