/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 *
 * Generated By CANNBot
 */

/**
 * NOTE: Portions of this code were AI-generated and have been
 * technically reviewed for functional accuracy and security
 */
/*!
 * \file apply_adadelta.h
 * \brief ApplyAdadelta kernel class definition (arch35)
 *
 * Aligned to canndev REG_OP(ApplyAdadelta):
 *   Inputs (7 Tensor): var, accum, accum_update, lr, rho, epsilon, grad
 *     - var/accum/accum_update/grad: full tensors (shape == var.shape)
 *     - lr/rho/epsilon: 1-element scalar tensors (shape={1})
 *   Outputs (1 Tensor): var_out (GE IR single-output view; aliased to var GM)
 *
 * Inplace semantics:
 *   The GE IR signature declares a single output (var), but Adadelta
 *   algorithmically requires accum and accum_update to be updated as well.
 *   This kernel still writes the new accum / accum_update values back to
 *   their input GM addresses (accum_gm / accum_update_gm). var_out is
 *   aliased to var_gm by the caller (inplace), so writing var_out_gm also
 *   updates var in place.
 *
 * Template parameters:
 *   - T:           Data type (float / half)
 *   - BUFFER_MODE: Buffer mode (0=single buffer, 1=double buffer)
 *
 * Adadelta update formula (4 steps):
 *   Step1: accum_new        = rho * accum + (1-rho) * grad^2
 *   Step2: update           = sqrt(accum_update + eps) / sqrt(accum_new + eps) * grad
 *   Step3: var_new          = var - lr * update
 *   Step4: accum_update_new = rho * accum_update + (1-rho) * update^2
 */
#ifndef APPLY_ADADELTA_H
#define APPLY_ADADELTA_H

#include "kernel_operator.h"
#include "kernel_tiling/kernel_tiling.h"
#include "apply_adadelta_tiling_data.h"
#include "apply_adadelta_tiling_key.h"

namespace NsApplyAdadelta {

using namespace AscendC;

template <typename T, int BUFFER_MODE>
class ApplyAdadelta {
    static constexpr int32_t BUFFER_NUM = BUFFER_MODE ? 2 : 1;
    static constexpr bool IS_FP16 = std::is_same_v<T, half>;
    // Number of float elements per 32B UB block (8 elements for fp32).
    // Used for the 1-element scalar Tensor DataCopyPad alignment.
    static constexpr int32_t SCALAR_ALIGN_ELEMS = 8;

public:
    __aicore__ inline ApplyAdadelta() {}

    __aicore__ inline void Init(
        GM_ADDR var, GM_ADDR accum, GM_ADDR accum_update,
        GM_ADDR lr, GM_ADDR rho, GM_ADDR epsilon,
        GM_ADDR grad, GM_ADDR var_out,
        const ApplyAdadeltaTilingData* tiling_data);

    __aicore__ inline void Process();

private:
    __aicore__ inline void load_scalars_from_gm(GM_ADDR lrAddr, GM_ADDR rhoAddr, GM_ADDR epsAddr);
    __aicore__ inline void CopyIn(int64_t progress, int64_t current_num);
    __aicore__ inline void Compute(int64_t current_num);
    __aicore__ inline void CopyOut(int64_t progress, int64_t current_num);

private:
    TPipe pipe;
    // 4 main-tensor input queues
    TQue<QuePosition::VECIN, BUFFER_NUM> in_que_var;
    TQue<QuePosition::VECIN, BUFFER_NUM> in_que_accum;
    TQue<QuePosition::VECIN, BUFFER_NUM> in_que_accum_update;
    TQue<QuePosition::VECIN, BUFFER_NUM> in_que_grad;
    // 3 output queues
    //   var_out_gm is aliased to var_gm by the caller (GE IR single output);
    //   accum_out / accum_update_out alias accum_gm / accum_update_gm (algorithmic inplace).
    TQue<QuePosition::VECOUT, BUFFER_NUM> out_que_var;
    TQue<QuePosition::VECOUT, BUFFER_NUM> out_que_accum;
    TQue<QuePosition::VECOUT, BUFFER_NUM> out_que_accum_update;
    // FP32 path: 2 temporary buffers for intermediate computation
    TBuf<QuePosition::VECCALC> tmp_buf1;
    TBuf<QuePosition::VECCALC> tmp_buf2;
    // FP16 path: 6 fp32 TBuf for Cast workspace + computation
    // (4 for Cast-up workspace: var/accum/accum_update/grad fp32 copies,
    //  2 for intermediate computation: tmp1/tmp2)
    TBuf<QuePosition::VECCALC> fp32_var_buf;
    TBuf<QuePosition::VECCALC> fp32_accum_buf;
    TBuf<QuePosition::VECCALC> fp32_accum_update_buf;
    TBuf<QuePosition::VECCALC> fp32_grad_buf;

    // Dedicated 32B-aligned UB scratch for the 1-element scalar Tensor reads.
    // Each scalar (lr / rho / epsilon) needs at most 1 UB block to land
    // safely; we use a single fp32-typed TBuf shared via offset.
    TBuf<QuePosition::VECCALC> scalar_buf;

    GlobalTensor<T> var_gm, accum_gm, accum_update_gm, grad_gm;
    GlobalTensor<T> var_out_gm;
    // Scalar Tensor GM views (1-element). dtype matches the main Tensor
    // dtype (T) per OpDef, and we Cast-up to fp32 in load_scalars_from_gm.
    GlobalTensor<T> lr_gm, rho_gm, epsilon_gm;

    int64_t block_length_ = 0;
    int64_t ub_length_ = 0;
    // Scalar values, materialized as fp32 in Init() from GM Tensors.
    float lr_ = 0.0f;
    float rho_ = 0.0f;
    float one_minus_rho_ = 1.0f;
    float eps_ = 1e-6f;
};

// Read a 1-element scalar Tensor from GM into UB, return the fp32 value.
// Handles both fp32 and fp16 dtypes by casting up to fp32 (for fp16 we
// need a tiny inline UB scratch since DataCopyPad cannot read a single
// fp16 element directly into a scalar register).
//
// We use a single fp32-typed TBuf "scalar_buf" with capacity for 3 * 8
// fp32 elements (3 UB blocks, one per scalar). Each scalar lands at a
// disjoint offset so the three reads do not collide.
template <typename T, int BUFFER_MODE>
__aicore__ inline void ApplyAdadelta<T, BUFFER_MODE>::load_scalars_from_gm(
    GM_ADDR lrAddr, GM_ADDR rhoAddr, GM_ADDR epsAddr)
{
    // Cast the GM pointers to GlobalTensor<T> (one element each).
    lr_gm.SetGlobalBuffer((__gm__ T*)lrAddr, 1);
    rho_gm.SetGlobalBuffer((__gm__ T*)rhoAddr, 1);
    epsilon_gm.SetGlobalBuffer((__gm__ T*)epsAddr, 1);

    // Three 32B-aligned slots in scalar_buf (8 fp32 elements per slot).
    LocalTensor<float> scratchF = scalar_buf.Get<float>();
    LocalTensor<float> slotLr  = scratchF[0 * SCALAR_ALIGN_ELEMS];
    LocalTensor<float> slotRho = scratchF[1 * SCALAR_ALIGN_ELEMS];
    LocalTensor<float> slotEps = scratchF[2 * SCALAR_ALIGN_ELEMS];

    DataCopyExtParams cpScalar;
    cpScalar.blockCount = 1;
    cpScalar.blockLen = sizeof(T);   // 1 element in bytes
    cpScalar.srcStride = 0;
    cpScalar.dstStride = 0;
    DataCopyPadExtParams<T> padParams{false, 0, 0, 0};

    if constexpr (IS_FP16) {
        // For fp16: read into a typed scratch (reuse scalar_buf via cast),
        // then Cast up to fp32 in-place using disjoint slots.
        //
        // scalar_buf is fp32-typed, but its underlying UB bytes are the
        // same regardless of view type — we use a half view onto the same
        // base UB and write 8 half elements into it, then Cast to fp32.
        LocalTensor<T> scratchH = scalar_buf.Get<T>();
        LocalTensor<T> hLr  = scratchH[0 * SCALAR_ALIGN_ELEMS * 2];  // each fp32 slot == 2 fp16 slots
        LocalTensor<T> hRho = scratchH[1 * SCALAR_ALIGN_ELEMS * 2];
        LocalTensor<T> hEps = scratchH[2 * SCALAR_ALIGN_ELEMS * 2];

        // Read 1 fp16 element into each slot (auto-padded by DataCopyPad).
        DataCopyPad(hLr,  lr_gm,      cpScalar, padParams);
        DataCopyPad(hRho, rho_gm,     cpScalar, padParams);
        DataCopyPad(hEps, epsilon_gm, cpScalar, padParams);

        // Synchronize DataCopyPad (MTE2) -> Vector. PipeBarrier is the
        // simplest synchronization that works in Init-time, where we do
        // not (yet) have an EnQue/DeQue rendezvous available.
        PipeBarrier<PIPE_ALL>();

        // Cast 1 element from fp16 to fp32. Use CAST_NONE per docs:
        // half->float is exact and does not need a round mode.
        Cast(slotLr,  hLr,  RoundMode::CAST_NONE, 1);
        Cast(slotRho, hRho, RoundMode::CAST_NONE, 1);
        Cast(slotEps, hEps, RoundMode::CAST_NONE, 1);
        PipeBarrier<PIPE_ALL>();
    } else {
        // fp32 path: DataCopyPad directly into the fp32 slots.
        DataCopyPad(slotLr,  lr_gm,      cpScalar, padParams);
        DataCopyPad(slotRho, rho_gm,     cpScalar, padParams);
        DataCopyPad(slotEps, epsilon_gm, cpScalar, padParams);
        PipeBarrier<PIPE_ALL>();
    }

    // Materialize as plain float scalars. GetValue(0) reads element [0]
    // of the LocalTensor, which is exactly where DataCopyPad landed the
    // 1-element payload.
    lr_  = slotLr.GetValue(0);
    rho_ = slotRho.GetValue(0);
    eps_ = slotEps.GetValue(0);
    one_minus_rho_ = 1.0f - rho_;
}

template <typename T, int BUFFER_MODE>
__aicore__ inline void ApplyAdadelta<T, BUFFER_MODE>::Init(
    GM_ADDR var, GM_ADDR accum, GM_ADDR accum_update,
    GM_ADDR lrAddr, GM_ADDR rhoAddr, GM_ADDR epsilonAddr,
    GM_ADDR grad, GM_ADDR var_out,
    const ApplyAdadeltaTilingData* tiling_data)
{
    // Compute per-core element range
    int64_t remain = tiling_data->totalNum - tiling_data->blockFactor * GetBlockIdx();
    block_length_ = (remain > tiling_data->blockFactor) ? tiling_data->blockFactor : remain;
    ub_length_ = tiling_data->ubFactor;

    // Set up main GM tensors with per-core offset
    int64_t off = tiling_data->blockFactor * GetBlockIdx();
    var_gm.SetGlobalBuffer((__gm__ T*)var + off, block_length_);
    accum_gm.SetGlobalBuffer((__gm__ T*)accum + off, block_length_);
    accum_update_gm.SetGlobalBuffer((__gm__ T*)accum_update + off, block_length_);
    grad_gm.SetGlobalBuffer((__gm__ T*)grad + off, block_length_);
    var_out_gm.SetGlobalBuffer((__gm__ T*)var_out + off, block_length_);

    // Initialize main queues
    pipe.InitBuffer(in_que_var, BUFFER_NUM, ub_length_ * sizeof(T));
    pipe.InitBuffer(in_que_accum, BUFFER_NUM, ub_length_ * sizeof(T));
    pipe.InitBuffer(in_que_accum_update, BUFFER_NUM, ub_length_ * sizeof(T));
    pipe.InitBuffer(in_que_grad, BUFFER_NUM, ub_length_ * sizeof(T));
    pipe.InitBuffer(out_que_var, BUFFER_NUM, ub_length_ * sizeof(T));
    pipe.InitBuffer(out_que_accum, BUFFER_NUM, ub_length_ * sizeof(T));
    pipe.InitBuffer(out_que_accum_update, BUFFER_NUM, ub_length_ * sizeof(T));

    // Initialize temporary buffers based on dtype path
    if constexpr (IS_FP16) {
        pipe.InitBuffer(fp32_var_buf,          ub_length_ * sizeof(float));
        pipe.InitBuffer(fp32_accum_buf,        ub_length_ * sizeof(float));
        pipe.InitBuffer(fp32_accum_update_buf, ub_length_ * sizeof(float));
        pipe.InitBuffer(fp32_grad_buf,         ub_length_ * sizeof(float));
        pipe.InitBuffer(tmp_buf1,             ub_length_ * sizeof(float));
        pipe.InitBuffer(tmp_buf2,             ub_length_ * sizeof(float));
    } else {
        pipe.InitBuffer(tmp_buf1, ub_length_ * sizeof(float));
        pipe.InitBuffer(tmp_buf2, ub_length_ * sizeof(float));
    }

    // Scalar scratch: 3 * 8 fp32 elements = 96 bytes (3 UB blocks). Each
    // slot holds exactly one fp32 scalar value after the read.
    pipe.InitBuffer(scalar_buf, 3 * SCALAR_ALIGN_ELEMS * sizeof(float));

    // Read lr/rho/epsilon from their 1-element GM Tensors into fp32 scalars.
    // Every core executes this (not just block 0) so each core has its own
    // local copies of the three values for the per-core Process() loop.
    load_scalars_from_gm(lrAddr, rhoAddr, epsilonAddr);
}

template <typename T, int BUFFER_MODE>
__aicore__ inline void ApplyAdadelta<T, BUFFER_MODE>::CopyIn(int64_t progress, int64_t current_num)
{
    LocalTensor<T> v = in_que_var.template AllocTensor<T>();
    LocalTensor<T> a = in_que_accum.template AllocTensor<T>();
    LocalTensor<T> au = in_que_accum_update.template AllocTensor<T>();
    LocalTensor<T> g = in_que_grad.template AllocTensor<T>();

    DataCopyExtParams cp;
    cp.blockCount = 1;
    cp.blockLen = current_num * sizeof(T);
    cp.srcStride = 0;
    cp.dstStride = 0;
    DataCopyPadExtParams<T> padParams{false, 0, 0, 0};
    int64_t gm_off = progress * ub_length_;
    DataCopyPad(v, var_gm[gm_off], cp, padParams);
    DataCopyPad(a, accum_gm[gm_off], cp, padParams);
    DataCopyPad(au, accum_update_gm[gm_off], cp, padParams);
    DataCopyPad(g, grad_gm[gm_off], cp, padParams);

    in_que_var.EnQue(v);
    in_que_accum.EnQue(a);
    in_que_accum_update.EnQue(au);
    in_que_grad.EnQue(g);
}

template <typename T, int BUFFER_MODE>
__aicore__ inline void ApplyAdadelta<T, BUFFER_MODE>::Compute(int64_t current_num)
{
    LocalTensor<T> v = in_que_var.template DeQue<T>();
    LocalTensor<T> a = in_que_accum.template DeQue<T>();
    LocalTensor<T> au = in_que_accum_update.template DeQue<T>();
    LocalTensor<T> g = in_que_grad.template DeQue<T>();

    LocalTensor<T> v_out = out_que_var.template AllocTensor<T>();
    LocalTensor<T> a_out = out_que_accum.template AllocTensor<T>();
    LocalTensor<T> au_out = out_que_accum_update.template AllocTensor<T>();

    LocalTensor<float> tmp1 = tmp_buf1.Get<float>();
    LocalTensor<float> tmp2 = tmp_buf2.Get<float>();

    if constexpr (IS_FP16) {
        // FP16 path: Cast up to fp32 -> compute -> Cast down to fp16
        LocalTensor<float> vF  = fp32_var_buf.Get<float>();
        LocalTensor<float> aF  = fp32_accum_buf.Get<float>();
        LocalTensor<float> auF = fp32_accum_update_buf.Get<float>();
        LocalTensor<float> gF  = fp32_grad_buf.Get<float>();

        Cast(vF,  v,  RoundMode::CAST_NONE, current_num);
        Cast(aF,  a,  RoundMode::CAST_NONE, current_num);
        Cast(auF, au, RoundMode::CAST_NONE, current_num);
        Cast(gF,  g,  RoundMode::CAST_NONE, current_num);

        // Step1: accum_new = accum * rho + grad^2 * (1 - rho)
        Mul(tmp1, gF, gF, current_num);
        Muls(tmp1, tmp1, one_minus_rho_, current_num);
        Muls(aF, aF, rho_, current_num);
        Add(aF, aF, tmp1, current_num);

        // Step2: update = sqrt(au_old + eps) / sqrt(accum_new + eps) * grad
        Adds(tmp1, auF, eps_, current_num);
        Sqrt(tmp1, tmp1, current_num);
        Adds(tmp2, aF, eps_, current_num);
        Sqrt(tmp2, tmp2, current_num);
        Div(tmp1, tmp1, tmp2, current_num);
        Mul(tmp1, tmp1, gF, current_num);

        // Step3: var_new = var - lr * update
        Muls(tmp2, tmp1, lr_, current_num);
        Sub(vF, vF, tmp2, current_num);

        // Step4: accum_update_new = au_old * rho + update^2 * (1 - rho)
        Mul(tmp2, tmp1, tmp1, current_num);
        Muls(tmp2, tmp2, one_minus_rho_, current_num);
        Muls(auF, auF, rho_, current_num);
        Add(auF, auF, tmp2, current_num);

        Cast(v_out,  vF,  RoundMode::CAST_RINT, current_num);
        Cast(a_out,  aF,  RoundMode::CAST_RINT, current_num);
        Cast(au_out, auF, RoundMode::CAST_RINT, current_num);
    } else {
        // FP32 path: T == float; operate directly on inputs / outputs.

        // Step1: accum_new = rho * accum + (1-rho) * grad^2
        Mul(tmp1, g, g, current_num);
        Muls(tmp1, tmp1, one_minus_rho_, current_num);
        Muls(a_out, a, rho_, current_num);
        Add(a_out, a_out, tmp1, current_num);

        // Step2: update = sqrt(accum_update + eps) / sqrt(accum_new + eps) * grad
        Adds(tmp1, au, eps_, current_num);
        Sqrt(tmp1, tmp1, current_num);
        Adds(tmp2, a_out, eps_, current_num);
        Sqrt(tmp2, tmp2, current_num);
        Div(tmp1, tmp1, tmp2, current_num);
        Mul(tmp1, tmp1, g, current_num);

        // Step3: var_new = var - lr * update
        Muls(tmp2, tmp1, lr_, current_num);
        Sub(v_out, v, tmp2, current_num);

        // Step4: accum_update_new = rho * accum_update + (1-rho) * update^2
        Mul(tmp2, tmp1, tmp1, current_num);
        Muls(tmp2, tmp2, one_minus_rho_, current_num);
        Muls(au_out, au, rho_, current_num);
        Add(au_out, au_out, tmp2, current_num);
    }

    in_que_var.FreeTensor(v);
    in_que_accum.FreeTensor(a);
    in_que_accum_update.FreeTensor(au);
    in_que_grad.FreeTensor(g);

    out_que_var.EnQue(v_out);
    out_que_accum.EnQue(a_out);
    out_que_accum_update.EnQue(au_out);
}

template <typename T, int BUFFER_MODE>
__aicore__ inline void ApplyAdadelta<T, BUFFER_MODE>::CopyOut(int64_t progress, int64_t current_num)
{
    LocalTensor<T> v_out = out_que_var.template DeQue<T>();
    LocalTensor<T> a_out = out_que_accum.template DeQue<T>();
    LocalTensor<T> au_out = out_que_accum_update.template DeQue<T>();

    DataCopyExtParams cp;
    cp.blockCount = 1;
    cp.blockLen = current_num * sizeof(T);
    cp.srcStride = 0;
    cp.dstStride = 0;
    int64_t gm_off = progress * ub_length_;
    // GE IR var output (aliased to var GM)
    DataCopyPad(var_out_gm[gm_off], v_out, cp);
    // Algorithmic inplace: write new accum/accum_update back to their
    // input GM (no separate output addresses exist in the new GE IR).
    DataCopyPad(accum_gm[gm_off], a_out, cp);
    DataCopyPad(accum_update_gm[gm_off], au_out, cp);

    out_que_var.FreeTensor(v_out);
    out_que_accum.FreeTensor(a_out);
    out_que_accum_update.FreeTensor(au_out);
}

template <typename T, int BUFFER_MODE>
__aicore__ inline void ApplyAdadelta<T, BUFFER_MODE>::Process()
{
    int64_t loop_count = (block_length_ + ub_length_ - 1) / ub_length_;
    for (int64_t i = 0; i < loop_count; i++) {
        int64_t current_num = (i == (loop_count - 1)) ? (block_length_ - ub_length_ * i) : ub_length_;
        CopyIn(i, current_num);
        Compute(current_num);
        CopyOut(i, current_num);
    }
}

} // namespace NsApplyAdadelta
#endif // APPLY_ADADELTA_H
