/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file sparse_apply_adadelta_infershape.cpp
 * \brief Infershape implementation for sparse_apply_adadelta operator
 *
 * Output shapes: var_out=var, accum_out=accum, accum_update_out=accum_update
 */
#include "register/op_impl_registry.h"
#include "log/log.h"

using namespace ge;

namespace ops {
static constexpr int64_t IDX_VAR = 0;
static constexpr int64_t IDX_ACCUM = 1;
static constexpr int64_t IDX_ACCUM_UPDATE = 2;
static constexpr int64_t IDX_GRAD = 6;
static constexpr int64_t IDX_INDICES = 7;

static void CopyShape(const gert::Shape* src, gert::Shape* dst)
{
    dst->SetDimNum(src->GetDimNum());
    for (size_t i = 0; i < src->GetDimNum(); i++) {
        dst->SetDim(i, src->GetDim(i));
    }
}

static ge::graphStatus InferShapeSparseApplyAdadelta(gert::InferShapeContext* context)
{
    OP_LOGD(context->GetNodeName(), "Begin InferShapeSparseApplyAdadelta");

    // var_out.shape = var.shape
    const gert::Shape* varShape = context->GetInputShape(IDX_VAR);
    OP_CHECK_NULL_WITH_CONTEXT(context, varShape);
    gert::Shape* varOutShape = context->GetOutputShape(IDX_VAR);
    OP_CHECK_NULL_WITH_CONTEXT(context, varOutShape);
    CopyShape(varShape, varOutShape);

    // accum_out.shape = accum.shape
    const gert::Shape* accumShape = context->GetInputShape(IDX_ACCUM);
    OP_CHECK_NULL_WITH_CONTEXT(context, accumShape);
    gert::Shape* accumOutShape = context->GetOutputShape(IDX_ACCUM);
    OP_CHECK_NULL_WITH_CONTEXT(context, accumOutShape);
    CopyShape(accumShape, accumOutShape);

    // accum_update_out.shape = accum_update.shape
    const gert::Shape* accumUpdateShape = context->GetInputShape(IDX_ACCUM_UPDATE);
    OP_CHECK_NULL_WITH_CONTEXT(context, accumUpdateShape);
    gert::Shape* accumUpdateOutShape = context->GetOutputShape(IDX_ACCUM_UPDATE);
    OP_CHECK_NULL_WITH_CONTEXT(context, accumUpdateOutShape);
    CopyShape(accumUpdateShape, accumUpdateOutShape);

    // 校验：var/accum/accum_update rank 一致
    if (varShape->GetDimNum() != accumShape->GetDimNum()) {
        OP_LOGE(context->GetNodeName(), "var and accum must have same rank");
        return ge::GRAPH_FAILED;
    }
    if (varShape->GetDimNum() != accumUpdateShape->GetDimNum()) {
        OP_LOGE(context->GetNodeName(), "var and accum_update must have same rank");
        return ge::GRAPH_FAILED;
    }

    // 校验：grad.shape[0] == indices.shape[0]
    const gert::Shape* gradShape = context->GetInputShape(IDX_GRAD);
    OP_CHECK_NULL_WITH_CONTEXT(context, gradShape);
    const gert::Shape* indicesShape = context->GetInputShape(IDX_INDICES);
    OP_CHECK_NULL_WITH_CONTEXT(context, indicesShape);
    if (gradShape->GetDim(0) != indicesShape->GetDim(0)) {
        OP_LOGE(context->GetNodeName(), "grad first dim must equal indices length");
        return ge::GRAPH_FAILED;
    }

    // 校验：grad.shape[1:] == var.shape[1:]（SE §5.4 约束）
    if (gradShape->GetDimNum() != varShape->GetDimNum()) {
        OP_LOGE(context->GetNodeName(), "grad and var must have same rank");
        return ge::GRAPH_FAILED;
    }
    for (size_t i = 1; i < varShape->GetDimNum(); i++) {
        if (gradShape->GetDim(i) != varShape->GetDim(i)) {
            OP_LOGE(context->GetNodeName(), "grad trailing dims must match var trailing dims");
            return ge::GRAPH_FAILED;
        }
    }

    OP_LOGD(context->GetNodeName(), "End InferShapeSparseApplyAdadelta");
    return GRAPH_SUCCESS;
}

IMPL_OP_INFERSHAPE(SparseApplyAdadelta).InferShape(InferShapeSparseApplyAdadelta);
}  // namespace ops
