/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/**
 * NOTE: Portions of this code were AI-generated and have been
 * technically reviewed for functional accuracy and security
 *
 * Generated By CANNBot
 */

/*!
 * \file softshrink_def.cpp
 * \brief Softshrink 算子定义，声明输入输出和算子配置（Ascend950 / arch35）
 *
 * 命名一致性约定（方案 Z - 完全对齐 hard_shrink）：
 *   - 目录名 / opFile.value / kernel 文件名 / kernel 函数名 / 头文件守卫 / 宏 全部统一为 softshrink / SOFTSHRINK_*
 *   - class 名 Softshrink、aclnn API 名 aclnnSoftshrink、OP_TYPE 名 Softshrink 保持不变（PascalCase）
 *   - CANN 构建系统强约束：kernel 入口函数名必须 = OP_TYPE 类名的 snake-split (Softshrink → softshrink)
 */
#include "register/op_def_registry.h"

namespace ops {
class Softshrink : public OpDef {
public:
    explicit Softshrink(const char* name) : OpDef(name)
    {
        this->Input("x")
            .ParamType(REQUIRED)
            .DataType({ge::DT_FLOAT16, ge::DT_FLOAT, ge::DT_BF16})
            .Format({ge::FORMAT_ND, ge::FORMAT_ND, ge::FORMAT_ND})
            .UnknownShapeFormat({ge::FORMAT_ND, ge::FORMAT_ND, ge::FORMAT_ND})
            .AutoContiguous();
        this->Output("y")
            .ParamType(REQUIRED)
            .DataType({ge::DT_FLOAT16, ge::DT_FLOAT, ge::DT_BF16})
            .Format({ge::FORMAT_ND, ge::FORMAT_ND, ge::FORMAT_ND})
            .UnknownShapeFormat({ge::FORMAT_ND, ge::FORMAT_ND, ge::FORMAT_ND})
            .AutoContiguous();

        // lambd 作为 Attr 传递到 Tiling（PyTorch 语义默认值 0.5，aclnn 校验 >= 0）
        this->Attr("lambd").AttrType(OPTIONAL).Float(0.5f);

        OpAICoreConfig aiCoreConfig;
        aiCoreConfig.DynamicCompileStaticFlag(true)
            .DynamicFormatFlag(false)
            .DynamicRankSupportFlag(true)
            .DynamicShapeSupportFlag(true)
            .NeedCheckSupportFlag(false)
            .PrecisionReduceFlag(true)
            // opFile.value 必须与算子目录名 / kernel 入口函数名严格一致（方案 Z）：
            //   目录名 = activation/softshrink/ → opFile.value = "softshrink"
            //   不加 _apt 后缀，与 hard_shrink 走同一约定。
            //   class 名 Softshrink 保持 PascalCase；构建系统按类名 snake-split 推导 kernel 入口名。
            .ExtendCfgInfo("opFile.value", "softshrink");
        this->AICore().AddConfig("ascend950", aiCoreConfig);
    }
};
OP_ADD(Softshrink);
} // namespace ops
