/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file foreach_binary_op_simt.h
 * \brief SIMT kernel implementation for foreach_binary_op operator.
 *        Computes y_i = x1_i <op> x2_i for each tensor in the list, where <op> is
 *        selected at compile time by op_code: 0=add, 1=sub, 2=mul, 3=div.
 *        Supports 4 dtype paths: FP16 (cast to FP32), FP32 (direct), INT32 (direct),
 *        BF16 (cast to FP32). IDX_T template selects 32/64-bit index width.
 */

#ifndef FOREACH_BINARY_OP_SIMT_H
#define FOREACH_BINARY_OP_SIMT_H

#include "kernel_operator.h"
#include "kernel_tiling/kernel_tiling.h"
#include "kernel_operator_list_tensor_intf.h"
#include "foreach_binary_op_tiling_data.h"
#include "foreach_binary_op_tiling_key.h"

// SIMT type conversion headers
#include "simt_api/asc_simt.h"
#include "simt_api/asc_fp16.h"
#include "simt_api/asc_bf16.h"
#include "simt_api/common_functions.h"

namespace NsForeachBinaryOp {

using namespace AscendC;

// ========== op_code dispatch constants ==========
constexpr uint32_t OP_CODE_ADD = 0;
constexpr uint32_t OP_CODE_SUB = 1;
constexpr uint32_t OP_CODE_MUL = 2;
constexpr uint32_t OP_CODE_DIV = 3;

// ========== Thread count by index type width ==========
template <typename IDX_T>
constexpr uint32_t THREAD_NUM_VF = (sizeof(IDX_T) == 4) ? 1024 : 512;

// ========== Compile-time binary op apply ==========
template <typename T, uint32_t OP>
__simt_callee__ inline T BinaryApply(T a, T b)
{
    if constexpr (OP == OP_CODE_ADD) {
        return a + b;
    } else if constexpr (OP == OP_CODE_SUB) {
        return a - b;
    } else if constexpr (OP == OP_CODE_MUL) {
        return a * b;
    } else {
        // Integer divide-by-zero is undefined on device (may trap); guard it. Float div by 0
        // yields IEEE inf/nan which is well-defined and left as-is.
        if constexpr (std::is_integral_v<T>) {
            return (b == static_cast<T>(0)) ? static_cast<T>(0) : (a / b);
        } else {
            return a / b;
        }
    }
}

// ========== Cast helpers (required for VF callee chain) ==========
__simt_callee__ inline float CastBf16ToFloat(bfloat16_t val) { return __bfloat162float(val); }

__simt_callee__ inline bfloat16_t CastFloatToBf16(float val) { return __float2bfloat16_rn(val); }

// ========== Direct compute kernel (float32, int32) ==========
template <typename T, typename IDX_T, uint32_t OP>
__simt_vf__ __aicore__ LAUNCH_BOUND(THREAD_NUM_VF<IDX_T>) inline void OpForeachBinaryDirectSimt(IDX_T count,
                                                                                                __gm__ T* x1,
                                                                                                __gm__ T* x2,
                                                                                                __gm__ T* y)
{
    for (IDX_T index = static_cast<IDX_T>(threadIdx.x); index < count; index += static_cast<IDX_T>(blockDim.x)) {
        y[index] = BinaryApply<T, OP>(x1[index], x2[index]);
    }
}

// ========== FP16 compute kernel (via FP32 intermediate for precision) ==========
template <typename IDX_T, uint32_t OP>
__simt_vf__ __aicore__ LAUNCH_BOUND(THREAD_NUM_VF<IDX_T>) inline void OpForeachBinaryFp16CastSimt(IDX_T count,
                                                                                                  __gm__ half* x1,
                                                                                                  __gm__ half* x2,
                                                                                                  __gm__ half* y)
{
    for (IDX_T index = static_cast<IDX_T>(threadIdx.x); index < count; index += static_cast<IDX_T>(blockDim.x)) {
        float x1_val = __half2float(x1[index]);
        float x2_val = __half2float(x2[index]);
        float result = BinaryApply<float, OP>(x1_val, x2_val);
        y[index] = __float2half_rn(result);
    }
}

// ========== BF16 compute kernel (via FP32 intermediate) ==========
template <typename IDX_T, uint32_t OP>
__simt_vf__ __aicore__ LAUNCH_BOUND(THREAD_NUM_VF<IDX_T>) inline void OpForeachBinaryBf16CastSimt(IDX_T count,
                                                                                                  __gm__ bfloat16_t* x1,
                                                                                                  __gm__ bfloat16_t* x2,
                                                                                                  __gm__ bfloat16_t* y)
{
    for (IDX_T index = static_cast<IDX_T>(threadIdx.x); index < count; index += static_cast<IDX_T>(blockDim.x)) {
        float x1_val = CastBf16ToFloat(x1[index]);
        float x2_val = CastBf16ToFloat(x2[index]);
        float result = BinaryApply<float, OP>(x1_val, x2_val);
        y[index] = CastFloatToBf16(result);
    }
}

// ========== Process: per-core multi-tensor iteration with 32/64-bit dispatch ==========

template <uint32_t OP>
__aicore__ inline void ForeachBinaryOpProcessFp16(GM_ADDR x1, GM_ADDR x2, GM_ADDR y,
                                                  const ForeachBinaryOpTilingData* tilingData)
{
    int32_t coreId = GetBlockIdx();
    int32_t startT = static_cast<int32_t>(tilingData->tensorStartList[coreId]);
    int32_t endT = static_cast<int32_t>(tilingData->tensorEndList[coreId]);

    ListTensorDesc x1List(reinterpret_cast<__gm__ void*>(x1));
    ListTensorDesc x2List(reinterpret_cast<__gm__ void*>(x2));
    ListTensorDesc yList(reinterpret_cast<__gm__ void*>(y));

    for (int32_t t = startT; t <= endT; t++) {
        __gm__ half* x1_t = x1List.GetDataPtr<half>(t);
        __gm__ half* x2_t = x2List.GetDataPtr<half>(t);
        __gm__ half* y_t = yList.GetDataPtr<half>(t);

        int64_t totalCount = tilingData->tensorDataCountList[t];
        int64_t localStart = (t == startT) ? tilingData->tensorStartOffsetList[coreId] : 0;
        int64_t localEnd = (t == endT) ? tilingData->tensorEndOffsetList[coreId] + 1 : totalCount;
        int64_t localCount = localEnd - localStart;

        if (localCount > 0) {
            if (localCount <= static_cast<int64_t>(INT32_MAX)) {
                asc_vf_call<OpForeachBinaryFp16CastSimt<int32_t, OP>>(
                    dim3(THREAD_NUM_VF<int32_t>), static_cast<int32_t>(localCount), x1_t + localStart,
                    x2_t + localStart, y_t + localStart);
            } else {
                asc_vf_call<OpForeachBinaryFp16CastSimt<int64_t, OP>>(
                    dim3(THREAD_NUM_VF<int64_t>), localCount, x1_t + localStart, x2_t + localStart, y_t + localStart);
            }
        }
    }
}

template <uint32_t OP>
__aicore__ inline void ForeachBinaryOpProcessFp32(GM_ADDR x1, GM_ADDR x2, GM_ADDR y,
                                                  const ForeachBinaryOpTilingData* tilingData)
{
    int32_t coreId = GetBlockIdx();
    int32_t startT = static_cast<int32_t>(tilingData->tensorStartList[coreId]);
    int32_t endT = static_cast<int32_t>(tilingData->tensorEndList[coreId]);

    ListTensorDesc x1List(reinterpret_cast<__gm__ void*>(x1));
    ListTensorDesc x2List(reinterpret_cast<__gm__ void*>(x2));
    ListTensorDesc yList(reinterpret_cast<__gm__ void*>(y));

    for (int32_t t = startT; t <= endT; t++) {
        __gm__ float* x1_t = x1List.GetDataPtr<float>(t);
        __gm__ float* x2_t = x2List.GetDataPtr<float>(t);
        __gm__ float* y_t = yList.GetDataPtr<float>(t);

        int64_t totalCount = tilingData->tensorDataCountList[t];
        int64_t localStart = (t == startT) ? tilingData->tensorStartOffsetList[coreId] : 0;
        int64_t localEnd = (t == endT) ? tilingData->tensorEndOffsetList[coreId] + 1 : totalCount;
        int64_t localCount = localEnd - localStart;

        if (localCount > 0) {
            if (localCount <= static_cast<int64_t>(INT32_MAX)) {
                asc_vf_call<OpForeachBinaryDirectSimt<float, int32_t, OP>>(
                    dim3(THREAD_NUM_VF<int32_t>), static_cast<int32_t>(localCount), x1_t + localStart,
                    x2_t + localStart, y_t + localStart);
            } else {
                asc_vf_call<OpForeachBinaryDirectSimt<float, int64_t, OP>>(
                    dim3(THREAD_NUM_VF<int64_t>), localCount, x1_t + localStart, x2_t + localStart, y_t + localStart);
            }
        }
    }
}

template <uint32_t OP>
__aicore__ inline void ForeachBinaryOpProcessInt32(GM_ADDR x1, GM_ADDR x2, GM_ADDR y,
                                                   const ForeachBinaryOpTilingData* tilingData)
{
    int32_t coreId = GetBlockIdx();
    int32_t startT = static_cast<int32_t>(tilingData->tensorStartList[coreId]);
    int32_t endT = static_cast<int32_t>(tilingData->tensorEndList[coreId]);

    ListTensorDesc x1List(reinterpret_cast<__gm__ void*>(x1));
    ListTensorDesc x2List(reinterpret_cast<__gm__ void*>(x2));
    ListTensorDesc yList(reinterpret_cast<__gm__ void*>(y));

    for (int32_t t = startT; t <= endT; t++) {
        __gm__ int32_t* x1_t = x1List.GetDataPtr<int32_t>(t);
        __gm__ int32_t* x2_t = x2List.GetDataPtr<int32_t>(t);
        __gm__ int32_t* y_t = yList.GetDataPtr<int32_t>(t);

        int64_t totalCount = tilingData->tensorDataCountList[t];
        int64_t localStart = (t == startT) ? tilingData->tensorStartOffsetList[coreId] : 0;
        int64_t localEnd = (t == endT) ? tilingData->tensorEndOffsetList[coreId] + 1 : totalCount;
        int64_t localCount = localEnd - localStart;

        if (localCount > 0) {
            if (localCount <= static_cast<int64_t>(INT32_MAX)) {
                asc_vf_call<OpForeachBinaryDirectSimt<int32_t, int32_t, OP>>(
                    dim3(THREAD_NUM_VF<int32_t>), static_cast<int32_t>(localCount), x1_t + localStart,
                    x2_t + localStart, y_t + localStart);
            } else {
                asc_vf_call<OpForeachBinaryDirectSimt<int32_t, int64_t, OP>>(
                    dim3(THREAD_NUM_VF<int64_t>), localCount, x1_t + localStart, x2_t + localStart, y_t + localStart);
            }
        }
    }
}

template <uint32_t OP>
__aicore__ inline void ForeachBinaryOpProcessBf16(GM_ADDR x1, GM_ADDR x2, GM_ADDR y,
                                                  const ForeachBinaryOpTilingData* tilingData)
{
    int32_t coreId = GetBlockIdx();
    int32_t startT = static_cast<int32_t>(tilingData->tensorStartList[coreId]);
    int32_t endT = static_cast<int32_t>(tilingData->tensorEndList[coreId]);

    ListTensorDesc x1List(reinterpret_cast<__gm__ void*>(x1));
    ListTensorDesc x2List(reinterpret_cast<__gm__ void*>(x2));
    ListTensorDesc yList(reinterpret_cast<__gm__ void*>(y));

    for (int32_t t = startT; t <= endT; t++) {
        __gm__ bfloat16_t* x1_t = x1List.GetDataPtr<bfloat16_t>(t);
        __gm__ bfloat16_t* x2_t = x2List.GetDataPtr<bfloat16_t>(t);
        __gm__ bfloat16_t* y_t = yList.GetDataPtr<bfloat16_t>(t);

        int64_t totalCount = tilingData->tensorDataCountList[t];
        int64_t localStart = (t == startT) ? tilingData->tensorStartOffsetList[coreId] : 0;
        int64_t localEnd = (t == endT) ? tilingData->tensorEndOffsetList[coreId] + 1 : totalCount;
        int64_t localCount = localEnd - localStart;

        if (localCount > 0) {
            if (localCount <= static_cast<int64_t>(INT32_MAX)) {
                asc_vf_call<OpForeachBinaryBf16CastSimt<int32_t, OP>>(
                    dim3(THREAD_NUM_VF<int32_t>), static_cast<int32_t>(localCount), x1_t + localStart,
                    x2_t + localStart, y_t + localStart);
            } else {
                asc_vf_call<OpForeachBinaryBf16CastSimt<int64_t, OP>>(
                    dim3(THREAD_NUM_VF<int64_t>), localCount, x1_t + localStart, x2_t + localStart, y_t + localStart);
            }
        }
    }
}

} // namespace NsForeachBinaryOp

#endif // FOREACH_BINARY_OP_SIMT_H
