/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file foreach_binary_op_tiling_key.h
 * \brief Tiling key definitions for foreach_binary_op operator.
 *        Combined key = op_code * 4 + dtypeIdx, covering 4 ops (add/sub/mul/div)
 *        x 4 dtypes (FP16/FP32/INT32/BF16) = 16 schedule modes [0, 15].
 */

#ifndef FOREACH_BINARY_OP_TILING_KEY_H
#define FOREACH_BINARY_OP_TILING_KEY_H

#include "ascendc/host_api/tiling/template_argument.h"

ASCENDC_TPL_ARGS_DECL(ForeachBinaryOp, ASCENDC_TPL_UINT_DECL(schMode, 4, ASCENDC_TPL_UI_LIST, 0, 1, 2, 3, 4, 5, 6, 7, 8,
                                                             9, 10, 11, 12, 13, 14, 15));

ASCENDC_TPL_SEL(ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_UINT_SEL(schMode, ASCENDC_TPL_UI_LIST, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9,
                                                          10, 11, 12, 13, 14, 15)));

#endif // FOREACH_BINARY_OP_TILING_KEY_H
