/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file celu_proto.h
 * \brief
 */
#ifndef CELU_PROTO_H_
#define CELU_PROTO_H_

#include "graph/operator_reg.h"

namespace ge {
/**
* @brief Continuously Differentiable Exponential Linear Units activation function.
*
* @par Inputs:
* x: An ND tensor. Must be one of the following types: float16, float32.
*
* @par Attributes:
* @li alpha1: An optional float32. Negative region scale factor. Defaults to "1.0".
* @li alpha2: An optional float32. Negative region slope factor. Defaults to "1.0".
* @li alpha3: An optional float32. Positive region fixed output factor. Defaults to "1.0".
*
* @par Outputs:
* y: A tensor of the same type, shape and format as input x.
*
* @par Third-party framework compatibility
* @li Compatible with ONNX's Celu operator
*/
REG_OP(Celu)
    .INPUT(x, TensorType({DT_FLOAT,DT_FLOAT16}))
    .OUTPUT(y, TensorType({DT_FLOAT,DT_FLOAT16}))
    .ATTR(alpha1, Float, 1.0)
    .ATTR(alpha2, Float, 1.0)
    .ATTR(alpha3, Float, 1.0)
    .OP_END_FACTORY_REG(Celu)
} // namespace ge
#endif
