/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file foreach_log10_simt.h
 * \brief SIMT kernel implementation for foreach_log10
 */

#ifndef FOREACH_LOG10_SIMT_H
#define FOREACH_LOG10_SIMT_H

#include "kernel_operator.h"
#include "kernel_tiling/kernel_tiling.h"
#include "simt_api/asc_simt.h"
#include "simt_api/math_functions.h"
#include "simt_api/asc_fp16.h"
#include "simt_api/asc_bf16.h"
#include "foreach_log10_tiling_data.h"
#include "foreach_log10_tiling_key.h"

namespace NsForeachLog10 {

constexpr int TENSOR_PTR_SHIFT = 3;

using namespace AscendC;

constexpr uint32_t THREAD_NUM = 1024;

template <typename T>
__simt_callee__ inline __gm__ T* SimtGetTensorAddr(GM_ADDR tensorListPtr, int64_t idx)
{
    __gm__ uint64_t* dataAddr = reinterpret_cast<__gm__ uint64_t*>(tensorListPtr);
    uint64_t tensorPtrOffset = *dataAddr;
    __gm__ uint64_t* tensorPtr = dataAddr + (tensorPtrOffset >> TENSOR_PTR_SHIFT);
    return reinterpret_cast<__gm__ T*>(*(tensorPtr + idx));
}

template <typename T>
__simt_callee__ inline T Log10Func(T x);

template <>
__simt_callee__ inline float Log10Func<float>(float x)
{
    return log10f(x);
}

template <>
__simt_callee__ inline half Log10Func<half>(half x)
{
    return hlog10(x);
}

template <>
__simt_callee__ inline bfloat16_t Log10Func<bfloat16_t>(bfloat16_t x)
{
    return hlog10(x);
}

template <typename T>
__simt_vf__ __aicore__ LAUNCH_BOUND(THREAD_NUM) inline void OpForeachLog10Simt(int32_t tensorCount,
                                                                               __gm__ int64_t* tensorElements,
                                                                               GM_ADDR xList, GM_ADDR yList)
{
    for (int32_t t = 0; t < tensorCount; t++) {
        int64_t count = tensorElements[t];
        if (count == 0) {
            continue;
        }

        __gm__ T* xData = SimtGetTensorAddr<T>(xList, t);
        __gm__ T* yData = SimtGetTensorAddr<T>(yList, t);

        uint64_t tid = static_cast<uint64_t>(blockIdx.x * blockDim.x + threadIdx.x);
        uint64_t stride = static_cast<uint64_t>(blockDim.x * gridDim.x);

        for (uint64_t idx = tid; idx < static_cast<uint64_t>(count); idx += stride) {
            T val = xData[idx];
            yData[idx] = Log10Func<T>(val);
        }
    }
}

template <typename T>
__aicore__ inline void Process(GM_ADDR x, GM_ADDR y, const __gm__ ForeachLog10TilingData* tilingGm)
{
    __gm__ int64_t* elemCounts = reinterpret_cast<__gm__ int64_t*>(
        reinterpret_cast<__gm__ char*>(const_cast<__gm__ ForeachLog10TilingData*>(tilingGm)) +
        offsetof(ForeachLog10TilingData, tensorElements));

    int32_t tensorCount = tilingGm->tensorCount;

    asc_vf_call<OpForeachLog10Simt<T>>(dim3(THREAD_NUM), tensorCount, elemCounts, x, y);
}

} // namespace NsForeachLog10

#endif // FOREACH_LOG10_SIMT_H
