/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file selu_grad_tiling_data.h
 * \brief TilingData 结构体定义（arch35 架构）
 *
 * 迭代二：TilingKey_0 (OneDim) + TilingKey_1 (Broadcast)
 * 支持 float16, float32, bfloat16 三种浮点 dtype
 */

#ifndef _SELU_GRAD_TILING_DATA_H_
#define _SELU_GRAD_TILING_DATA_H_

constexpr int32_t SELU_GRAD_MAX_DIM = 8;

struct SeluGradTilingData {
    // === 基础信息（TilingKey_0 和 TilingKey_1 共用） ===
    int64_t totalElements = 0;   // 输出总元素数（broadcast 后）
    int64_t blockFormer = 0;     // OneDim: 每核元素数; Broadcast: 每核行数
    int64_t ubFormer = 0;        // OneDim: 每次 UB 元素数; Broadcast: 每次 UB 行数

    // === 广播信息（TilingKey_1 使用） ===
    int32_t needBroadcast = 0;   // 0=无需广播, 1=需要广播
    int32_t shapeLen = 0;        // 合轴后维度数
    int64_t innerSize = 0;       // 连续内维大小（最内层连续非广播轴及其右侧元素积）
    int64_t totalRows = 0;       // 外层行数 = totalElements / innerSize
    int64_t innerChunkSize = 0;  // 内维分块大小（每块元素数，<= innerSize）
    int32_t numInnerChunks = 0;  // 内维分块数 = CeilDiv(innerSize, innerChunkSize)

    // === 多维广播参数（仅 TilingKey_1 使用） ===
    int64_t outputDims[SELU_GRAD_MAX_DIM];    // 合轴后输出 shape
    int64_t gradStrides[SELU_GRAD_MAX_DIM];   // gradients 合轴后 stride（0=广播轴）
    int64_t outStrides[SELU_GRAD_MAX_DIM];    // outputs 合轴后 stride（0=广播轴）
};

#endif // _SELU_GRAD_TILING_DATA_H_
