/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot - Iter2 Fix */

/*!
 * \file selu_grad.h
 * \brief SeluGrad 算子 Kernel 类定义（arch35 架构）
 *
 * 全 dtype × 2 SCH_MODE = 12 TilingKey。
 *
 * 设计：计算逻辑封装为两个 "Kit"，搬运/切分逻辑封装为两个驱动类，二者组合：
 *   - SeluGradDirectKit<T>  : float 直算（在 T==float 上原地计算）
 *   - SeluGradTransitKit<T> : half/bfloat16/int32/int8/uint8 FP32 中转
 *                             (half/bf16 单步 Cast；int32/int8/uint8 经 half 两步 Cast)
 *   - SeluGradOneDim<T, Kit>    : 连续分块搬运 + 多核切分
 *   - SeluGradBroadcast<T, Kit> : 多维 stride 偏移 + 内维分块逐行搬运
 *
 * 公式：
 *   y = SCALE * gradients                            if outputs >= 0
 *   y = gradients * (outputs + SCALE_ALPHA_PRODUCT)  if outputs < 0
 */

#ifndef SELU_GRAD_H
#define SELU_GRAD_H

#include "kernel_operator.h"
#include "kernel_tiling/kernel_tiling.h"
#include "selu_grad_tiling_data.h"
#include "selu_grad_tiling_key.h"

namespace NsSeluGrad {

using namespace AscendC;

// SELU 常量（FP32 精度）
constexpr float SCALE_F = 1.0507009873554804934193349852946f;
constexpr float SCALE_ALPHA_PRODUCT_F = 1.7580993408473768599402175208123f;

// 需要经 half 两步 Cast（int → half → float）的 dtype（DAV_3510 不支持 int↔float 直接 Cast）
template <typename T>
constexpr bool kNeedsHalfTransit = std::is_same_v<T, int32_t> || std::is_same_v<T, int8_t> ||
                                   std::is_same_v<T, uint8_t>;

// ============================================================================
// 公共自由函数：搬运参数 / 计算核 / Cast / 广播偏移
// ============================================================================

template <typename T>
__aicore__ inline DataCopyParams MakeCopyParams(int64_t count)
{
    DataCopyParams params;
    params.blockCount = 1;
    params.blockLen = count * sizeof(T);
    params.srcStride = 0;
    params.dstStride = 0;
    return params;
}

// SELU 反向核（FP32）。direct 路径 T==float 时同样复用此核。
// Iter3 Fix #1: 使用 float 常量做 Muls/Adds，避免 half 精度截断。
__aicore__ inline void SeluGradSelectFp32(const LocalTensor<float>& yFp32, const LocalTensor<float>& gradFp32,
                                          const LocalTensor<float>& outFp32, const LocalTensor<float>& branchA,
                                          const LocalTensor<float>& branchB, const LocalTensor<float>& tmp,
                                          const LocalTensor<uint8_t>& selMask, int64_t n)
{
    CompareScalar(selMask, outFp32, (float)0.0f, CMPMODE::LT, n);
    Muls(branchA, gradFp32, SCALE_F, n);
    Adds(tmp, outFp32, SCALE_ALPHA_PRODUCT_F, n);
    Mul(branchB, gradFp32, tmp, n);
    Select(yFp32, selMask, branchB, branchA, SELMODE::VSEL_TENSOR_TENSOR_MODE, n);
}

// 输入 Cast: T → float（整型经 half 两步，浮点单步）
template <typename T>
__aicore__ inline void SeluGradCastInToFp32(const LocalTensor<float>& gradFp32, const LocalTensor<float>& outFp32,
                                            const LocalTensor<T>& gradLocal, const LocalTensor<T>& outLocal,
                                            const LocalTensor<half>& gradHalf, const LocalTensor<half>& outHalf,
                                            int64_t n)
{
    if constexpr (kNeedsHalfTransit<T>) {
        Cast(gradHalf, gradLocal, RoundMode::CAST_NONE, n);
        Cast(outHalf, outLocal, RoundMode::CAST_NONE, n);
        Cast(gradFp32, gradHalf, RoundMode::CAST_NONE, n);
        Cast(outFp32, outHalf, RoundMode::CAST_NONE, n);
    } else {
        Cast(gradFp32, gradLocal, RoundMode::CAST_NONE, n);
        Cast(outFp32, outLocal, RoundMode::CAST_NONE, n);
    }
}

// 输出 Cast: float → T（整型经 half 两步，浮点单步），统一 CAST_RINT
template <typename T>
__aicore__ inline void SeluGradCastFp32ToOut(const LocalTensor<T>& yLocal, const LocalTensor<float>& yFp32,
                                             const LocalTensor<half>& yHalf, int64_t n)
{
    if constexpr (kNeedsHalfTransit<T>) {
        Cast(yHalf, yFp32, RoundMode::CAST_RINT, n);
        Cast(yLocal, yHalf, RoundMode::CAST_RINT, n);
    } else {
        Cast(yLocal, yFp32, RoundMode::CAST_RINT, n);
    }
}

// 广播路径：flatIdx → multiIdx 分解
__aicore__ inline void FlatIdxToMultiIdx(int64_t flatIdx, int32_t shapeLen, const int64_t* dims, int64_t* multiIdx)
{
    for (int32_t d = shapeLen - 1; d >= 0; d--) {
        if (dims[d] > 0) {
            multiIdx[d] = flatIdx % dims[d];
            flatIdx = flatIdx / dims[d];
        } else {
            multiIdx[d] = 0;
        }
    }
}

__aicore__ inline int64_t ComputeStrideOffset(int32_t shapeLen, const int64_t* multiIdx, const int64_t* strides)
{
    int64_t offset = 0;
    for (int32_t d = 0; d < shapeLen; d++) {
        offset += multiIdx[d] * strides[d];
    }
    return offset;
}

// 广播行的 GM 偏移与本块元素数（chunkOffset 已折入三个偏移）
struct RowGeom {
    int64_t gradOffset;
    int64_t outOffset;
    int64_t yOffset;
    int64_t count;
};

__aicore__ inline RowGeom ComputeRowGeom(int64_t rowIdx, int32_t chunkIdx, int64_t innerSize, int32_t shapeLen,
                                         int64_t innerChunkSize, const int64_t* outputDims, const int64_t* gradStrides,
                                         const int64_t* outStrides)
{
    int64_t flatIdx = rowIdx * innerSize;
    int64_t multiIdx[SELU_GRAD_MAX_DIM];
    FlatIdxToMultiIdx(flatIdx, shapeLen, outputDims, multiIdx);

    int64_t chunkOffset = (int64_t)chunkIdx * innerChunkSize;
    int64_t count = innerChunkSize;
    if (chunkOffset + count > innerSize) {
        count = innerSize - chunkOffset;
    }

    RowGeom geom;
    geom.gradOffset = ComputeStrideOffset(shapeLen, multiIdx, gradStrides) + chunkOffset;
    geom.outOffset = ComputeStrideOffset(shapeLen, multiIdx, outStrides) + chunkOffset;
    geom.yOffset = rowIdx * innerSize + chunkOffset;
    geom.count = count;
    return geom;
}

// ============================================================================
// 计算 Kit：封装计算所需缓冲与一次 (grad, out) -> y 的计算
// ============================================================================

// 直算 Kit（half/float；实际仅 float 实例化）
template <typename T>
struct SeluGradDirectKit {
    TQue<QuePosition::VECCALC, 1> branchAQueue, branchBQueue, tmpQueue, selMaskQueue;
    TBuf<TPosition::VECCALC> nanMaskBuf;

    __aicore__ inline void InitBufs(TPipe& pipe, int64_t n)
    {
        pipe.InitBuffer(branchAQueue, 1, n * sizeof(T));
        pipe.InitBuffer(branchBQueue, 1, n * sizeof(T));
        pipe.InitBuffer(tmpQueue, 1, n * sizeof(T));
        pipe.InitBuffer(selMaskQueue, 1, (n / 8) + 32);
        pipe.InitBuffer(nanMaskBuf, (n / 8) + 32);
    }

    __aicore__ inline void Compute(const LocalTensor<T>& gradLocal, const LocalTensor<T>& outLocal,
                                   const LocalTensor<T>& yLocal, int64_t n)
    {
        LocalTensor<T> branchA = branchAQueue.template AllocTensor<T>();
        LocalTensor<T> branchB = branchBQueue.template AllocTensor<T>();
        LocalTensor<T> tmp = tmpQueue.template AllocTensor<T>();
        LocalTensor<uint8_t> selMask = selMaskQueue.template AllocTensor<uint8_t>();

        SeluGradSelectFp32(yLocal, gradLocal, outLocal, branchA, branchB, tmp, selMask, n);

        branchAQueue.FreeTensor(branchA);
        branchBQueue.FreeTensor(branchB);
        tmpQueue.FreeTensor(tmp);
        selMaskQueue.FreeTensor(selMask);
    }
};

// FP32 中转 Kit（half/bfloat16/int32/int8/uint8）
template <typename T>
struct SeluGradTransitKit {
    TBuf<TPosition::VECCALC> gradHalfBuf, outHalfBuf, yHalfBuf;
    TBuf<TPosition::VECCALC> gradFp32Buf, outFp32Buf, branchABuf, branchBBuf, tmpBuf, yFp32Buf, maskBuf;

    __aicore__ inline void InitBufs(TPipe& pipe, int64_t n)
    {
        if constexpr (kNeedsHalfTransit<T>) {
            pipe.InitBuffer(gradHalfBuf, n * sizeof(half));
            pipe.InitBuffer(outHalfBuf, n * sizeof(half));
            if constexpr (!std::is_same_v<T, int8_t>) {
                pipe.InitBuffer(yHalfBuf, n * sizeof(half)); // int8 复用 outHalfBuf
            }
        }
        pipe.InitBuffer(gradFp32Buf, n * sizeof(float));
        pipe.InitBuffer(outFp32Buf, n * sizeof(float));
        pipe.InitBuffer(branchABuf, n * sizeof(float));
        pipe.InitBuffer(branchBBuf, n * sizeof(float));
        pipe.InitBuffer(tmpBuf, n * sizeof(float));
        pipe.InitBuffer(yFp32Buf, n * sizeof(float));
        pipe.InitBuffer(maskBuf, (n / 8) + 32);
    }

    __aicore__ inline void Compute(const LocalTensor<T>& gradLocal, const LocalTensor<T>& outLocal,
                                   const LocalTensor<T>& yLocal, int64_t n)
    {
        LocalTensor<float> gradFp32 = gradFp32Buf.template Get<float>();
        LocalTensor<float> outFp32 = outFp32Buf.template Get<float>();
        LocalTensor<float> branchA = branchABuf.template Get<float>();
        LocalTensor<float> branchB = branchBBuf.template Get<float>();
        LocalTensor<float> tmp = tmpBuf.template Get<float>();
        LocalTensor<uint8_t> selMask = maskBuf.template Get<uint8_t>();
        LocalTensor<float> yFp32 = yFp32Buf.template Get<float>();

        LocalTensor<half> gradHalf;
        LocalTensor<half> outHalf;
        LocalTensor<half> yHalf;
        if constexpr (kNeedsHalfTransit<T>) {
            gradHalf = gradHalfBuf.template Get<half>();
            outHalf = outHalfBuf.template Get<half>();
            if constexpr (std::is_same_v<T, int8_t>) {
                yHalf = outHalfBuf.template Get<half>();
            } else {
                yHalf = yHalfBuf.template Get<half>();
            }
        }

        SeluGradCastInToFp32<T>(gradFp32, outFp32, gradLocal, outLocal, gradHalf, outHalf, n);
        SeluGradSelectFp32(yFp32, gradFp32, outFp32, branchA, branchB, tmp, selMask, n);
        SeluGradCastFp32ToOut<T>(yLocal, yFp32, yHalf, n);
    }
};

// ============================================================================
// 驱动类：连续分块搬运（OneDim） / 多维广播逐行搬运（Broadcast）
// ============================================================================

template <typename T, typename Kit>
class SeluGradOneDim {
public:
    __aicore__ inline void Init(GM_ADDR gradients, GM_ADDR outputs, GM_ADDR y, const SeluGradTilingData* tilingData)
    {
        if (tilingData->totalElements == 0) {
            blockLen_ = 0;
            return;
        }
        int64_t blockOffset = tilingData->blockFormer * AscendC::GetBlockIdx();
        int64_t remainder = tilingData->totalElements - blockOffset;
        blockLen_ = (remainder > tilingData->blockFormer) ? tilingData->blockFormer : remainder;
        ubLen_ = tilingData->ubFormer;

        gradGM.SetGlobalBuffer((__gm__ T*)gradients + blockOffset, blockLen_);
        outGM.SetGlobalBuffer((__gm__ T*)outputs + blockOffset, blockLen_);
        yGM.SetGlobalBuffer((__gm__ T*)y + blockOffset, blockLen_);

        pipe.InitBuffer(gradQueue, 1, ubLen_ * sizeof(T));
        pipe.InitBuffer(outQueue, 1, ubLen_ * sizeof(T));
        pipe.InitBuffer(yQueue, 1, ubLen_ * sizeof(T));
        kit_.InitBufs(pipe, ubLen_);
    }

    __aicore__ inline void Process()
    {
        if (blockLen_ == 0) {
            return;
        }
        int64_t loopCount = (blockLen_ + ubLen_ - 1) / ubLen_;
        for (int64_t i = 0; i < loopCount; i++) {
            int64_t currentNum = (i == (loopCount - 1)) ? (blockLen_ - ubLen_ * i) : ubLen_;
            CopyIn(i, currentNum);
            Compute(currentNum);
            CopyOut(i, currentNum);
        }
    }

private:
    __aicore__ inline void CopyIn(int64_t progress, int64_t currentNum)
    {
        LocalTensor<T> gradLocal = gradQueue.template AllocTensor<T>();
        LocalTensor<T> outLocal = outQueue.template AllocTensor<T>();
        DataCopyParams copyParams = MakeCopyParams<T>(currentNum);
        DataCopyPad(gradLocal, gradGM[progress * ubLen_], copyParams, {false, 0, 0, 0});
        DataCopyPad(outLocal, outGM[progress * ubLen_], copyParams, {false, 0, 0, 0});
        gradQueue.EnQue(gradLocal);
        outQueue.EnQue(outLocal);
    }

    __aicore__ inline void Compute(int64_t currentNum)
    {
        LocalTensor<T> gradLocal = gradQueue.template DeQue<T>();
        LocalTensor<T> outLocal = outQueue.template DeQue<T>();
        LocalTensor<T> yLocal = yQueue.template AllocTensor<T>();
        kit_.Compute(gradLocal, outLocal, yLocal, currentNum);
        yQueue.template EnQue<T>(yLocal);
        gradQueue.FreeTensor(gradLocal);
        outQueue.FreeTensor(outLocal);
    }

    __aicore__ inline void CopyOut(int64_t progress, int64_t currentNum)
    {
        LocalTensor<T> yLocal = yQueue.template DeQue<T>();
        DataCopyParams copyParams = MakeCopyParams<T>(currentNum);
        DataCopyPad(yGM[progress * ubLen_], yLocal, copyParams);
        yQueue.FreeTensor(yLocal);
    }

    TPipe pipe;
    TQue<QuePosition::VECIN, 1> gradQueue, outQueue;
    TQue<QuePosition::VECOUT, 1> yQueue;
    GlobalTensor<T> gradGM, outGM, yGM;
    int64_t blockLen_ = 0;
    int64_t ubLen_ = 0;
    Kit kit_;
};

template <typename T, typename Kit>
class SeluGradBroadcast {
public:
    __aicore__ inline void Init(GM_ADDR gradients, GM_ADDR outputs, GM_ADDR y, const SeluGradTilingData* tilingData)
    {
        totalElements_ = tilingData->totalElements;
        if (totalElements_ == 0) {
            return;
        }
        innerSize_ = tilingData->innerSize;
        totalRows_ = tilingData->totalRows;
        shapeLen_ = tilingData->shapeLen;
        blockRows_ = tilingData->blockFormer;
        innerChunkSize_ = tilingData->innerChunkSize;
        numInnerChunks_ = tilingData->numInnerChunks;

        for (int32_t d = 0; d < shapeLen_; d++) {
            outputDims_[d] = tilingData->outputDims[d];
            gradStrides_[d] = tilingData->gradStrides[d];
            outStrides_[d] = tilingData->outStrides[d];
        }

        int64_t totalItems = totalRows_ * numInnerChunks_;
        startItem_ = (int64_t)AscendC::GetBlockIdx() * blockRows_;
        endItem_ = startItem_ + blockRows_;
        if (endItem_ > totalItems) {
            endItem_ = totalItems;
        }

        gradBase_ = (__gm__ T*)gradients;
        outBase_ = (__gm__ T*)outputs;
        yBase_ = (__gm__ T*)y;

        pipe.InitBuffer(gradQueue, 1, innerChunkSize_ * sizeof(T));
        pipe.InitBuffer(outQueue, 1, innerChunkSize_ * sizeof(T));
        pipe.InitBuffer(yQueue, 1, innerChunkSize_ * sizeof(T));
        kit_.InitBufs(pipe, innerChunkSize_);
    }

    __aicore__ inline void Process()
    {
        if (totalElements_ == 0) {
            return;
        }
        for (int64_t item = startItem_; item < endItem_; item++) {
            ProcessRow(item / numInnerChunks_, static_cast<int32_t>(item % numInnerChunks_));
        }
    }

private:
    __aicore__ inline void ProcessRow(int64_t rowIdx, int32_t chunkIdx)
    {
        RowGeom geom = ComputeRowGeom(rowIdx, chunkIdx, innerSize_, shapeLen_, innerChunkSize_, outputDims_,
                                      gradStrides_, outStrides_);
        gradGM.SetGlobalBuffer(gradBase_ + geom.gradOffset, geom.count);
        outGM.SetGlobalBuffer(outBase_ + geom.outOffset, geom.count);
        yGM.SetGlobalBuffer(yBase_ + geom.yOffset, geom.count);

        // CopyIn
        LocalTensor<T> gradLocal = gradQueue.template AllocTensor<T>();
        LocalTensor<T> outLocal = outQueue.template AllocTensor<T>();
        DataCopyParams copyParams = MakeCopyParams<T>(geom.count);
        DataCopyPad(gradLocal, gradGM, copyParams, {false, 0, 0, 0});
        DataCopyPad(outLocal, outGM, copyParams, {false, 0, 0, 0});
        gradQueue.EnQue(gradLocal);
        outQueue.EnQue(outLocal);

        // Compute
        gradLocal = gradQueue.template DeQue<T>();
        outLocal = outQueue.template DeQue<T>();
        LocalTensor<T> yLocal = yQueue.template AllocTensor<T>();
        kit_.Compute(gradLocal, outLocal, yLocal, geom.count);
        yQueue.template EnQue<T>(yLocal);
        gradQueue.FreeTensor(gradLocal);
        outQueue.FreeTensor(outLocal);

        // CopyOut
        yLocal = yQueue.template DeQue<T>();
        DataCopyPad(yGM, yLocal, MakeCopyParams<T>(geom.count));
        yQueue.FreeTensor(yLocal);
    }

    TPipe pipe;
    TQue<QuePosition::VECIN, 1> gradQueue, outQueue;
    TQue<QuePosition::VECOUT, 1> yQueue;
    GlobalTensor<T> gradGM, outGM, yGM;

    int64_t totalElements_ = 0;
    int64_t innerSize_ = 0;
    int64_t totalRows_ = 0;
    int64_t blockRows_ = 0;
    int32_t shapeLen_ = 0;
    int64_t innerChunkSize_ = 0;
    int32_t numInnerChunks_ = 0;

    int64_t outputDims_[SELU_GRAD_MAX_DIM];
    int64_t gradStrides_[SELU_GRAD_MAX_DIM];
    int64_t outStrides_[SELU_GRAD_MAX_DIM];

    int64_t startItem_ = 0;
    int64_t endItem_ = 0;

    __gm__ T* gradBase_;
    __gm__ T* outBase_;
    __gm__ T* yBase_;

    Kit kit_;
};

// dtype 调度别名：float 走 Direct，其余走 Transit
template <typename T>
using SeluGradOneDimOp = SeluGradOneDim<
    T, std::conditional_t<std::is_same_v<T, float>, SeluGradDirectKit<T>, SeluGradTransitKit<T>>>;

template <typename T>
using SeluGradBroadcastOp = SeluGradBroadcast<
    T, std::conditional_t<std::is_same_v<T, float>, SeluGradDirectKit<T>, SeluGradTransitKit<T>>>;

} // namespace NsSeluGrad

#endif // SELU_GRAD_H
