/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file foreach_div_list_simt.h
 * \brief SIMT kernel implementation for foreach_div_list operator.
 *        Sequential traversal of tensor pairs with per-pair VF_CALL.
 *        Workspace stores tensor metadata (addresses/element counts).
 *        bfloat16 path uses float32 intermediate computation via Simt API.
 */

#ifndef FOREACH_DIV_LIST_SIMT_H
#define FOREACH_DIV_LIST_SIMT_H

#include "kernel_operator.h"
#include "kernel_tiling/kernel_tiling.h"
#include "foreach_div_list_tiling_data.h"
#include "foreach_div_list_tiling_key.h"
#include "simt_api/asc_simt.h"
#include "simt_api/asc_bf16.h"
#include "simt_api/asc_fp16.h"

namespace NsForeachDivList {

using namespace AscendC;

static constexpr uint32_t THREAD_NUM = 512;

// ========== Helper: extract raw address from ListTensorDesc ==========

__aicore__ inline uint64_t GetListTensorAddrValue(
    GM_ADDR tensorListPtr, int64_t idx)
{
    __gm__ uint64_t* dataAddr = reinterpret_cast<__gm__ uint64_t*>(tensorListPtr);
    uint64_t tensorPtrOffset = *dataAddr;
    __gm__ uint64_t* tensorPtr = dataAddr + (tensorPtrOffset >> 3);
    return *(tensorPtr + idx);
}

// ========== Populate workspace with tensor metadata ==========

__aicore__ inline void PopulateWorkspace(
    GM_ADDR x1, GM_ADDR x2, GM_ADDR y,
    GM_ADDR workspace, const ForeachDivListTilingData* tilingData)
{
    __gm__ int64_t* ws = reinterpret_cast<__gm__ int64_t*>(workspace);
    int32_t tensorCount = tilingData->tensorCount;

    // Workspace layout (int64_t aligned):
    // ws[0]: tensorCount
    // ws[1..tensorCount]: elementCounts
    // ws[1+tensorCount..1+2*tensorCount]: x1Addrs
    // ws[1+2*tensorCount..1+3*tensorCount]: x2Addrs
    // ws[1+3*tensorCount..1+4*tensorCount]: yAddrs
    ws[0] = static_cast<int64_t>(tensorCount);

    __gm__ int64_t* elementCounts = ws + 1;
    __gm__ int64_t* x1Addrs = ws + 1 + tensorCount;
    __gm__ int64_t* x2Addrs = ws + 1 + 2 * tensorCount;
    __gm__ int64_t* yAddrs  = ws + 1 + 3 * tensorCount;

    for (int32_t i = 0; i < tensorCount; i++) {
        elementCounts[i] = tilingData->elementCounts[i];
        x1Addrs[i] = static_cast<int64_t>(GetListTensorAddrValue(x1, i));
        x2Addrs[i] = static_cast<int64_t>(GetListTensorAddrValue(x2, i));
        yAddrs[i]  = static_cast<int64_t>(GetListTensorAddrValue(y, i));
    }
}

// ========== SIMT VF: generic div (float16 / float32) ==========

template <typename T>
__simt_vf__ __aicore__ LAUNCH_BOUND(THREAD_NUM)
inline void ForeachDivListComputeSimt(
    int64_t elementCount,
    __gm__ T* x1, __gm__ T* x2, __gm__ T* y)
{
    for (uint64_t index = static_cast<uint64_t>(
            AscendC::Simt::GetBlockIdx() * THREAD_NUM + AscendC::Simt::GetThreadIdx());
         index < static_cast<uint64_t>(elementCount);
         index += static_cast<uint64_t>(THREAD_NUM * AscendC::Simt::GetBlockNum())) {
        // IEEE 754: 0/0=NaN, non-zero/0=Inf, NaN propagation
        y[index] = x1[index] / x2[index];
    }
}

// ========== SIMT VF: bfloat16 div (float32 intermediate) ==========

__simt_vf__ __aicore__ LAUNCH_BOUND(THREAD_NUM)
inline void ForeachDivListBf16ComputeSimt(
    int64_t elementCount,
    __gm__ bfloat16_t* x1, __gm__ bfloat16_t* x2, __gm__ bfloat16_t* y)
{
    for (uint64_t index = static_cast<uint64_t>(
            AscendC::Simt::GetBlockIdx() * THREAD_NUM + AscendC::Simt::GetThreadIdx());
         index < static_cast<uint64_t>(elementCount);
         index += static_cast<uint64_t>(THREAD_NUM * AscendC::Simt::GetBlockNum())) {
        bfloat16_t x1_val = x1[index];
        bfloat16_t x2_val = x2[index];
        // bfloat16 -> float32, compute division, float32 -> bfloat16
        float fx1 = __bfloat162float(x1_val);
        float fx2 = __bfloat162float(x2_val);
        float fresult = fx1 / fx2;
        y[index] = __float2bfloat16_rn(fresult);
    }
}

// ========== Process: float16 / float32 ==========

template <typename T>
__aicore__ inline void ProcessDiv(
    GM_ADDR workspace,
    const ForeachDivListTilingData* tilingData)
{
    __gm__ int64_t* ws = reinterpret_cast<__gm__ int64_t*>(workspace);
    int32_t tensorCount = tilingData->tensorCount;

    __gm__ int64_t* elementCounts = ws + 1;
    __gm__ int64_t* x1Addrs = ws + 1 + tensorCount;
    __gm__ int64_t* x2Addrs = ws + 1 + 2 * tensorCount;
    __gm__ int64_t* yAddrs  = ws + 1 + 3 * tensorCount;

    // Sequential traversal: iterate tensor pairs, call VF per pair
    for (int32_t i = 0; i < tensorCount; i++) {
        int64_t elemCount = elementCounts[i];
        if (elemCount == 0) { continue; }  // skip empty tensor

        __gm__ T* x1_gm = reinterpret_cast<__gm__ T*>(x1Addrs[i]);
        __gm__ T* x2_gm = reinterpret_cast<__gm__ T*>(x2Addrs[i]);
        __gm__ T* y_gm  = reinterpret_cast<__gm__ T*>(yAddrs[i]);

        AscendC::Simt::VF_CALL<ForeachDivListComputeSimt<T>>(
            AscendC::Simt::Dim3(THREAD_NUM), elemCount, x1_gm, x2_gm, y_gm);
    }
}

// ========== Process: bfloat16 ==========

__aicore__ inline void ProcessDivBf16(
    GM_ADDR workspace,
    const ForeachDivListTilingData* tilingData)
{
    __gm__ int64_t* ws = reinterpret_cast<__gm__ int64_t*>(workspace);
    int32_t tensorCount = tilingData->tensorCount;

    __gm__ int64_t* elementCounts = ws + 1;
    __gm__ int64_t* x1Addrs = ws + 1 + tensorCount;
    __gm__ int64_t* x2Addrs = ws + 1 + 2 * tensorCount;
    __gm__ int64_t* yAddrs  = ws + 1 + 3 * tensorCount;

    for (int32_t i = 0; i < tensorCount; i++) {
        int64_t elemCount = elementCounts[i];
        if (elemCount == 0) { continue; }

        __gm__ bfloat16_t* x1_gm = reinterpret_cast<__gm__ bfloat16_t*>(x1Addrs[i]);
        __gm__ bfloat16_t* x2_gm = reinterpret_cast<__gm__ bfloat16_t*>(x2Addrs[i]);
        __gm__ bfloat16_t* y_gm  = reinterpret_cast<__gm__ bfloat16_t*>(yAddrs[i]);

        AscendC::Simt::VF_CALL<ForeachDivListBf16ComputeSimt>(
            AscendC::Simt::Dim3(THREAD_NUM), elemCount, x1_gm, x2_gm, y_gm);
    }
}

} // namespace NsForeachDivList
#endif // FOREACH_DIV_LIST_SIMT_H