/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file softsign_tiling_arch35.cpp
 * \brief Softsign 算子 Host Tiling 实现（atvoss 框架 - Elewise 模式, arch35）
 *
 * Tiling 策略：
 * - FP32 (TilingKey=103): 直接计算，无 Cast
 * - FP16 (TilingKey=101): Cast→FP32→计算→Cast→FP16
 * - BF16 (TilingKey=102): Cast→FP32→计算→Cast→BF16
 */

#include "register/op_def_registry.h"
#include "op_common/log/log.h"
#include "atvoss/elewise/elewise_tiling.h"
#include "../../op_kernel/arch35/softsign_dag.h"
#include "../../op_kernel/arch35/softsign_struct.h"

namespace optiling {

using namespace ge;
using Ops::Base::bfloat16_t;
using Ops::Base::ElewiseBaseTiling;
using Ops::Base::half;

// TilingKey 定义（与 DESIGN.md §3.1 一致）
constexpr uint64_t TILING_KEY_FP16 = 101UL;
constexpr uint64_t TILING_KEY_BF16 = 102UL;
constexpr uint64_t TILING_KEY_FP32 = 103UL;

static ge::graphStatus DoTilingByDtype(gert::TilingContext* context, ge::DataType dtype, SoftsignTilingData* tilingData,
                                       uint64_t& tilingKey)
{
    ElewiseBaseTiling eleTiling(context);
    ge::graphStatus ret;
    if (dtype == ge::DT_FLOAT) {
        using OpDag = SoftsignOp::GraphSoftsign<float, float>::OpDag;
        ret = eleTiling.DoTiling<OpDag>(tilingData->baseTiling);
        tilingKey = TILING_KEY_FP32;
    } else if (dtype == ge::DT_FLOAT16) {
        using OpDag = SoftsignOp::GraphSoftsign<half, float>::OpDag;
        ret = eleTiling.DoTiling<OpDag>(tilingData->baseTiling);
        tilingKey = TILING_KEY_FP16;
    } else if (dtype == ge::DT_BF16) {
        using OpDag = SoftsignOp::GraphSoftsign<bfloat16_t, float>::OpDag;
        ret = eleTiling.DoTiling<OpDag>(tilingData->baseTiling);
        tilingKey = TILING_KEY_BF16;
    } else {
        OP_LOGE(context, "Softsign: unsupported dtype=%d", static_cast<int>(dtype));
        return ge::GRAPH_FAILED;
    }
    OP_CHECK_IF(ret != ge::GRAPH_SUCCESS,
                OP_LOGE(context, "Softsign: DoTiling failed for dtype=%d", static_cast<int>(dtype)), return ret);
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus PrepareWorkspace(gert::TilingContext* context)
{
    constexpr uint64_t WORKSPACE_RESERVE_BYTE = 16UL * 1024 * 1024;
    size_t* currentWorkspace = context->GetWorkspaceSizes(1);
    OP_CHECK_NULL_WITH_CONTEXT(context, currentWorkspace);
    currentWorkspace[0] = WORKSPACE_RESERVE_BYTE;
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus SoftsignTilingFunc(gert::TilingContext* context)
{
    auto inputDesc = context->GetInputDesc(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, inputDesc);
    ge::DataType dtype = inputDesc->GetDataType();

    auto inputShape = context->GetInputShape(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, inputShape);
    auto storageShape = inputShape->GetStorageShape();
    int64_t dim0 = (storageShape.GetDimNum() == 0) ? 1 : storageShape.GetShapeSize();

    OP_CHECK_IF(PrepareWorkspace(context) != ge::GRAPH_SUCCESS, OP_LOGE(context, "Softsign: PrepareWorkspace failed"),
                return ge::GRAPH_FAILED);

    if (dim0 == 0) {
        context->SetBlockDim(1);
        context->SetTilingKey(TILING_KEY_FP32);
        return ge::GRAPH_SUCCESS;
    }

    uint64_t tilingKey = 0;
    auto tilingData = context->GetTilingData<SoftsignTilingData>();
    OP_CHECK_NULL_WITH_CONTEXT(context, tilingData);
    auto ret = DoTilingByDtype(context, dtype, tilingData, tilingKey);
    OP_CHECK_IF(ret != ge::GRAPH_SUCCESS, OP_LOGE(context, "Softsign: DoTilingByDtype failed"), return ret);

    context->SetTilingKey(tilingKey);
    context->SetBlockDim(tilingData->baseTiling.blockNum);
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus TilingParseForSoftsign([[maybe_unused]] gert::TilingParseContext* context)
{
    return ge::GRAPH_SUCCESS;
}

struct SoftsignCompileInfo {};

IMPL_OP_OPTILING(Softsign).Tiling(SoftsignTilingFunc).TilingParse<SoftsignCompileInfo>(TilingParseForSoftsign);

} // namespace optiling
