/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/*!
 * \file foreach_copy_tiling_key.h
 * \brief tiling key definitions for foreach_copy operator
 */

#ifndef FOREACH_COPY_TILING_KEY_H
#define FOREACH_COPY_TILING_KEY_H

#include "ascendc/host_api/tiling/template_argument.h"

#define FOREACH_COPY_TPL_SCH_MODE_HALF_TO_HALF 0
#define FOREACH_COPY_TPL_SCH_MODE_FLOAT_TO_FLOAT 1
#define FOREACH_COPY_TPL_SCH_MODE_INT32_TO_INT32 2
#define FOREACH_COPY_TPL_SCH_MODE_BF16_TO_BF16 3
#define FOREACH_COPY_TPL_SCH_MODE_UINT8_TO_UINT8 4
#define FOREACH_COPY_TPL_SCH_MODE_UINT32_TO_UINT32 5
#define FOREACH_COPY_TPL_SCH_MODE_INT16_TO_INT16 6
#define FOREACH_COPY_TPL_SCH_MODE_UINT16_TO_UINT16 7
#define FOREACH_COPY_TPL_SCH_MODE_INT8_TO_INT8 8
#define FOREACH_COPY_TPL_SCH_MODE_BOOL_TO_BOOL 9
#define FOREACH_COPY_TPL_SCH_MODE_INT64_TO_INT64 10
#define FOREACH_COPY_TPL_SCH_MODE_DOUBLE_TO_DOUBLE 11
#define FOREACH_COPY_TPL_SCH_MODE_FLOAT_TO_BF16 12
#define FOREACH_COPY_TPL_SCH_MODE_FLOAT_TO_HALF 13
#define FOREACH_COPY_TPL_SCH_MODE_HALF_TO_FLOAT 14
#define FOREACH_COPY_TPL_SCH_MODE_BF16_TO_FLOAT 15

ASCENDC_TPL_ARGS_DECL(
    ForeachCopy,
    ASCENDC_TPL_UINT_DECL(schMode, 16, ASCENDC_TPL_UI_LIST, FOREACH_COPY_TPL_SCH_MODE_HALF_TO_HALF,
                          FOREACH_COPY_TPL_SCH_MODE_FLOAT_TO_FLOAT, FOREACH_COPY_TPL_SCH_MODE_INT32_TO_INT32,
                          FOREACH_COPY_TPL_SCH_MODE_BF16_TO_BF16, FOREACH_COPY_TPL_SCH_MODE_UINT8_TO_UINT8,
                          FOREACH_COPY_TPL_SCH_MODE_UINT32_TO_UINT32, FOREACH_COPY_TPL_SCH_MODE_INT16_TO_INT16,
                          FOREACH_COPY_TPL_SCH_MODE_UINT16_TO_UINT16, FOREACH_COPY_TPL_SCH_MODE_INT8_TO_INT8,
                          FOREACH_COPY_TPL_SCH_MODE_BOOL_TO_BOOL, FOREACH_COPY_TPL_SCH_MODE_INT64_TO_INT64,
                          FOREACH_COPY_TPL_SCH_MODE_DOUBLE_TO_DOUBLE, FOREACH_COPY_TPL_SCH_MODE_FLOAT_TO_BF16,
                          FOREACH_COPY_TPL_SCH_MODE_FLOAT_TO_HALF, FOREACH_COPY_TPL_SCH_MODE_HALF_TO_FLOAT,
                          FOREACH_COPY_TPL_SCH_MODE_BF16_TO_FLOAT));

ASCENDC_TPL_SEL(ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_UINT_SEL(
    schMode, ASCENDC_TPL_UI_LIST, FOREACH_COPY_TPL_SCH_MODE_HALF_TO_HALF, FOREACH_COPY_TPL_SCH_MODE_FLOAT_TO_FLOAT,
    FOREACH_COPY_TPL_SCH_MODE_INT32_TO_INT32, FOREACH_COPY_TPL_SCH_MODE_BF16_TO_BF16,
    FOREACH_COPY_TPL_SCH_MODE_UINT8_TO_UINT8, FOREACH_COPY_TPL_SCH_MODE_UINT32_TO_UINT32,
    FOREACH_COPY_TPL_SCH_MODE_INT16_TO_INT16, FOREACH_COPY_TPL_SCH_MODE_UINT16_TO_UINT16,
    FOREACH_COPY_TPL_SCH_MODE_INT8_TO_INT8, FOREACH_COPY_TPL_SCH_MODE_BOOL_TO_BOOL,
    FOREACH_COPY_TPL_SCH_MODE_INT64_TO_INT64, FOREACH_COPY_TPL_SCH_MODE_DOUBLE_TO_DOUBLE,
    FOREACH_COPY_TPL_SCH_MODE_FLOAT_TO_BF16, FOREACH_COPY_TPL_SCH_MODE_FLOAT_TO_HALF,
    FOREACH_COPY_TPL_SCH_MODE_HALF_TO_FLOAT, FOREACH_COPY_TPL_SCH_MODE_BF16_TO_FLOAT)));

#endif // FOREACH_COPY_TILING_KEY_H
