/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/*!
 * \file fused_bias_leaky_relu_grad_infershape.cpp
 * \brief InferShape for FusedBiasLeakyReluGrad (Broadcast)
 * Generated By CANNBot
 */
#include "register/op_impl_registry.h"

using namespace ge;

namespace ops {

static ge::graphStatus InferShapeFusedBiasLeakyReluGrad(gert::InferShapeContext *context)
{
    const gert::Shape *shape0 = context->GetInputShape(0);
    const gert::Shape *shape1 = context->GetInputShape(1);
    gert::Shape *outShape = context->GetOutputShape(0);
    if (shape0 == nullptr || shape1 == nullptr || outShape == nullptr) {
        return ge::GRAPH_FAILED;
    }

    // Broadcast: output shape = broadcast(y_grad.shape, features.shape)
    size_t rank0 = shape0->GetDimNum();
    size_t rank1 = shape1->GetDimNum();
    size_t outRank = (rank0 > rank1) ? rank0 : rank1;
    outShape->SetDimNum(outRank);

    for (size_t i = 0; i < outRank; ++i) {
        int64_t d0 = 1;
        int64_t d1 = 1;
        if (i < rank0) {
            d0 = shape0->GetDim(rank0 - 1 - i);
        }
        if (i < rank1) {
            d1 = shape1->GetDim(rank1 - 1 - i);
        }
        int64_t outDim;
        if (d0 == d1) {
            outDim = d0;
        } else if (d0 == 1) {
            outDim = d1;
        } else if (d1 == 1) {
            outDim = d0;
        } else {
            // Incompatible shapes
            return ge::GRAPH_FAILED;
        }
        outShape->SetDim(outRank - 1 - i, outDim);
    }
    return ge::GRAPH_SUCCESS;
}

IMPL_OP_INFERSHAPE(FusedBiasLeakyReluGrad).InferShape(InferShapeFusedBiasLeakyReluGrad);

}  // namespace ops
