/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/**
 * NOTE: Portions of this code were AI-generated and have been
 * technically reviewed for functional accuracy and security
 * Generated By CANNBot
 */

/*!
 * \file apply_adagrad_dad.h
 * \brief ApplyAdagradDAD kernel header (arch35 / DAV_3510)
 *
 * Forwards tiling_data.h and tiling_key.h includes. The kernel implementation
 * (class-style ApplyAdagradDADKernel) is self-contained in apply_adagrad_dad.cpp.
 */

#ifndef APPLY_ADAGRAD_DAD_H
#define APPLY_ADAGRAD_DAD_H

#include "apply_adagrad_dad_tiling_data.h"
#include "apply_adagrad_dad_tiling_key.h"

#endif // APPLY_ADAGRAD_DAD_H
