/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file foreach_tanh.cpp
 * \brief kernel entry for foreach_tanh (arch35)
 */

#include "foreach_tanh_simt.h"

enum class ForeachTanhTilingKey : uint32_t
{
    TILING_KEY_FLOAT   = 0,
    TILING_KEY_FLOAT16 = 1,
    TILING_KEY_BF16    = 2,
};

template <uint32_t schMode>
__global__ __aicore__ void foreach_tanh(GM_ADDR x, GM_ADDR y, GM_ADDR workspace, GM_ADDR tiling)
{
    REGISTER_TILING_DEFAULT(ForeachTanhTilingData);
    GET_TILING_DATA_WITH_STRUCT(ForeachTanhTilingData, tilingData, tiling);

    if constexpr (schMode == static_cast<uint32_t>(
            ForeachTanhTilingKey::TILING_KEY_FLOAT)) {
        NsForeachTanh::Process<float>(x, y, &tilingData);
    } else if constexpr (schMode == static_cast<uint32_t>(
            ForeachTanhTilingKey::TILING_KEY_FLOAT16)) {
        NsForeachTanh::Process<half>(x, y, &tilingData);
    } else if constexpr (schMode == static_cast<uint32_t>(
            ForeachTanhTilingKey::TILING_KEY_BF16)) {
        NsForeachTanh::Process<bfloat16_t>(x, y, &tilingData);
    }
}