/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* !
 * \file dual_level_quant_batch_matmul_tiling_key.h
 * \brief
 */

#ifndef DUAL_LEVEL_QUANT_BATCH_MATMUL_TILING_KEY_H
#define DUAL_LEVEL_QUANT_BATCH_MATMUL_TILING_KEY_H

#include "ascendc/host_api/tiling/template_argument.h"

#define DLQBMM_SOC_RESERVERD 0 // 平台大类
#define DLQBMM_SOC_SUPPORT_L0C_TO_OUT 1

#define DLQBMM_DEFAULT 0 // 平台小类

#define DLQBMM_TEMPLATE_CUBEBOUND 0 // 模板类型

#define DLQBMM_QUANT_TYPE_NONE 0 // 量化类型
#define DLQBMM_QUANT_TYPE_PER_TENSOR 1
#define DLQBMM_QUANT_TYPE_PER_CHANNEL 2
#define DLQBMM_QUANT_TYPE_PER_GROUP 3
#define DLQBMM_QUANT_TYPE_MX 4

#define DLQBMM_WEIGHT_ND 0 // weight数据格式
#define DLQBMM_WEIGHT_FRACTAL_NZ 1

#define PLACEHOLDER_0 0 // placehoder
#define PLACEHOLDER_1 1
#define PLACEHOLDER_2 2
#define PLACEHOLDER_3 3
#define PLACEHOLDER_4 4
#define PLACEHOLDER_5 5

ASCENDC_TPL_ARGS_DECL(
    DualLevelQuantBatchMatmul,
    ASCENDC_TPL_UINT_DECL( // 平台大类
        SOC_VERSION_TYPE, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST, DLQBMM_SOC_RESERVERD, DLQBMM_SOC_SUPPORT_L0C_TO_OUT),
    ASCENDC_TPL_UINT_DECL( // 平台小类
        SUB_SOC_VERSION_TYPE, ASCENDC_TPL_2_BW, ASCENDC_TPL_UI_LIST, DLQBMM_DEFAULT),
    ASCENDC_TPL_UINT_DECL( // 模板类型
        TEMPLATE_CUSTOM, ASCENDC_TPL_8_BW, ASCENDC_TPL_UI_LIST, DLQBMM_TEMPLATE_CUBEBOUND),
    ASCENDC_TPL_UINT_DECL( // level1量化类型
        LEVEL1_QUANT_TYPE, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST, DLQBMM_QUANT_TYPE_NONE, DLQBMM_QUANT_TYPE_PER_TENSOR,
        DLQBMM_QUANT_TYPE_PER_CHANNEL, DLQBMM_QUANT_TYPE_PER_GROUP, DLQBMM_QUANT_TYPE_MX),
    ASCENDC_TPL_UINT_DECL( // level0量化类型
        LEVEL0_QUANT_TYPE, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST, DLQBMM_QUANT_TYPE_NONE, DLQBMM_QUANT_TYPE_PER_TENSOR,
        DLQBMM_QUANT_TYPE_PER_CHANNEL, DLQBMM_QUANT_TYPE_PER_GROUP, DLQBMM_QUANT_TYPE_MX),
    ASCENDC_TPL_BOOL_DECL( // 转置场景
        TRANS_A, 0, 1),
    ASCENDC_TPL_BOOL_DECL( // 转置场景
        TRANS_B, 0, 1),
    ASCENDC_TPL_BOOL_DECL( // 可选输入
        HAS_BIAS, 0, 1),
    ASCENDC_TPL_BOOL_DECL( // weight的格式
        IS_WEIGHT_NZ, 0, 1), );

ASCENDC_TPL_SEL(
    ASCENDC_TPL_ARGS_SEL(
        ASCENDC_TPL_UINT_SEL(SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, DLQBMM_SOC_RESERVERD),
        ASCENDC_TPL_UINT_SEL(SUB_SOC_VERSION_TYPE, ASCENDC_TPL_UI_LIST, DLQBMM_DEFAULT),
        ASCENDC_TPL_UINT_SEL(TEMPLATE_CUSTOM, ASCENDC_TPL_UI_LIST, DLQBMM_TEMPLATE_CUBEBOUND),
        ASCENDC_TPL_UINT_SEL(LEVEL1_QUANT_TYPE, ASCENDC_TPL_UI_LIST, DLQBMM_QUANT_TYPE_MX),
        ASCENDC_TPL_UINT_SEL(LEVEL0_QUANT_TYPE, ASCENDC_TPL_UI_LIST, DLQBMM_QUANT_TYPE_PER_GROUP),
        ASCENDC_TPL_BOOL_SEL(TRANS_A, 0), ASCENDC_TPL_BOOL_SEL(TRANS_B, 1), ASCENDC_TPL_BOOL_SEL(HAS_BIAS, 0, 1),
        ASCENDC_TPL_BOOL_SEL(IS_WEIGHT_NZ, 1), ), );

#endif // DUAL_LEVEL_QUANT_BATCH_MATMUL_TILING_KEY_H
