/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/**
 * NOTE: Portions of this code were AI-generated and have been
 * technically reviewed for functional accuracy and security
 * Generated By CANNBot
 */

/*!
 * \file apply_adagrad_v2d_def.cpp
 * \brief ApplyAdagradV2d 算子定义（输入输出、dtype、format 配置）
 *
 * 对齐 CANNDEV ApplyAdagradV2D：2 输出（var, accum），仅支持 FLOAT。
 * lr 为标量 Tensor 输入，kernel 从 GM_ADDR 运行时读取（CACHE-SAFE）。
 * epsilon 为 REQUIRED_ATTR(Float)，存入 TilingData。
 *
 * 输入：var, accum, lr, grad（lr 为标量 Tensor, shape=[]）
 * 输出：var, accum（shape/dtype 与输入一致）
 * 属性：epsilon(float), update_slots(bool), use_locking(bool)
 */

#include "register/op_def_registry.h"

namespace ops {
class ApplyAdagradV2d : public OpDef {
public:
    explicit ApplyAdagradV2d(const char* name) : OpDef(name)
    {
        this->Input("var")
            .ParamType(REQUIRED)
            .DataType({ge::DT_FLOAT})
            .Format({ge::FORMAT_ND})
            .UnknownShapeFormat({ge::FORMAT_ND})
            .AutoContiguous();

        this->Input("accum")
            .ParamType(REQUIRED)
            .DataType({ge::DT_FLOAT})
            .Format({ge::FORMAT_ND})
            .UnknownShapeFormat({ge::FORMAT_ND})
            .AutoContiguous();

        // lr: 标量 Tensor (shape=[])，CACHE-SAFE 设计：kernel 从 GM_ADDR 读取
        this->Input("lr")
            .ParamType(REQUIRED)
            .DataType({ge::DT_FLOAT})
            .Format({ge::FORMAT_ND})
            .UnknownShapeFormat({ge::FORMAT_ND})
            .AutoContiguous();

        this->Input("grad")
            .ParamType(REQUIRED)
            .DataType({ge::DT_FLOAT})
            .Format({ge::FORMAT_ND})
            .UnknownShapeFormat({ge::FORMAT_ND})
            .AutoContiguous();

        // 输出：var（shape/dtype 与输入 var 一致）
        this->Output("var")
            .ParamType(REQUIRED)
            .DataType({ge::DT_FLOAT})
            .Format({ge::FORMAT_ND})
            .UnknownShapeFormat({ge::FORMAT_ND})
            .AutoContiguous();

        // 输出：accum（shape/dtype 与输入 accum 一致）
        this->Output("accum")
            .ParamType(REQUIRED)
            .DataType({ge::DT_FLOAT})
            .Format({ge::FORMAT_ND})
            .UnknownShapeFormat({ge::FORMAT_ND})
            .AutoContiguous();

        // 属性顺序对齐 CANNDEV ApplyAdagradV2D：epsilon(0), update_slots(1), use_locking(2)
        this->Attr("epsilon").Float();
        this->Attr("update_slots").Bool(true);
        this->Attr("use_locking").Bool(false);

        OpAICoreConfig aiCoreConfig;
        aiCoreConfig.DynamicCompileStaticFlag(true)
            .DynamicFormatFlag(false)
            .DynamicRankSupportFlag(true)
            .DynamicShapeSupportFlag(true)
            .NeedCheckSupportFlag(false)
            .PrecisionReduceFlag(true)
            .ExtendCfgInfo("opFile.value", "apply_adagrad_v2d");
        this->AICore().AddConfig("ascend950", aiCoreConfig);
    }
};
OP_ADD(ApplyAdagradV2d);
} // namespace ops
