/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 *
 * Generated By CANNBot
 */


/**
 * NOTE: Portions of this code were AI-generated and have been
 * technically reviewed for functional accuracy and security
 */
/*!
 * \file apply_adadelta_def.cpp
 * \brief ApplyAdadelta 算子定义（对齐 canndev REG_OP(ApplyAdadelta)）
 *
 * 输入 (7): var, accum, accum_update, lr, rho, epsilon, grad
 * 输出 (1): var（accum / accum_update 通过 inplace 语义随输入 GM 地址更新，无显式输出端口）
 * 属性 (1): use_locking (bool, default=false, 语义占位)
 *
 * 仅适配 Ascend950 (arch35 / DAV_3510)。
 */
#include "register/op_def_registry.h"

namespace ops {
class ApplyAdadelta : public OpDef {
public:
    explicit ApplyAdadelta(const char* name) : OpDef(name)
    {
        // 张量输入 (Tensor shape = var shape)
        this->Input("var")
            .ParamType(REQUIRED)
            .DataType({ge::DT_FLOAT, ge::DT_FLOAT16})
            .Format({ge::FORMAT_ND, ge::FORMAT_ND})
            .UnknownShapeFormat({ge::FORMAT_ND, ge::FORMAT_ND})
            .AutoContiguous();
        this->Input("accum")
            .ParamType(REQUIRED)
            .DataType({ge::DT_FLOAT, ge::DT_FLOAT16})
            .Format({ge::FORMAT_ND, ge::FORMAT_ND})
            .UnknownShapeFormat({ge::FORMAT_ND, ge::FORMAT_ND})
            .AutoContiguous();
        this->Input("accum_update")
            .ParamType(REQUIRED)
            .DataType({ge::DT_FLOAT, ge::DT_FLOAT16})
            .Format({ge::FORMAT_ND, ge::FORMAT_ND})
            .UnknownShapeFormat({ge::FORMAT_ND, ge::FORMAT_ND})
            .AutoContiguous();

        // 标量输入 (shape = [1])
        this->Input("lr")
            .ParamType(REQUIRED)
            .DataType({ge::DT_FLOAT, ge::DT_FLOAT16})
            .Format({ge::FORMAT_ND, ge::FORMAT_ND})
            .UnknownShapeFormat({ge::FORMAT_ND, ge::FORMAT_ND})
            .AutoContiguous();
        this->Input("rho")
            .ParamType(REQUIRED)
            .DataType({ge::DT_FLOAT, ge::DT_FLOAT16})
            .Format({ge::FORMAT_ND, ge::FORMAT_ND})
            .UnknownShapeFormat({ge::FORMAT_ND, ge::FORMAT_ND})
            .AutoContiguous();
        this->Input("epsilon")
            .ParamType(REQUIRED)
            .DataType({ge::DT_FLOAT, ge::DT_FLOAT16})
            .Format({ge::FORMAT_ND, ge::FORMAT_ND})
            .UnknownShapeFormat({ge::FORMAT_ND, ge::FORMAT_ND})
            .AutoContiguous();
        this->Input("grad")
            .ParamType(REQUIRED)
            .DataType({ge::DT_FLOAT, ge::DT_FLOAT16})
            .Format({ge::FORMAT_ND, ge::FORMAT_ND})
            .UnknownShapeFormat({ge::FORMAT_ND, ge::FORMAT_ND})
            .AutoContiguous();

        // 输出 (单输出 var；accum / accum_update 通过 inplace 语义随输入 GM 地址更新)
        this->Output("var")
            .ParamType(REQUIRED)
            .DataType({ge::DT_FLOAT, ge::DT_FLOAT16})
            .Format({ge::FORMAT_ND, ge::FORMAT_ND})
            .UnknownShapeFormat({ge::FORMAT_ND, ge::FORMAT_ND})
            .AutoContiguous();

        // 属性 (use_locking, 语义占位)
        this->Attr("use_locking").AttrType(OPTIONAL).Bool(false);

        // Ascend950 (arch35) 配置
        OpAICoreConfig aicoreConfig;
        aicoreConfig.DynamicCompileStaticFlag(true)
            .DynamicFormatFlag(false)
            .DynamicRankSupportFlag(true)
            .DynamicShapeSupportFlag(true)
            .NeedCheckSupportFlag(false)
            .PrecisionReduceFlag(true)
            // opFile.value 用于 CANN 构建期定位 cpp 文件（apply_adadelta.cpp），
            // kernel 函数符号则按 OpType 'ApplyAdadelta' 的 snake_case 'apply_adadelta' 绑定，两条链路独立。
            // GE IR 端到端验证已确认 CANN runtime 正确绑定。
            // 目录/文件名 'apply_adadelta' 与 ops-nn 仓 optim/ 现有命名约定一致。
            .ExtendCfgInfo("opFile.value", "apply_adadelta");
        this->AICore().AddConfig("ascend950", aicoreConfig);
    }
};
OP_ADD(ApplyAdadelta);
} // namespace ops
