/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file foreach_addcmul_scalar_list_tiling_arch22.cpp
 * \brief Tiling for ForeachAddcmulScalarList on arch22 (ascend910b/910_93/kirin etc.).
 *        Uses ForeachCommonTiling with FOREACH_POINTWISE_OP_CODE and scalar-list input type.
 */

#include "../../../foreach_utils/op_host/foreach_tiling_class.h"

namespace optiling {

static ge::graphStatus Tiling4ForeachAddcmulScalarListTiling(gert::TilingContext* context)
{
    ForeachCommonTiling tilingObject(context);
    if (tilingObject.Init(FOREACH_POINTWISE_OP_CODE, ForeachInputType::TYPE_SCALARS_TENSOR) != ge::GRAPH_SUCCESS) {
        return ge::GRAPH_FAILED;
    }
    return tilingObject.RunBigKernelTiling();
}

static ge::graphStatus TilingPrepare4ForeachTiling([[maybe_unused]] gert::TilingParseContext* context)
{
    return ge::GRAPH_SUCCESS;
}

IMPL_OP_OPTILING(ForeachAddcmulScalarList)
    .Tiling(Tiling4ForeachAddcmulScalarListTiling)
    .TilingParse<ForeachCompileInfo>(TilingPrepare4ForeachTiling);

} // namespace optiling
