/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/**
 * NOTE: Portions of this code were AI-generated and have been
 * technically reviewed for functional accuracy and security
 * Generated By CANNBot
 */

/*!
 * \file apply_adagrad_dad_tiling_arch35.cpp
 * \brief Host-side Tiling function for ApplyAdagradDAD (arch35)
 *
 * CACHE-SAFE DESIGN: TilingData only contains shape-related fields.
 * Scalar values (lr, l1, l2, global_step) are NOT stored in TilingData;
 * the kernel reads them directly from GM_ADDR (device memory).
 *
 * Responsibilities:
 *   1. Read input shape/dtype
 *   2. Compute TilingKey (based on var dtype)
 *   3. Compute TilingData (totalElements, chunkSize, globalStepDtype)
 *   4. Empty tensor early return
 */

#include "register/op_def_registry.h"
#include "op_common/log/log.h"
#include "op_common/op_host/util/math_util.h"
#include "op_common/op_host/util/platform_util.h"
#include "../../op_kernel/arch35/apply_adagrad_dad_tiling_data.h"
#include "../../op_kernel/arch35/apply_adagrad_dad_tiling_key.h"

#include <cstring>

namespace optiling {

using Ops::Base::CeilDiv;

constexpr uint32_t WS_SYS_SIZE = 0U;
constexpr size_t WORKSPACE_NUM = 1;

// 输入索引（var=0, gradient_accumulator=1, gradient_squared_accumulator=2, grad=3,
//            lr=4, l1=5, l2=6, global_step=7）
constexpr uint32_t GLOBAL_STEP_INPUT_INDEX = 7;

// chunkSize constants (derived from UB budget, 256B aligned)
// UB 布局：
//   FP32: 3 VECIN + 3 VECOUT = 6 × chunkSize × 4B
//   FP16: 3 VECIN(2B) + 3 VECOUT(2B) + 4 TBuf(4B) + 1 scratch(4B) = 32B/elem
constexpr uint32_t CHUNK_SIZE_FP32 = 7680U;      // 6 * 7680 * 4 = 184320 B (< 192KB)
constexpr uint32_t CHUNK_SIZE_FP16 = 5632U;  // (6*2 + 5*4) * 5632 = 180224 B (< 192KB)

static const gert::Shape g_vec_1_shape = {1};

static inline const gert::Shape EnsureNotScalar(const gert::Shape& in_shape)
{
    if (in_shape.GetDimNum() == 0) {
        return g_vec_1_shape;
    }
    return in_shape;
}

// Get platform info (ubSize, coreNum)
static ge::graphStatus GetPlatformInfo(gert::TilingContext* context, uint64_t* ubSize, int64_t* coreNum)
{
    fe::PlatFormInfos* platformInfoPtr = context->GetPlatformInfo();
    OP_CHECK_NULL_WITH_CONTEXT(context, platformInfoPtr);
    auto ascendcPlatform = platform_ascendc::PlatformAscendC(platformInfoPtr);
    *coreNum = ascendcPlatform.GetCoreNumAiv();
    OP_CHECK_IF(*coreNum == 0, OP_LOGE(context, "coreNum is 0"), return ge::GRAPH_FAILED);
    ascendcPlatform.GetCoreMemSize(platform_ascendc::CoreMemType::UB, *ubSize);
    OP_CHECK_IF(*ubSize == 0, OP_LOGE(context, "ubSize is 0"), return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

// Workspace declaration (even if size=0, must declare the slot)
static ge::graphStatus GetWorkspaceSize(gert::TilingContext* context)
{
    size_t* currentWorkspace = context->GetWorkspaceSizes(WORKSPACE_NUM);
    OP_CHECK_NULL_WITH_CONTEXT(context, currentWorkspace);
    currentWorkspace[0] = WS_SYS_SIZE;
    return ge::GRAPH_SUCCESS;
}

// Compute chunkSize and multi-core partitioning (steps 7-8).
// NOTE: step 6 (global_step dtype retrieval + null check) stays in the main
// tiling function because OP_CHECK_NULL_WITH_CONTEXT returns ge::GRAPH_FAILED,
// which is incompatible with a void return type.
static void ComputeTilingParams(int64_t totalElements, ge::DataType dataType,
                                int64_t coreNum, uint32_t* chunkSize, int64_t* usedCoreNum)
{
    // Compute chunkSize based on dtype
    if (dataType == ge::DT_FLOAT) {
        *chunkSize = CHUNK_SIZE_FP32;
    } else {
        *chunkSize = CHUNK_SIZE_FP16;
    }

    // Multi-core partitioning
    *usedCoreNum = CeilDiv(totalElements, static_cast<int64_t>(*chunkSize));
    if (*usedCoreNum > coreNum) {
        *usedCoreNum = coreNum;
    }
}

// Get input shape, validate tensor/scalar shapes, and retrieve dtype.
// Returns GRAPH_FAILED on validation error.
static ge::graphStatus GetShapeAndValidate(gert::TilingContext* context,
                                           int64_t* totalElements, ge::DataType* dataType)
{
    auto varInput = context->GetInputShape(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, varInput);
    auto varShape = EnsureNotScalar(varInput->GetStorageShape());
    *totalElements = varShape.GetShapeSize();

    // 校验 tensor 输入与 var 同 shape (gAcc=1, ggAcc=2, grad=3)
    constexpr uint32_t TENSOR_INPUT_START = 1;
    constexpr uint32_t TENSOR_INPUT_END = 4;
    for (uint32_t i = TENSOR_INPUT_START; i < TENSOR_INPUT_END; i++) {
        auto tensorInput = context->GetInputShape(i);
        OP_CHECK_NULL_WITH_CONTEXT(context, tensorInput);
        auto tensorShape = EnsureNotScalar(tensorInput->GetStorageShape());
        OP_CHECK_IF(
            tensorShape.GetShapeSize() != varShape.GetShapeSize(),
            OP_LOGE(context, "ApplyAdagradDAD: input[%u] shape size %ld != var shape size %ld",
                    i, tensorShape.GetShapeSize(), varShape.GetShapeSize()),
            return ge::GRAPH_FAILED);
    }

    // 校验标量输入为 1-element (lr=4, l1=5, l2=6, global_step=7)
    constexpr uint32_t SCALAR_INPUT_START = 4;
    constexpr uint32_t SCALAR_INPUT_END = 8;
    for (uint32_t i = SCALAR_INPUT_START; i < SCALAR_INPUT_END; i++) {
        auto scalarInput = context->GetInputShape(i);
        OP_CHECK_NULL_WITH_CONTEXT(context, scalarInput);
        auto scalarShape = scalarInput->GetStorageShape();
        OP_CHECK_IF(
            scalarShape.GetShapeSize() != 1,
            OP_LOGE(context, "ApplyAdagradDAD: input[%u] must be 1-element scalar, got shape_size=%ld",
                    i, scalarShape.GetShapeSize()),
            return ge::GRAPH_FAILED);
    }

    auto varDesc = context->GetInputDesc(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, varDesc);
    *dataType = varDesc->GetDataType();

    const std::set<ge::DataType> supportedDtype = {ge::DT_FLOAT, ge::DT_FLOAT16};
    OP_CHECK_IF(supportedDtype.count(*dataType) == 0,
                OP_LOGE(context, "ApplyAdagradDAD: unsupported dtype %d", static_cast<int>(*dataType)),
                return ge::GRAPH_FAILED);

    return ge::GRAPH_SUCCESS;
}

// Fill TilingData: memset + empty-tensor short-circuit + compute + fill.
static ge::graphStatus FillTilingData(gert::TilingContext* context, int64_t totalElements,
                                      ge::DataType dataType, int64_t coreNum)
{
    ApplyAdagradDADTilingData* tiling = context->GetTilingData<ApplyAdagradDADTilingData>();
    OP_CHECK_NULL_WITH_CONTEXT(context, tiling);
    OP_CHECK_IF(
        memset_s(tiling, sizeof(ApplyAdagradDADTilingData), 0, sizeof(ApplyAdagradDADTilingData)) != EOK,
        OP_LOGE(context, "set tiling data error"), return ge::GRAPH_FAILED);

    if (totalElements == 0) {
        context->SetBlockDim(1);
        return ge::GRAPH_SUCCESS;
    }

    auto gsDesc = context->GetInputDesc(GLOBAL_STEP_INPUT_INDEX);
    OP_CHECK_NULL_WITH_CONTEXT(context, gsDesc);
    ge::DataType gsDtype = gsDesc->GetDataType();

    uint32_t chunkSize;
    int64_t usedCoreNum;
    ComputeTilingParams(totalElements, dataType, coreNum, &chunkSize, &usedCoreNum);

    tiling->totalElements = totalElements;
    tiling->chunkSize = chunkSize;
    tiling->globalStepDtype = (gsDtype == ge::DT_INT64) ? 1 : 0;
    context->SetBlockDim(usedCoreNum);

    return ge::GRAPH_SUCCESS;
}

// Main tiling function
static ge::graphStatus ApplyAdagradDADTilingFunc(gert::TilingContext* context)
{
    OP_LOGI(context->GetNodeName(), "Enter ApplyAdagradDADTilingFunc");
    uint64_t ubSize;
    int64_t coreNum;
    OP_CHECK_IF(
        GetPlatformInfo(context, &ubSize, &coreNum) != ge::GRAPH_SUCCESS,
        OP_LOGE(context, "GetPlatformInfo error"),
        return ge::GRAPH_FAILED);

    int64_t totalElements;
    ge::DataType dataType;
    OP_CHECK_IF(
        GetShapeAndValidate(context, &totalElements, &dataType) != ge::GRAPH_SUCCESS,
        OP_LOGE(context, "GetShapeAndValidate error"),
        return ge::GRAPH_FAILED);

    OP_CHECK_IF(
        GetWorkspaceSize(context) != ge::GRAPH_SUCCESS,
        OP_LOGE(context, "GetWorkspaceSize error"),
        return ge::GRAPH_FAILED);

    return FillTilingData(context, totalElements, dataType, coreNum);
}

static ge::graphStatus TilingParseForApplyAdagradDAD([[maybe_unused]] gert::TilingParseContext* context)
{
    return ge::GRAPH_SUCCESS;
}

struct ApplyAdagradDADCompileInfo {};

// Tiling registration
// CACHE-SAFE: 标量值不存入 TilingData，kernel 从 GM_ADDR 读取，无需 TilingInputsDataDependency。
IMPL_OP_OPTILING(ApplyAdagradDAD)
    .Tiling(ApplyAdagradDADTilingFunc)
    .TilingParse<ApplyAdagradDADCompileInfo>(TilingParseForApplyAdagradDAD);

} // namespace optiling
