/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/**
 * NOTE: Portions of this code were AI-generated and have been
 * technically reviewed for functional accuracy and security
 *
 * Generated By CANNBot
 */

/*!
 * \file bn_infer_grad_proto.h
 * \brief BNInferGrad 算子 IR 原型注册（与 op_host/bn_infer_grad_def.cpp 类名 BNInferGrad 对齐）
 *
 * 公式参考: x_backprop = grads * scale * 1/sqrt(batch_variance + epsilon)
 *
 * 注: canndev 历史代号为 `BNInferGrad`（大写 NN），本算子按本仓 def.cpp 已声明的
 * `BNInferGrad` 注册以保持 def 与 proto 一致，避免图融合阶段类型字符串不匹配。
 */
#ifndef OPS_BN_INFER_GRAD_PROTO_H_
#define OPS_BN_INFER_GRAD_PROTO_H_

#include "graph/operator_reg.h"

namespace ge {
/**
* @brief Performs the backpropagation of BatchNorm for inference .

* @par Inputs:
* Three inputs, including:
* @li grads: A tensor of type float16 or float32 or bfloat16. Indicates the gradient of the BathNorm output parameter "y".
* Shape support 4D and 5D. Format support NHWC, NCHW or NC1HWC0.
* @li scale: A 1D tensor of type float32. Shape must be C channel.
* Specifies the scaling factor. Has the same format as "grads".
* @li batch_variance: A 1D tensor of type float32. Calculated variance, that is, the value of BatchNorm output parameter "batch_variance".
* Shape must be C channel. Has the same format as "grads". \n

* @par Attributes:
* epsilon: An optional float32. Defaults to "0.0001". A small float number
* added to the variance of "batch_variance". \n

* @par Outputs:
* x_backprop: A tensor of type float16 or float32 or bfloat16.
* Indicates the gradient of BathNorm input data "x".
* Has the same type, shape and format as "grads". \n

* @attention Constraints:
* The preceding layer of this operator must be operator BatchNorm.
*/
REG_OP(BNInferGrad)
    .INPUT(grads, TensorType({DT_FLOAT16, DT_FLOAT, DT_BF16}))
    .INPUT(scale, TensorType({DT_FLOAT}))
    .INPUT(batch_variance, TensorType({DT_FLOAT}))
    .OUTPUT(x_backprop, TensorType({DT_FLOAT16, DT_FLOAT, DT_BF16}))
    .ATTR(epsilon, Float, 0.0001)
    .OP_END_FACTORY_REG(BNInferGrad)
} // namespace ge

#endif // OPS_BN_INFER_GRAD_PROTO_H_
