/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file fake_quant_with_min_max_vars_arch35.cpp
 * \brief FakeQuantWithMinMaxVars kernel entry for arch35 (Ascend950)
 *
 * Template parameters (matching TilingKey ASCENDC_TPL_ARGS_DECL):
 *   - MODODE:      0=PER_TENSOR (unused, hardcoded PT)
 *   - BUFFER_MODE: 0=single buffer, 1=double buffer
 *   - ROUND_MODE:  0=CAST_FLOOR, 1=CAST_RINT (unused, hardcoded RINT)
 *   - HAS_ZP:      0=no explicit zero_point (unused, nudge is kernel-internal)
 */

#include "arch35/fake_quant_with_min_max_vars_kernel.h"

template <uint32_t MODODE, uint32_t BUFFER_MODE, uint32_t ROUND_MODE, uint32_t HAS_ZP>
__global__ __aicore__ void fake_quant_with_min_max_vars(
    GM_ADDR x, GM_ADDR min, GM_ADDR max, GM_ADDR y,
    GM_ADDR workspace, GM_ADDR tiling)
{
    REGISTER_TILING_DEFAULT(FakeQuantWithMinMaxVarsTilingData);
    GET_TILING_DATA_WITH_STRUCT(FakeQuantWithMinMaxVarsTilingData, tilingData, tiling);
    NsFakeQuantWithMinMaxVars::FakeQuantWithMinMaxVars<BUFFER_MODE> op;
    op.Init(x, min, max, y, &tilingData);
    op.Process();
}