/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/**
 * NOTE: Portions of this code were AI-generated and have been
 * technically reviewed for functional accuracy and security
 * Generated By CANNBot
 */

/*!
 * \file apply_proximal_adagrad_tiling_arch35.cpp
 * \brief ApplyProximalAdagrad tiling (arch35).
 *
 * Tiling strategy:
 *   1. Multi-core: split total elements evenly across AI vector cores.
 *      blockFactor = CeilAlign(CeilDiv(total, coreNum), ubBlockSize)
 *      so neighbouring cores do not trample each other's GM output.
 *   2. UB: ubFactor = floor((UB_size / 4B) / N) where N counts the per-element
 *      4-byte-unit footprint of all co-resident UB tensors on the chosen path.
 *
 * UB co-resident layout (fp32 path, single-precision native):
 *   3 IN queues  (var/accum/grad)  x DB(2) x 4B  = 24B
 *   2 OUT queues (var/accum)       x DB(2) x 4B  = 16B
 *   4 fp32 scratch (eta/prox/thresh/scale)       = 16B
 *                                          total = 56B / elem = 14 fp32-units / elem
 *
 * UB co-resident layout (fp16/bf16 path, with Cast to fp32 intermediate):
 *   3 IN queues  (var/accum/grad)  x DB(2) x 2B  = 12B
 *   2 OUT queues (var/accum)       x DB(2) x 2B  = 8B
 *   3 fp32 cast-buffers (varF32 / accumF32 / gradF32)
 *                                        3 x 4B = 12B
 *   4 fp32 scratch (eta/prox/thresh/scale) 4 x 4B = 16B
 *                                          total = 48B / elem = 12 fp32-units / elem
 *
 *   Note: the fp16/bf16 footprint is smaller than fp32 because the queue
 *   tensors are half-precision. We still allocate fp32 scratch / cast
 *   buffers (the dominant cost). Both budgets are conservative ceilings.
 *
 *   bf16 path also allocates 3 x 32B scratch (scalarLoadBuf_ /
 *   scalarLoadF32Buf_ / bf16ConstBuf_), all constant 32B and negligible
 *   versus the per-element ubFactor allocation.
 *
 * TilingKey via (D_T_VAR, PAD_TAIL, HAS_L1):
 *   (fp32,  PAD_TAIL=0, HAS_L1=1) -> general fp32 / aligned tail / l1 >= 0
 *   (fp32,  PAD_TAIL=1, HAS_L1=1) -> general fp32 / non-aligned tail / l1 >= 0
 *   (fp32,  PAD_TAIL=*, HAS_L1=0) -> fp32 fast-path / l1 == 0
 *   (fp16,  PAD_TAIL=0, HAS_L1=1) -> fp16 cast path / aligned tail / l1 >= 0
 *   (fp16,  PAD_TAIL=1, HAS_L1=1) -> fp16 cast path / non-aligned tail / l1 >= 0
 *   (fp16,  PAD_TAIL=*, HAS_L1=0) -> fp16 cast path / l1 == 0
 *   (bf16,  PAD_TAIL=0, HAS_L1=1) -> bf16 cast path / aligned tail / l1 >= 0
 *   (bf16,  PAD_TAIL=1, HAS_L1=1) -> bf16 cast path / non-aligned tail / l1 >= 0
 *   (bf16,  PAD_TAIL=*, HAS_L1=0) -> bf16 cast path / l1 == 0
 */

#include "register/op_def_registry.h"
#include "op_common/log/log.h"
#include "op_common/op_host/util/math_util.h"
#include "op_common/op_host/util/platform_util.h"
#include "optim/apply_proximal_adagrad/op_kernel/arch35/apply_proximal_adagrad_tiling_data.h"
#include "optim/apply_proximal_adagrad/op_kernel/arch35/apply_proximal_adagrad_tiling_key.h"

namespace optiling {

using Ops::Base::CeilDiv;
using Ops::Base::CeilAlign;
using Ops::Base::FloorAlign;
using Ops::Base::FloorDiv;
using Ops::Base::GetUbBlockSize;

constexpr uint32_t WS_SYS_SIZE = 0U;
// Per-tile target element count.
constexpr int64_t TILE_ELEM_NUM_TARGET = 2048;
// UB co-resident buffer accounting (per element, in 4-byte / fp32-unit terms).
// See the file-level comment for the breakdown.
constexpr int64_t UB_BUFFER_COUNT_FP32 = 14;
constexpr int64_t UB_BUFFER_COUNT_HALF = 12;
constexpr int64_t SIZE_FP32 = 4;

static const gert::Shape g_vec_1_shape = {1};

static inline const gert::Shape EnsureNotScalar(const gert::Shape& in_shape)
{
    if (in_shape.GetDimNum() == 0) {
        return g_vec_1_shape;
    }
    return in_shape;
}

static ge::graphStatus GetPlatformInfo(gert::TilingContext* context,
                                       uint64_t& ubSize, int64_t& coreNum)
{
    fe::PlatFormInfos* platformInfoPtr = context->GetPlatformInfo();
    OP_CHECK_NULL_WITH_CONTEXT(context, platformInfoPtr);
    auto ascendcPlatform = platform_ascendc::PlatformAscendC(platformInfoPtr);
    coreNum = ascendcPlatform.GetCoreNumAiv();
    OP_CHECK_IF(coreNum == 0, OP_LOGE(context, "coreNum is 0"),
                return ge::GRAPH_FAILED);
    ascendcPlatform.GetCoreMemSize(platform_ascendc::CoreMemType::UB, ubSize);
    OP_CHECK_IF(ubSize == 0, OP_LOGE(context, "ubSize is 0"),
                return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus GetShapeInfo(gert::TilingContext* context,
                                    int64_t& totalElements,
                                    ge::DataType& dataType)
{
    // Input 0 = var; its shape is canonical (var/accum/grad must match).
    auto inputVar = context->GetInputShape(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, inputVar);
    auto varShape = EnsureNotScalar(inputVar->GetStorageShape());
    totalElements = varShape.GetShapeSize();

    auto inputDesc = context->GetInputDesc(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, inputDesc);
    dataType = inputDesc->GetDataType();
    OP_CHECK_IF(dataType != ge::DT_FLOAT &&
                dataType != ge::DT_FLOAT16 &&
                dataType != ge::DT_BF16,
                OP_LOGE(context,
                        "ApplyProximalAdagrad: only float32 / float16 / "
                        "bfloat16 are supported, got %d",
                        static_cast<int>(dataType)),
                return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus GetWorkspaceSize(gert::TilingContext* context)
{
    size_t* currentWorkspace = context->GetWorkspaceSizes(1);
    OP_CHECK_NULL_WITH_CONTEXT(context, currentWorkspace);
    currentWorkspace[0] = WS_SYS_SIZE;
    return ge::GRAPH_SUCCESS;
}

// Multi-core split: ceil-aligned to DMA granularity.
// ubBlockSize = 32B / sizeof(T), fp32 -> 8 elements, fp16/bf16 -> 16 elements.
static ge::graphStatus ComputeMultiCoreSplit(gert::TilingContext* context,
                                             int64_t totalElements,
                                             int64_t coreNum,
                                             int64_t& blockFactor,
                                             int64_t& usedCoreNum,
                                             int64_t& ubBlockSize)
{
    ubBlockSize = Ops::Base::GetUbBlockSize(context);
    OP_CHECK_IF(ubBlockSize <= 0,
                OP_LOGE(context, "invalid ubBlockSize=%ld", ubBlockSize),
                return ge::GRAPH_FAILED);

    blockFactor = CeilAlign(CeilDiv(totalElements, coreNum), ubBlockSize);
    usedCoreNum = CeilDiv(totalElements, blockFactor);
    return ge::GRAPH_SUCCESS;
}

// UB split per dtype path. perElemBytes = sizeof(fp32) for the worst-case
// (cast/scratch) accounting; ubBufCount captures the actual per-element
// 4-byte-unit footprint. Caller must ensure ubBlockSize > 0.
static ge::graphStatus ComputeUbSplit(gert::TilingContext* context,
                                      uint64_t ubSize, ge::DataType dataType,
                                      int64_t blockFactor, int64_t ubBlockSize,
                                      int64_t& ubFactor)
{
    int64_t ubBufCount =
        (dataType == ge::DT_FLOAT) ? UB_BUFFER_COUNT_FP32 : UB_BUFFER_COUNT_HALF;
    int64_t perElemBytes = SIZE_FP32;

    int64_t ubCapacityElem =
        FloorAlign(FloorDiv(static_cast<int64_t>(ubSize) / perElemBytes,
                            ubBufCount),
                   ubBlockSize);
    OP_CHECK_IF(ubCapacityElem <= 0,
                OP_LOGE(context, "UB too small: ubCapacityElem=%ld",
                        ubCapacityElem),
                return ge::GRAPH_FAILED);

    ubFactor = (TILE_ELEM_NUM_TARGET < ubCapacityElem)
                   ? TILE_ELEM_NUM_TARGET
                   : ubCapacityElem;

    // Also cap by blockFactor so a single core does not allocate more UB
    // space than it will ever use.
    if (ubFactor > blockFactor) {
        ubFactor = FloorAlign(blockFactor, ubBlockSize);
        if (ubFactor <= 0) {
            ubFactor = ubBlockSize;
        }
    }
    return ge::GRAPH_SUCCESS;
}

// TilingKey via ASCENDC_TPL_SEL_PARAM (template-argument mechanism).
// HAS_L1 cannot be determined from host-side tiling without a Host<->Device
// sync (lr/l1/l2 are aclTensor inputs whose values live in Device GM), so we
// default it to 1 and rely on the kernel to take a runtime fast-path when
// l1 == 0. The HAS_L1 = 0 binary is still produced so UT can drive TilingKey
// directly (and a future L0-API hint can flip this from host).
static void SetTilingKey(gert::TilingContext* context, ge::DataType dataType,
                         uint32_t padTail)
{
    uint32_t dTypeVar = static_cast<uint32_t>(dataType);
    uint32_t hasL1 = 1U;
    ASCENDC_TPL_SEL_PARAM(context, dTypeVar, padTail, hasL1);
}

// Multi-core + UB split for non-empty tensors. Fills tiling, sets block dim and
// tiling key. Empty-tensor handling lives in the caller.
static ge::graphStatus FillTilingForNonEmpty(gert::TilingContext* context,
                                             int64_t totalElements,
                                             ge::DataType dataType,
                                             uint64_t ubSize, int64_t coreNum,
                                             ApplyProximalAdagradTilingData* tiling)
{
    int64_t blockFactor = 0;
    int64_t usedCoreNum = 0;
    int64_t ubBlockSize = 0;
    OP_CHECK_IF(ComputeMultiCoreSplit(context, totalElements, coreNum,
                                      blockFactor, usedCoreNum,
                                      ubBlockSize) != ge::GRAPH_SUCCESS,
                OP_LOGE(context, "ComputeMultiCoreSplit error"),
                return ge::GRAPH_FAILED);

    int64_t ubFactor = 0;
    OP_CHECK_IF(ComputeUbSplit(context, ubSize, dataType, blockFactor,
                               ubBlockSize, ubFactor) != ge::GRAPH_SUCCESS,
                OP_LOGE(context, "ComputeUbSplit error"),
                return ge::GRAPH_FAILED);

    tiling->blockFactor = blockFactor;
    tiling->ubFactor = ubFactor;
    context->SetBlockDim(usedCoreNum);

    // Guard the modulo against ubBlockSize == 0; ComputeMultiCoreSplit already
    // rejects ubBlockSize <= 0, the explicit check here just satisfies static
    // analyzers that don't track the postcondition through the call.
    uint32_t padTail =
        (ubBlockSize > 0 && (totalElements % ubBlockSize) != 0) ? 1U : 0U;
    SetTilingKey(context, dataType, padTail);
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus ApplyProximalAdagradTilingFunc(gert::TilingContext* context)
{
    uint64_t ubSize = 0;
    int64_t coreNum = 0;
    OP_CHECK_IF(GetPlatformInfo(context, ubSize, coreNum) != ge::GRAPH_SUCCESS,
                OP_LOGE(context, "GetPlatformInfo error"),
                return ge::GRAPH_FAILED);

    int64_t totalElements = 0;
    ge::DataType dataType = ge::DT_FLOAT;
    OP_CHECK_IF(GetShapeInfo(context, totalElements, dataType) != ge::GRAPH_SUCCESS,
                OP_LOGE(context, "GetShapeInfo error"),
                return ge::GRAPH_FAILED);

    OP_CHECK_IF(GetWorkspaceSize(context) != ge::GRAPH_SUCCESS,
                OP_LOGE(context, "GetWorkspaceSize error"),
                return ge::GRAPH_FAILED);

    ApplyProximalAdagradTilingData* tiling =
        context->GetTilingData<ApplyProximalAdagradTilingData>();
    OP_CHECK_NULL_WITH_CONTEXT(context, tiling);
    OP_CHECK_IF(
        memset_s(tiling, sizeof(ApplyProximalAdagradTilingData), 0,
                 sizeof(ApplyProximalAdagradTilingData)) != EOK,
        OP_LOGE(context, "set tiling data error"),
        return ge::GRAPH_FAILED);

    tiling->totalElements = totalElements;

    // Empty tensor: run a single idle core so the launcher still succeeds.
    // Process() short-circuits before doing any compute.
    if (totalElements == 0) {
        tiling->blockFactor = 0;
        tiling->ubFactor = 0;
        context->SetBlockDim(1);
        SetTilingKey(context, dataType, 0U);
        return ge::GRAPH_SUCCESS;
    }

    return FillTilingForNonEmpty(context, totalElements, dataType, ubSize,
                                 coreNum, tiling);
}

static ge::graphStatus TilingParseForApplyProximalAdagrad(
    [[maybe_unused]] gert::TilingParseContext* context)
{
    return ge::GRAPH_SUCCESS;
}

struct ApplyProximalAdagradCompileInfo {};

IMPL_OP_OPTILING(ApplyProximalAdagrad)
    .Tiling(ApplyProximalAdagradTilingFunc)
    .TilingParse<ApplyProximalAdagradCompileInfo>(TilingParseForApplyProximalAdagrad);

} // namespace optiling
