/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file foreach_log1p_tiling_arch35.cpp
 * \brief Tiling implementation for foreach_log1p operator.
 */

#include <vector>
#include <algorithm>
#include "register/op_def_registry.h"
#include "tiling/tiling_api.h"
#include "platform/platform_info.h"
#include "log/log.h"
#include "../../op_kernel/arch35/foreach_log1p_tiling_data.h"
#include "../../op_kernel/arch35/foreach_log1p_tiling_key.h"

using namespace AscendC;

namespace optiling {

constexpr int64_t DCACHE_SIZE = 128 * 1024;
constexpr int64_t MIN_PER_CORE_ELEMENTS = 1024;
constexpr int64_t INPUT_IDX = 0;

struct ForeachLog1pCompileInfo {
    int64_t coreNum;
    int64_t ubSize;
};

constexpr uint64_t TILING_KEY_FP16 = 0;
constexpr uint64_t TILING_KEY_FP32 = 1;
constexpr uint64_t TILING_KEY_BF16 = 2;

constexpr int64_t FALLBACK_CORE_NUM = 24;
constexpr int64_t FALLBACK_UB_SIZE = 1024 * 1024;

static uint64_t GetTilingKeyByDtype(ge::DataType dtype)
{
    switch (dtype) {
        case ge::DT_FLOAT16:
            return TILING_KEY_FP16;
        case ge::DT_FLOAT:
            return TILING_KEY_FP32;
        case ge::DT_BF16:
            return TILING_KEY_BF16;
        default:
            return TILING_KEY_FP16;
    }
}

static ge::graphStatus GetPlatformInfoFallback(const gert::TilingContext* context, int64_t& coreNum, int64_t& ubSize)
{
    auto compileInfo = reinterpret_cast<const ForeachLog1pCompileInfo*>(context->GetCompileInfo());
    if (compileInfo != nullptr && compileInfo->coreNum > 0 && compileInfo->ubSize > 0) {
        coreNum = compileInfo->coreNum;
        ubSize = compileInfo->ubSize;
        return ge::GRAPH_SUCCESS;
    }
    fe::PlatFormInfos* platformInfoPtr = context->GetPlatformInfo();
    if (platformInfoPtr != nullptr) {
        auto ascendcPlatform = platform_ascendc::PlatformAscendC(platformInfoPtr);
        coreNum = ascendcPlatform.GetCoreNumAiv();
        uint64_t ub = 0;
        ascendcPlatform.GetCoreMemSize(platform_ascendc::CoreMemType::UB, ub);
        ubSize = static_cast<int64_t>(ub);
        if (coreNum > 0 && ubSize > 0) {
            return ge::GRAPH_SUCCESS;
        }
    }
    coreNum = FALLBACK_CORE_NUM;
    ubSize = FALLBACK_UB_SIZE;
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus ForeachLog1pTilingFunc(gert::TilingContext* context)
{
    int64_t coreNum = 0;
    int64_t ubSize = 0;
    OP_CHECK_IF(GetPlatformInfoFallback(context, coreNum, ubSize) != ge::GRAPH_SUCCESS,
        OP_LOGE(context, "Failed to get platform info"),
        return ge::GRAPH_FAILED);
    OP_CHECK_IF((ubSize <= DCACHE_SIZE),
        OP_LOGE(context, "ubSize %ld <= DCACHE_SIZE %ld", ubSize, DCACHE_SIZE),
        return ge::GRAPH_FAILED);
    ubSize = ubSize - DCACHE_SIZE;

    auto computeNodeInfoPtr = context->GetComputeNodeInfo();
    OP_CHECK_NULL_WITH_CONTEXT(context, computeNodeInfoPtr);
    auto idxInstanceInfoPtr = computeNodeInfoPtr->GetInputInstanceInfo(INPUT_IDX);
    OP_CHECK_NULL_WITH_CONTEXT(context, idxInstanceInfoPtr);
    uint64_t tensorNum = idxInstanceInfoPtr->GetInstanceNum();

    OP_CHECK_IF((static_cast<int32_t>(tensorNum) > MAX_TENSOR_NUM),
        OP_LOGE(context, "tensorNum %lu exceeds MAX_TENSOR_NUM %d",
            tensorNum, MAX_TENSOR_NUM),
        return ge::GRAPH_FAILED);

    int64_t totalElements = 0;
    ge::DataType dataType = ge::DT_FLOAT;
    ForeachLog1pTilingData* tilingData = context->GetTilingData<ForeachLog1pTilingData>();

    for (uint64_t i = 0; i < tensorNum; i++) {
        auto idxTensorShapePtr = context->GetDynamicInputShape(INPUT_IDX, i);
        OP_CHECK_NULL_WITH_CONTEXT(context, idxTensorShapePtr);
        auto idxTensorShape = idxTensorShapePtr->GetStorageShape();
        int64_t numel = idxTensorShape.GetShapeSize();
        totalElements += numel;
        tilingData->cumulativeOffsets[i] = totalElements;

        if (i == 0) {
            auto idxTensorDtypePtr = context->GetDynamicInputDesc(INPUT_IDX, i);
            OP_CHECK_NULL_WITH_CONTEXT(context, idxTensorDtypePtr);
            dataType = idxTensorDtypePtr->GetDataType();
        }
    }

    int64_t needCoreNum = (totalElements + MIN_PER_CORE_ELEMENTS - 1) / MIN_PER_CORE_ELEMENTS;
    needCoreNum = std::min(needCoreNum, coreNum);
    needCoreNum = std::max(needCoreNum, static_cast<int64_t>(1));
    int64_t perCoreElements = (totalElements + needCoreNum - 1) / needCoreNum;

    tilingData->needCoreNum = static_cast<int32_t>(needCoreNum);
    tilingData->tensorCount = static_cast<int32_t>(tensorNum);
    tilingData->totalElements = totalElements;
    tilingData->perCoreElements = perCoreElements;

    context->SetBlockDim(needCoreNum);
    context->SetTilingKey(GetTilingKeyByDtype(dataType));

    auto res = context->SetLocalMemorySize(ubSize);
    OP_CHECK_IF((res != ge::GRAPH_SUCCESS),
        OP_LOGE(context, "SetLocalMemorySize ubSize=%ld failed", ubSize),
        return ge::GRAPH_FAILED);

    size_t* currentWorkspace = context->GetWorkspaceSizes(1);
    currentWorkspace[0] = 0;

    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus TilingParseForForeachLog1p(gert::TilingParseContext* context)
{
    auto compileInfo = context->GetCompiledInfo<ForeachLog1pCompileInfo>();
    OP_CHECK_NULL_WITH_CONTEXT(context, compileInfo);
    auto platformInfo = context->GetPlatformInfo();
    OP_CHECK_NULL_WITH_CONTEXT(context, platformInfo);
    auto ascendcPlatform = platform_ascendc::PlatformAscendC(platformInfo);
    compileInfo->coreNum = ascendcPlatform.GetCoreNumAiv();
    OP_CHECK_IF((compileInfo->coreNum <= 0),
        OP_LOGE(context, "Failed to get core num."),
        return ge::GRAPH_FAILED);
    uint64_t ubSize;
    ascendcPlatform.GetCoreMemSize(platform_ascendc::CoreMemType::UB, ubSize);
    compileInfo->ubSize = static_cast<int64_t>(ubSize);
    OP_CHECK_IF((compileInfo->ubSize <= 0),
        OP_LOGE(context, "Failed to get ub size."),
        return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

IMPL_OP_OPTILING(ForeachLog1p)
    .Tiling(ForeachLog1pTilingFunc)
    .TilingParse<ForeachLog1pCompileInfo>(TilingParseForForeachLog1p);

} // namespace optiling
