/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file sparse_apply_adadelta_tiling.cpp
 * \brief Tiling implementation for sparse_apply_adadelta operator
 */

#include "log/log.h"
#include "platform/platform_ascendc.h"
#include "util/math_util.h"
#include "op_host/tiling_util.h"
#include "op_host/tiling_templates_registry.h"
#include "optim/sparse_apply_adadelta/op_kernel/arch35/sparse_apply_adadelta_tiling_data.h"
#include "optim/sparse_apply_adadelta/op_kernel/arch35/sparse_apply_adadelta_tiling_key.h"

namespace optiling {

using namespace Ops::NN::Optiling;

inline const gert::Shape& EnsureNotScalar(const gert::Shape& in_shape) { return in_shape; }

constexpr int64_t PER_CORE_K_MIN = 32;
constexpr uint32_t DCACHE_SIZE = 128 * 1024;
constexpr uint32_t STATIC_UB_ESTIMATE = 0;

constexpr int32_t IDX_VAR = 0;
constexpr int32_t IDX_ACCUM = 1;
constexpr int32_t IDX_ACCUM_UPDATE = 2;
constexpr int32_t IDX_LR = 3;
constexpr int32_t IDX_RHO = 4;
constexpr int32_t IDX_EPSILON = 5;
constexpr int32_t IDX_GRAD = 6;
constexpr int32_t IDX_INDICES = 7;

struct SparseApplyAdadeltaCompileInfo {};

static ge::graphStatus GetPlatformInfo(gert::TilingContext* context, uint64_t& ubSize, int64_t& coreNum)
{
    fe::PlatFormInfos* platformInfoPtr = context->GetPlatformInfo();
    OP_CHECK_NULL_WITH_CONTEXT(context, platformInfoPtr);
    auto ascendcPlatform = platform_ascendc::PlatformAscendC(platformInfoPtr);
    coreNum = ascendcPlatform.GetCoreNumAiv();
    OP_CHECK_IF(coreNum == 0, OP_LOGE(context, "coreNum is 0"), return ge::GRAPH_FAILED);
    ascendcPlatform.GetCoreMemSize(platform_ascendc::CoreMemType::UB, ubSize);
    OP_CHECK_IF(ubSize == 0, OP_LOGE(context, "ubSize is 0"), return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

static float GetScalarFloat(gert::TilingContext* context, int32_t idx)
{
    auto tensor = context->GetInputTensor(idx);
    if (tensor == nullptr) {
        return 0.0f;
    }
    const float* data = tensor->GetData<float>();
    if (data == nullptr) {
        return 0.0f;
    }
    return *data;
}

static ge::graphStatus GetWorkspaceSize(gert::TilingContext* context)
{
    auto ascendcPlatform = platform_ascendc::PlatformAscendC(context->GetPlatformInfo());
    uint64_t sysWorkspaceSize = ascendcPlatform.GetLibApiWorkSpaceSize();
    size_t* currentWorkspace = context->GetWorkspaceSizes(1);
    OP_CHECK_NULL_WITH_CONTEXT(context, currentWorkspace);
    currentWorkspace[0] = static_cast<size_t>(sysWorkspaceSize);
    return ge::GRAPH_SUCCESS;
}

static void ComputeAdadeltaCoreNum(int64_t K, int64_t coreNum, gert::TilingContext* context)
{
    if (K == 0) {
        context->SetBlockDim(1);
        return;
    }
    int64_t perCoreK = Ops::Base::CeilDiv(K, coreNum);
    if (perCoreK < PER_CORE_K_MIN) {
        perCoreK = PER_CORE_K_MIN;
    }
    perCoreK = Ops::Base::CeilDiv(perCoreK, static_cast<int64_t>(32)) * 32;
    context->SetBlockDim(Ops::Base::CeilDiv(K, perCoreK));
}

static ge::graphStatus SetLocalMemory(gert::TilingContext* context, uint64_t ubSize)
{
    OP_CHECK_IF((ubSize <= DCACHE_SIZE + STATIC_UB_ESTIMATE),
        OP_LOGE(context, "ubSize %lu <= DCACHE_SIZE + STATIC_UB_ESTIMATE", ubSize),
        return ge::GRAPH_FAILED);
    auto res = context->SetLocalMemorySize(static_cast<uint32_t>(ubSize - DCACHE_SIZE - STATIC_UB_ESTIMATE));
    OP_CHECK_IF((res != ge::GRAPH_SUCCESS),
        OP_LOGE(context, "SetLocalMemorySize failed"), return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus SparseApplyAdadeltaTilingFunc(gert::TilingContext* context)
{
    uint64_t ubSize = 0;
    int64_t coreNum = 0;
    OP_CHECK_IF(
        GetPlatformInfo(context, ubSize, coreNum) != ge::GRAPH_SUCCESS,
        OP_LOGE(context, "GetPlatformInfo error"), return ge::GRAPH_FAILED);

    auto varInput = context->GetInputShape(IDX_VAR);
    OP_CHECK_NULL_WITH_CONTEXT(context, varInput);
    auto indicesInput = context->GetInputShape(IDX_INDICES);
    OP_CHECK_NULL_WITH_CONTEXT(context, indicesInput);

    auto varShape = EnsureNotScalar(varInput->GetStorageShape());
    auto indicesShape = EnsureNotScalar(indicesInput->GetStorageShape());
    int64_t K = indicesShape.GetShapeSize();
    int64_t varShapeSize = varShape.GetShapeSize();
    int64_t varFirstDim = varShape.GetDim(0);
    int64_t rowSize = (varFirstDim > 0) ? (varShapeSize / varFirstDim) : 0;

    auto indicesDesc = context->GetInputDesc(IDX_INDICES);
    OP_CHECK_NULL_WITH_CONTEXT(context, indicesDesc);
    int32_t indicesDType = (indicesDesc->GetDataType() == ge::DT_INT64) ? 1 : 0;

    SparseApplyAdadeltaTilingData* tiling = context->GetTilingData<SparseApplyAdadeltaTilingData>();
    OP_CHECK_NULL_WITH_CONTEXT(context, tiling);
    OP_CHECK_IF(
        memset_s(tiling, sizeof(SparseApplyAdadeltaTilingData), 0, sizeof(SparseApplyAdadeltaTilingData)) != EOK,
        OP_LOGE(context, "set tiling data error"), return ge::GRAPH_FAILED);
    tiling->K = K;
    tiling->rowSize = rowSize;
    tiling->varTotalSize = varShapeSize;
    tiling->lr = GetScalarFloat(context, IDX_LR);
    tiling->rho = GetScalarFloat(context, IDX_RHO);
    tiling->epsilon = GetScalarFloat(context, IDX_EPSILON);
    tiling->indicesDType = indicesDType;

    ComputeAdadeltaCoreNum(K, coreNum, context);
    OP_CHECK_IF(
        GetWorkspaceSize(context) != ge::GRAPH_SUCCESS,
        OP_LOGE(context, "GetWorkspaceSize error"), return ge::GRAPH_FAILED);
    OP_CHECK_IF(SetLocalMemory(context, ubSize) != ge::GRAPH_SUCCESS,
        OP_LOGE(context, "SetLocalMemory error"), return ge::GRAPH_FAILED);

    context->SetTilingKey(GET_TPL_TILING_KEY(
        (indicesDType == 0) ? TILING_KEY_IDX_INT32 : TILING_KEY_IDX_INT64));
    return ge::GRAPH_SUCCESS;
}

static ge::graphStatus TilingParseForSparseApplyAdadelta(
    [[maybe_unused]] gert::TilingParseContext* context)
{
    return ge::GRAPH_SUCCESS;
}

IMPL_OP_OPTILING(SparseApplyAdadelta)
    .Tiling(SparseApplyAdadeltaTilingFunc)
    .TilingParse<SparseApplyAdadeltaCompileInfo>(TilingParseForSparseApplyAdadelta);

}  // namespace optiling
