/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file apply_keras_momentum_infershape.cpp
 * \brief ApplyKerasMomentum 形状推导：1 个输出 var（in-place，accum 隐式更新）
 */

#include "register/op_impl_registry.h"
#include "exe_graph/runtime/infer_shape_context.h"
#include "op_common/log/log.h"

using namespace ge;

namespace ops {

static constexpr size_t VAR_INDEX = 0;

static ge::graphStatus InferShape4ApplyKerasMomentum(gert::InferShapeContext* context)
{
    const gert::Shape* varShape = context->GetInputShape(VAR_INDEX);
    OP_CHECK_NULL_WITH_CONTEXT(context, varShape);

    gert::Shape* varRefShape = context->GetOutputShape(VAR_INDEX);
    OP_CHECK_NULL_WITH_CONTEXT(context, varRefShape);
    *varRefShape = *varShape;

    return ge::GRAPH_SUCCESS;
}

static graphStatus InferDataType4ApplyKerasMomentum(gert::InferDataTypeContext* context)
{
    context->SetOutputDataType(VAR_INDEX, context->GetInputDataType(VAR_INDEX));
    return GRAPH_SUCCESS;
}

IMPL_OP_INFERSHAPE(ApplyKerasMomentum)
    .InferShape(InferShape4ApplyKerasMomentum)
    .InferDataType(InferDataType4ApplyKerasMomentum);

} // namespace ops
