/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file inplace_update_infershape.cpp
 * \brief infershape implementation for InplaceUpdate
 */
#include "register/op_impl_registry.h"
#include "log/log.h"

using namespace ge;

namespace ops {

static ge::graphStatus InferShapeInplaceUpdate(gert::InferShapeContext* context)
{
    const gert::Shape* xShape = context->GetInputShape(0);
    const gert::Shape* indicesShape = context->GetInputShape(1);
    const gert::Shape* vShape = context->GetInputShape(2);
    OP_CHECK_NULL_WITH_CONTEXT(context, xShape);
    OP_CHECK_NULL_WITH_CONTEXT(context, indicesShape);
    OP_CHECK_NULL_WITH_CONTEXT(context, vShape);

    // 校验1: indices 必须是 1 维
    OP_CHECK_IF(indicesShape->GetDimNum() != 1,
        OP_LOGE(context, "indices must be 1-dimensional"), return GRAPH_FAILED);

    // 校验2: x.ndim == v.ndim
    OP_CHECK_IF(xShape->GetDimNum() != vShape->GetDimNum(),
        OP_LOGE(context, "x.ndim must equal v.ndim"), return GRAPH_FAILED);

    // 校验3: v.shape[0] == indices.shape[0]（即 K）
    OP_CHECK_IF(vShape->GetDim(0) != indicesShape->GetDim(0),
        OP_LOGE(context, "v.shape[0] must equal indices length"), return GRAPH_FAILED);

    // 校验4: x.shape[1:] == v.shape[1:]
    for (size_t d = 1; d < xShape->GetDimNum(); d++) {
        OP_CHECK_IF(xShape->GetDim(d) != vShape->GetDim(d),
            OP_LOGE(context, "x.shape[d] must equal v.shape[d] for d >= 1"), return GRAPH_FAILED);
    }

    // 输出 y shape = x shape
    gert::Shape* yShape = context->GetOutputShape(0);
    OP_CHECK_NULL_WITH_CONTEXT(context, yShape);
    yShape->SetDimNum(xShape->GetDimNum());
    for (size_t i = 0; i < xShape->GetDimNum(); i++) {
        yShape->SetDim(i, xShape->GetDim(i));
    }

    return GRAPH_SUCCESS;
}

IMPL_OP_INFERSHAPE(InplaceUpdate).InferShape(InferShapeInplaceUpdate);

} // namespace ops
