/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file test_geir_apply_ftrl_v2.cpp
 * \brief ApplyFtrlV2 GEIR graph mode example
 */

#include <iostream>
#include <fstream>
#include <string.h>
#include <stdint.h>
#include <vector>
#include <string>
#include <map>
#include "assert.h"
#include "graph.h"
#include "types.h"
#include "tensor.h"
#include "ge_error_codes.h"
#include "ge_api_types.h"
#include "ge_api.h"
#include "array_ops.h"
#include "ge_ir_build.h"
#include "../../op_graph/apply_ftrl_v2_proto.h"

#define FAILED -1
#define SUCCESS 0

using namespace ge;
using std::map;
using std::string;
using std::vector;

#define LOG_PRINT(message, ...)         \
    do {                                \
        printf(message, ##__VA_ARGS__); \
    } while (0)

string GetTime()
{
    time_t timep;
    time(&timep);
    char tmp[64];
    strftime(tmp, sizeof(tmp), "%Y-%m-%d %H:%M:%S,000", localtime(&timep));
    return tmp;
}

uint32_t GetDataTypeSize(DataType dt)
{
    switch (dt) {
        case ge::DT_FLOAT:   return 4;
        case ge::DT_FLOAT16: return 2;
        case ge::DT_BF16:    return 2;
        case ge::DT_INT8:    return 1;
        case ge::DT_INT16:   return 2;
        case ge::DT_UINT16:  return 2;
        case ge::DT_INT32:   return 4;
        case ge::DT_UINT32:  return 4;
        case ge::DT_INT64:   return 8;
        case ge::DT_UINT64:  return 8;
        default:             return 4;
    }
}

int32_t GenFloat32Data(vector<int64_t> shapes, Tensor& tensor, TensorDesc& desc, float value)
{
    desc.SetRealDimCnt(shapes.size());
    size_t size = 1;
    for (auto s : shapes) { size *= s; }
    uint32_t dataLen = size * sizeof(float);
    float* pData = new (std::nothrow) float[size];
    for (size_t i = 0; i < size; ++i) { pData[i] = value; }
    tensor = Tensor(desc, (uint8_t*)pData, dataLen);
    delete[] pData;
    return SUCCESS;
}

int32_t GenScalarConstData(Tensor& tensor, TensorDesc& desc, DataType dtype, float value)
{
    vector<int64_t> shape = {1};
    desc.SetRealDimCnt(1);
    uint32_t dataLen = GetDataTypeSize(dtype);
    uint8_t* pData = new (std::nothrow) uint8_t[dataLen];
    if (dtype == ge::DT_FLOAT) {
        float v = value;
        memcpy(pData, &v, sizeof(float));
    } else if (dtype == ge::DT_FLOAT16) {
        uint16_t v = 0;
        float f = value;
        uint32_t* fi = reinterpret_cast<uint32_t*>(&f);
        uint32_t sign = (*fi >> 16) & 0x8000;
        uint32_t exp = ((*fi >> 23) & 0xFF) - 127 + 15;
        uint32_t mant = (*fi >> 13) & 0x3FF;
        if (exp <= 0) v = sign;
        else if (exp >= 31) v = sign | 0x7C00;
        else v = sign | (exp << 10) | mant;
        memcpy(pData, &v, sizeof(uint16_t));
    } else if (dtype == ge::DT_BF16) {
        // BF16 与 FP32 共享相同的 8-bit 指数（偏置 127），直接截断 FP32 低 16 位 mantissa
        uint16_t v = 0;
        float f = value;
        uint32_t* fi = reinterpret_cast<uint32_t*>(&f);
        v = static_cast<uint16_t>((*fi >> 16) & 0xFFFF);
        memcpy(pData, &v, sizeof(uint16_t));
    } else {
        float v = value;
        memcpy(pData, &v, sizeof(float));
    }
    tensor = Tensor(desc, pData, dataLen);
    delete[] pData;
    return SUCCESS;
}

int32_t WriteDataToFile(string binFile, uint64_t dataSize, uint8_t* data)
{
    FILE* fp = fopen(binFile.c_str(), "w");
    if (fp == nullptr) { return FAILED; }
    fwrite(data, sizeof(uint8_t), dataSize, fp);
    fclose(fp);
    return SUCCESS;
}

#define ADD_TENSOR_INPUT(idx, inputName, inDtype, xShape, value, opInst)                          \
    auto ph##idx = op::Data("placeholder" #idx).set_attr_index(idx - 1);                           \
    TensorDesc ph##idx##Desc(ge::Shape(xShape), FORMAT_ND, inDtype);                               \
    ph##idx##Desc.SetPlacement(ge::kPlacementHost);                                                \
    Tensor t##idx;                                                                                 \
    ret = GenFloat32Data(xShape, t##idx, ph##idx##Desc, value);                                    \
    if (ret != SUCCESS) { LOG_PRINT("Gen " #inputName " data failed\n"); return FAILED; }             \
    ph##idx.update_input_desc_x(ph##idx##Desc);                                                    \
    ph##idx.update_output_desc_y(ph##idx##Desc);                                                   \
    input.push_back(t##idx);                                                                       \
    graph.AddOp(ph##idx);                                                                          \
    opInst.set_input_##inputName(ph##idx);                                                         \
    opInst.update_input_desc_##inputName(ph##idx##Desc);                                           \
    inputs.push_back(ph##idx)

#define ADD_SCALAR_INPUT(idx, inputName, inDtype, scalarShape, value, opInst)                      \
    auto ph##idx = op::Const("placeholder" #idx);                                                   \
    TensorDesc ph##idx##Desc(ge::Shape(scalarShape), FORMAT_ND, inDtype);                           \
    ph##idx##Desc.SetPlacement(ge::kPlacementHost);                                                \
    Tensor t##idx;                                                                                 \
    ret = GenScalarConstData(t##idx, ph##idx##Desc, inDtype, value);                               \
    if (ret != SUCCESS) { LOG_PRINT("Gen " #inputName " data failed\n"); return FAILED; }             \
    ph##idx.SetAttr("value", t##idx);                                                              \
    ph##idx.update_output_desc_y(ph##idx##Desc);                                                   \
    graph.AddOp(ph##idx);                                                                          \
    opInst.set_input_##inputName(ph##idx);                                                         \
    opInst.update_input_desc_##inputName(ph##idx##Desc);                                           \
    inputs.push_back(ph##idx)

int CreateApplyFtrlV2Graph(
    DataType inDtype, vector<ge::Tensor>& input, vector<Operator>& inputs,
    vector<Operator>& outputs, Graph& graph)
{
    Status ret = SUCCESS;
    auto applyFtrlV2 = op::ApplyFtrlV2("applyFtrlV2_1");

    vector<int64_t> xShape = {2, 30};
    vector<int64_t> scalarShape = {1};

    ADD_TENSOR_INPUT(1, var,   inDtype, xShape, 1.0f, applyFtrlV2);
    ADD_TENSOR_INPUT(2, accum, inDtype, xShape, 1.0f, applyFtrlV2);
    ADD_TENSOR_INPUT(3, linear,inDtype, xShape, 0.5f, applyFtrlV2);
    ADD_TENSOR_INPUT(4, grad,  inDtype, xShape, 0.1f, applyFtrlV2);

    ADD_SCALAR_INPUT(5, lr,           inDtype, scalarShape, 0.01f, applyFtrlV2);
    ADD_SCALAR_INPUT(6, l1,           inDtype, scalarShape, 0.0f,  applyFtrlV2);
    ADD_SCALAR_INPUT(7, l2,           inDtype, scalarShape, 0.0f,  applyFtrlV2);
    ADD_SCALAR_INPUT(8, l2_shrinkage, inDtype, scalarShape, 0.0f,  applyFtrlV2);
    ADD_SCALAR_INPUT(9, lr_power,     inDtype, scalarShape, -0.5f, applyFtrlV2);

    TensorDesc outDesc(ge::Shape(xShape), FORMAT_ND, inDtype);
    applyFtrlV2.update_output_desc_var(outDesc);

    outputs.push_back(applyFtrlV2);
    return SUCCESS;
}

int main(int argc, char* argv[])
{
    const char* graphName = "apply_ftrl_v2_geir_test";
    Graph graph(graphName);
    vector<ge::Tensor> input;

    LOG_PRINT("%s - INFO - Initialize GE\n", GetTime().c_str());
    map<AscendString, AscendString> globalOptions = {
        {"ge.exec.deviceId", "0"}
    };
    Status ret = ge::GEInitialize(globalOptions);
    if (ret != SUCCESS) {
        LOG_PRINT("%s - ERROR - GEInitialize failed, ret=%d\n", GetTime().c_str(), (int)ret);
        return FAILED;
    }

    vector<Operator> inputs{};
    vector<Operator> outputs{};

    DataType inDtype = DT_FLOAT;
    if (argc > 1) {
        std::string dtypeArg(argv[1]);
        if (dtypeArg == "fp16") {
            inDtype = DT_FLOAT16;
        } else if (dtypeArg == "bf16") {
            inDtype = DT_BF16;
        }
    }
    LOG_PRINT("%s - INFO - dtype = %d\n", GetTime().c_str(), (int)inDtype);

    ret = CreateApplyFtrlV2Graph(inDtype, input, inputs, outputs, graph);
    if (ret != SUCCESS) {
        LOG_PRINT("%s - ERROR - CreateApplyFtrlV2Graph failed\n", GetTime().c_str());
        ge::GEFinalize();
        return FAILED;
    }

    if (!inputs.empty() && !outputs.empty()) {
        graph.SetInputs(inputs).SetOutputs(outputs);
    }

    map<AscendString, AscendString> buildOptions;
    ge::Session* session = new Session(buildOptions);
    if (session == nullptr) {
        LOG_PRINT("%s - ERROR - Create session failed\n", GetTime().c_str());
        ge::GEFinalize();
        return FAILED;
    }

    map<AscendString, AscendString> graphOptions;
    uint32_t graphId = 0;
    ret = session->AddGraph(graphId, graph, graphOptions);
    if (ret != SUCCESS) {
        LOG_PRINT("%s - ERROR - AddGraph failed\n", GetTime().c_str());
        delete session;
        ge::GEFinalize();
        return FAILED;
    }

    LOG_PRINT("%s - INFO - Run graph\n", GetTime().c_str());
    vector<ge::Tensor> output;
    ret = session->RunGraph(graphId, input, output);
    if (ret != SUCCESS) {
        LOG_PRINT("%s - ERROR - RunGraph failed\n", GetTime().c_str());
        delete session;
        ge::GEFinalize();
        return FAILED;
    }
    LOG_PRINT("%s - INFO - RunGraph success\n", GetTime().c_str());

    for (size_t i = 0; i < input.size(); i++) {
        string file = "./apply_ftrl_v2_input_" + std::to_string(i) + ".bin";
        uint8_t* data = input[i].GetData();
        int64_t shapeSize = input[i].GetTensorDesc().GetShape().GetShapeSize();
        uint32_t dataSize = shapeSize * GetDataTypeSize(input[i].GetTensorDesc().GetDataType());
        WriteDataToFile(file, dataSize, data);
    }

    const char* outputNames[] = {"var"};
    for (size_t i = 0; i < output.size(); i++) {
        string file = "./apply_ftrl_v2_output_" + std::to_string(i) + ".bin";
        uint8_t* data = output[i].GetData();
        int64_t shapeSize = output[i].GetTensorDesc().GetShape().GetShapeSize();
        uint32_t dataSize = shapeSize * GetDataTypeSize(output[i].GetTensorDesc().GetDataType());
        WriteDataToFile(file, dataSize, data);
        LOG_PRINT("=== %s (shape=%ld, dtype=%d) ===\n", outputNames[i], shapeSize,
               (int)output[i].GetTensorDesc().GetDataType());
        if (output[i].GetTensorDesc().GetDataType() == DT_FLOAT && shapeSize > 0) {
            float* resultData = (float*)data;
            for (int64_t j = 0; j < shapeSize && j < 16; j++) {
                LOG_PRINT("  [%ld] = %f\n", j, resultData[j]);
            }
            if (shapeSize > 16) { LOG_PRINT("  ... (%ld more)\n", shapeSize - 16); }
        }
    }

    LOG_PRINT("%s - INFO - Finalize GE\n", GetTime().c_str());
    delete session;
    ge::GEFinalize();
    LOG_PRINT("%s - INFO - Done\n", GetTime().c_str());
    return SUCCESS;
}
