/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file foreach_pow_scalar_and_tensor_tiling_key.h
 * \brief Tiling key declarations for foreach_pow_scalar_and_tensor (arch35 / Ascend950).
 *        4 dtype combos: float32^float16, float32^float32, int64^int32, float32^bfloat16.
 */

#ifndef FOREACH_POW_SCALAR_AND_TENSOR_TILING_KEY_H
#define FOREACH_POW_SCALAR_AND_TENSOR_TILING_KEY_H

#include "ascendc/host_api/tiling/template_argument.h"

#define FPST_TPL_SCH_MODE_FP32_FP16 0
#define FPST_TPL_SCH_MODE_FP32_FP32 1
#define FPST_TPL_SCH_MODE_INT64_INT32 2
#define FPST_TPL_SCH_MODE_FP32_BF16 3

ASCENDC_TPL_ARGS_DECL(ForeachPowScalarAndTensor,
                      ASCENDC_TPL_UINT_DECL(schMode, 4, ASCENDC_TPL_UI_LIST, FPST_TPL_SCH_MODE_FP32_FP16,
                                            FPST_TPL_SCH_MODE_FP32_FP32, FPST_TPL_SCH_MODE_INT64_INT32,
                                            FPST_TPL_SCH_MODE_FP32_BF16));

ASCENDC_TPL_SEL(ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_UINT_SEL(schMode, ASCENDC_TPL_UI_LIST, FPST_TPL_SCH_MODE_FP32_FP16,
                                                          FPST_TPL_SCH_MODE_FP32_FP32, FPST_TPL_SCH_MODE_INT64_INT32,
                                                          FPST_TPL_SCH_MODE_FP32_BF16)));

#endif // FOREACH_POW_SCALAR_AND_TENSOR_TILING_KEY_H
