/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file apply_add_sign_kernel.h
 * \brief ApplyAddSign 算子统一模板 Kernel（arch35 / DAV_3510 / Ascend950）
 *
 * 关键设计点：
 *   1) IO Queues：3 VECIN + 1 VECOUT 全部启用 BUF_NUM=2 双缓冲（fp16 同步启用）
 *   2) 中间 buffer：每个 fp32 中间值一个独立 TBuf<TPosition::VECCALC>
 *      → 不再使用 calcBuf_ + GetWithOffset 切片视图
 *   3) 标量：通过 GlobalTensor + DataCopyPad 搬运到 UB 后 GetValue，避免裸 GM 直读
 *   4) NaN-Patch 保留：Compare(EQ,x,x) + Select(VSEL_TENSOR_SCALAR_MODE) 模式 1
 *   5) Step 7 乘法顺序保留：scale*grad 先乘 → Muls(update, tmp, lrVal)
 *   6) Sign tmpBuffer 大小由 Host 侧 GetSignMaxMinTmpSize 精算（kernel 仍保留兜底）
 *
 * 模板参数：
 *   - T_IN:      输入数据类型（float / half / bfloat16_t）
 *   - T_COMPUTE: 计算精度类型（fp32 → float；fp16/bf16 → float 升精度）
 *
 * Compute 流程：
 *   0. [fp16/bf16 only] var_fp32/m_fp32/grad_fp32 = Cast<float>(var/m/grad)  - CAST_NONE
 *   1. betaM1 = 1.0 - beta
 *   2. m_new  = beta * m + (1 - beta) * grad        (Muls + Mul + Add)
 *   3. sign_grad = Sign(grad)                        + NaN-Patch
 *   4. sign_m    = Sign(m_new)                       + NaN-Patch
 *   5. sign_gm   = sign_grad * sign_m
 *   6. scale     = alpha + sign_decay * sign_gm
 *   7. update    = (scale * grad) * lr               ← L1_161 fp16/bf16 subnormal 顺序
 *   8. var_out_fp32 = var - update
 *   9. [fp16/bf16 only] var_out = Cast<T>(var_out_fp32) - CAST_RINT
 *
 * BF16 路径与 FP16 路径完全同构：均走 Cast<float> 升精度 → fp32 全公式 →
 * Cast<T,CAST_RINT> 回写。bf16 mantissa 7bit 比 fp16 mantissa 10bit 更短，
 * Step 7 `(scale*grad)*lr` 顺序对 bf16 同样有 subnormal 保护作用。
 */

#ifndef APPLY_ADD_SIGN_KERNEL_ARCH35_H
#define APPLY_ADD_SIGN_KERNEL_ARCH35_H

#include "kernel_operator.h"
#include "kernel_tiling/kernel_tiling.h"
#include "apply_add_sign_tiling_data.h"
#include "apply_add_sign_tiling_key.h"

namespace NsApplyAddSign {

using namespace AscendC;

// 双缓冲：fp16 / fp32 / bf16 统一启用 BUF_NUM=2（post-acceptance 收敛后 fp16 也开启）
constexpr int32_t BUF_NUM = 2;

template <typename T_IN, typename T_COMPUTE>
class ApplyAddSignKernel {
public:
    __aicore__ inline ApplyAddSignKernel() {}

    __aicore__ inline void Init(GM_ADDR var, GM_ADDR m, GM_ADDR lr, GM_ADDR alpha, GM_ADDR signDecay, GM_ADDR beta,
                                GM_ADDR grad, GM_ADDR varOut, const ApplyAddSignTilingData* tilingData);

    __aicore__ inline void Process();

private:
    __aicore__ inline void CopyIn(int64_t progress, int64_t currentNum);
    __aicore__ inline void Compute(int64_t currentNum);
    __aicore__ inline void CopyOut(int64_t progress, int64_t currentNum);

private:
    TPipe pipe;

    // VECIN Queues：3 张量输入（BUF_NUM=2 双缓冲）
    TQue<QuePosition::VECIN, BUF_NUM> varQueue;
    TQue<QuePosition::VECIN, BUF_NUM> mQueue;
    TQue<QuePosition::VECIN, BUF_NUM> gradQueue;

    // 标量搬运 Queue（深 1，每核每 tile 搬一次即可）
    TQue<QuePosition::VECIN, 1> lrQueue;
    TQue<QuePosition::VECIN, 1> alphaQueue;
    TQue<QuePosition::VECIN, 1> signDecayQueue;
    TQue<QuePosition::VECIN, 1> betaQueue;

    // VECOUT Queue（BUF_NUM=2 双缓冲）
    TQue<QuePosition::VECOUT, BUF_NUM> varOutQueue;

    // VECCALC fp32 中间 Buffer（每个独立 TBuf，避免 calcBuf+GetWithOffset 在 fp16
    // 路径上的 NPU 507035 vec exception）。
    //   - fp32 升精度副本（fp16/bf16 路径专用，fp32 路径空闲不占预算）
    //     varF32Buf / mF32Buf / gradF32Buf
    //   - 标量 Duplicate broadcast
    //     lrBuf / alphaBuf / signDecayBuf / betaBuf
    //   - 中间计算
    //     betaM1Buf / mNewBuf / tmpBuf / signGradBuf / signMBuf / signGmBuf
    //     scaleBuf / updateBuf / varOutF32Buf (fp16/bf16 only)
    //   - 辅助
    //     signTmpBuf (Sign API) / nanMaskBuf (Compare 输出 / Select 输入)
    TBuf<TPosition::VECCALC> varF32Buf;
    TBuf<TPosition::VECCALC> mF32Buf;
    TBuf<TPosition::VECCALC> gradF32Buf;
    TBuf<TPosition::VECCALC> varOutF32Buf;
    TBuf<TPosition::VECCALC> lrBuf;
    TBuf<TPosition::VECCALC> alphaBuf;
    TBuf<TPosition::VECCALC> signDecayBuf;
    TBuf<TPosition::VECCALC> betaBuf;
    TBuf<TPosition::VECCALC> betaM1Buf;
    TBuf<TPosition::VECCALC> mNewBuf;
    TBuf<TPosition::VECCALC> tmpBuf;
    TBuf<TPosition::VECCALC> signGradBuf;
    TBuf<TPosition::VECCALC> signMBuf;
    TBuf<TPosition::VECCALC> signGmBuf;
    TBuf<TPosition::VECCALC> scaleBuf;
    TBuf<TPosition::VECCALC> updateBuf;
    TBuf<TPosition::VECCALC> signTmpBuf;
    TBuf<TPosition::VECCALC> nanMaskBuf;

    // GlobalTensors
    GlobalTensor<T_IN> varGM_;
    GlobalTensor<T_IN> mGM_;
    GlobalTensor<T_IN> gradGM_;
    GlobalTensor<T_IN> varOutGM_;
    GlobalTensor<T_IN> lrGM_;
    GlobalTensor<T_IN> alphaGM_;
    GlobalTensor<T_IN> signDecayGM_;
    GlobalTensor<T_IN> betaGM_;

    int64_t blockLength_ = 0;
    int64_t ubLength_ = 0;
    uint32_t signTmpSize_ = 0;
    uint32_t nanMaskSize_ = 0;
};

// ============================================================================
// Init
// ============================================================================
template <typename T_IN, typename T_COMPUTE>
__aicore__ inline void ApplyAddSignKernel<T_IN, T_COMPUTE>::Init(GM_ADDR var, GM_ADDR m, GM_ADDR lr, GM_ADDR alpha,
                                                                 GM_ADDR signDecay, GM_ADDR beta, GM_ADDR grad,
                                                                 GM_ADDR varOut,
                                                                 const ApplyAddSignTilingData* tilingData)
{
    // Per-core slice
    int64_t remainderLength = tilingData->dim0 - tilingData->blockFactor * AscendC::GetBlockIdx();
    blockLength_ = (remainderLength > tilingData->blockFactor) ? tilingData->blockFactor : remainderLength;
    if (blockLength_ < 0) {
        blockLength_ = 0;
    }
    ubLength_ = tilingData->ubFactor;
    if (ubLength_ < 1) {
        ubLength_ = 1;
    }

    // 张量 GM
    varGM_.SetGlobalBuffer(reinterpret_cast<__gm__ T_IN*>(var) + tilingData->blockFactor * AscendC::GetBlockIdx(),
                           blockLength_);
    mGM_.SetGlobalBuffer(reinterpret_cast<__gm__ T_IN*>(m) + tilingData->blockFactor * AscendC::GetBlockIdx(),
                         blockLength_);
    gradGM_.SetGlobalBuffer(reinterpret_cast<__gm__ T_IN*>(grad) + tilingData->blockFactor * AscendC::GetBlockIdx(),
                            blockLength_);
    varOutGM_.SetGlobalBuffer(reinterpret_cast<__gm__ T_IN*>(varOut) + tilingData->blockFactor * AscendC::GetBlockIdx(),
                              blockLength_);

    // 标量 GM（1 元素）
    lrGM_.SetGlobalBuffer(reinterpret_cast<__gm__ T_IN*>(lr), 1);
    alphaGM_.SetGlobalBuffer(reinterpret_cast<__gm__ T_IN*>(alpha), 1);
    signDecayGM_.SetGlobalBuffer(reinterpret_cast<__gm__ T_IN*>(signDecay), 1);
    betaGM_.SetGlobalBuffer(reinterpret_cast<__gm__ T_IN*>(beta), 1);

    // VECIN Queues（BUF_NUM=2 双缓冲）
    pipe.InitBuffer(varQueue, BUF_NUM, ubLength_ * sizeof(T_IN));
    pipe.InitBuffer(mQueue, BUF_NUM, ubLength_ * sizeof(T_IN));
    pipe.InitBuffer(gradQueue, BUF_NUM, ubLength_ * sizeof(T_IN));

    // 标量 Queue（深 1）
    pipe.InitBuffer(lrQueue, 1, 1 * sizeof(T_IN));
    pipe.InitBuffer(alphaQueue, 1, 1 * sizeof(T_IN));
    pipe.InitBuffer(signDecayQueue, 1, 1 * sizeof(T_IN));
    pipe.InitBuffer(betaQueue, 1, 1 * sizeof(T_IN));

    // VECOUT Queue（BUF_NUM=2 双缓冲）
    pipe.InitBuffer(varOutQueue, BUF_NUM, ubLength_ * sizeof(T_IN));

    // 中间 fp32 buffer。fp16 / fp32 / bf16 同步分配——fp32 路径下 varF32Buf 等
    // 升精度副本不被使用，相当于 ~3 个 fp32 buffer 等价闲置容量（Tiling
    // SINGLE_BUF_TENSOR_COUNT=27 已按 fp32 视角保守预算覆盖该 case）。
    constexpr uint32_t COMPUTE_TYPE_SIZE = sizeof(T_COMPUTE);
    uint32_t calcBytes = static_cast<uint32_t>(ubLength_) * COMPUTE_TYPE_SIZE;

    pipe.InitBuffer(varF32Buf, calcBytes);
    pipe.InitBuffer(mF32Buf, calcBytes);
    pipe.InitBuffer(gradF32Buf, calcBytes);
    pipe.InitBuffer(varOutF32Buf, calcBytes);
    pipe.InitBuffer(lrBuf, calcBytes);
    pipe.InitBuffer(alphaBuf, calcBytes);
    pipe.InitBuffer(signDecayBuf, calcBytes);
    pipe.InitBuffer(betaBuf, calcBytes);
    pipe.InitBuffer(betaM1Buf, calcBytes);
    pipe.InitBuffer(mNewBuf, calcBytes);
    pipe.InitBuffer(tmpBuf, calcBytes);
    pipe.InitBuffer(signGradBuf, calcBytes);
    pipe.InitBuffer(signMBuf, calcBytes);
    pipe.InitBuffer(signGmBuf, calcBytes);
    pipe.InitBuffer(scaleBuf, calcBytes);
    pipe.InitBuffer(updateBuf, calcBytes);

    // Sign tmpBuffer。Host 侧通过 GetSignMaxMinTmpSize 精算并下发；Kernel
    // 仍保留兜底（256B）以兼容旧 Tiling 路径 (tilingData->signTmpSize==0)。
    signTmpSize_ = tilingData->signTmpSize > 0 ? tilingData->signTmpSize : 256U;
    pipe.InitBuffer(signTmpBuf, signTmpSize_);

    // NaN mask buffer。Compare(EQ,x,x) 输出 1 bit/元素；按 byte 安全余量分配，
    // 最少 32B（UB 最小对齐）。
    nanMaskSize_ = static_cast<uint32_t>((ubLength_ < 32) ? 32 : ubLength_);
    pipe.InitBuffer(nanMaskBuf, nanMaskSize_);
}

// ============================================================================
// CopyIn
// ============================================================================
template <typename T_IN, typename T_COMPUTE>
__aicore__ inline void ApplyAddSignKernel<T_IN, T_COMPUTE>::CopyIn(int64_t progress, int64_t currentNum)
{
    // 张量搬运
    LocalTensor<T_IN> varLocal = varQueue.AllocTensor<T_IN>();
    LocalTensor<T_IN> mLocal = mQueue.AllocTensor<T_IN>();
    LocalTensor<T_IN> gradLocal = gradQueue.AllocTensor<T_IN>();

    DataCopyParams params;
    params.blockCount = 1;
    params.blockLen = static_cast<uint16_t>(currentNum * sizeof(T_IN));
    params.srcStride = 0;
    params.dstStride = 0;
    DataCopyPad(varLocal, varGM_[progress * ubLength_], params, {false, 0, 0, 0});
    DataCopyPad(mLocal, mGM_[progress * ubLength_], params, {false, 0, 0, 0});
    DataCopyPad(gradLocal, gradGM_[progress * ubLength_], params, {false, 0, 0, 0});

    varQueue.EnQue(varLocal);
    mQueue.EnQue(mLocal);
    gradQueue.EnQue(gradLocal);

    // 标量搬运（1 元素），DataCopyPad 自动 32B 对齐
    LocalTensor<T_IN> lrLocal = lrQueue.AllocTensor<T_IN>();
    LocalTensor<T_IN> alphaLocal = alphaQueue.AllocTensor<T_IN>();
    LocalTensor<T_IN> signDecayLocal = signDecayQueue.AllocTensor<T_IN>();
    LocalTensor<T_IN> betaLocal = betaQueue.AllocTensor<T_IN>();

    DataCopyParams scalarParams;
    scalarParams.blockCount = 1;
    scalarParams.blockLen = static_cast<uint16_t>(1 * sizeof(T_IN));
    scalarParams.srcStride = 0;
    scalarParams.dstStride = 0;
    DataCopyPad(lrLocal, lrGM_, scalarParams, {false, 0, 0, 0});
    DataCopyPad(alphaLocal, alphaGM_, scalarParams, {false, 0, 0, 0});
    DataCopyPad(signDecayLocal, signDecayGM_, scalarParams, {false, 0, 0, 0});
    DataCopyPad(betaLocal, betaGM_, scalarParams, {false, 0, 0, 0});

    lrQueue.EnQue(lrLocal);
    alphaQueue.EnQue(alphaLocal);
    signDecayQueue.EnQue(signDecayLocal);
    betaQueue.EnQue(betaLocal);
}

// ============================================================================
// Compute: 8-step element-wise computation
// ============================================================================
template <typename T_IN, typename T_COMPUTE>
__aicore__ inline void ApplyAddSignKernel<T_IN, T_COMPUTE>::Compute(int64_t currentNum)
{
    // --- DeQue tensor inputs ---
    LocalTensor<T_IN> varLocalIn = varQueue.DeQue<T_IN>();
    LocalTensor<T_IN> mLocalIn = mQueue.DeQue<T_IN>();
    LocalTensor<T_IN> gradLocalIn = gradQueue.DeQue<T_IN>();

    // --- DeQue scalars ---
    LocalTensor<T_IN> lrLocalUb = lrQueue.DeQue<T_IN>();
    LocalTensor<T_IN> alphaLocalUb = alphaQueue.DeQue<T_IN>();
    LocalTensor<T_IN> signDecayLocalUb = signDecayQueue.DeQue<T_IN>();
    LocalTensor<T_IN> betaLocalUb = betaQueue.DeQue<T_IN>();

    // 标量取值：
    //   - fp32 / fp16：可以直接 GetValue + C++ scalar static_cast 到 float（half
    //     有 C++ 隐式转换，fp32 无 cast）。
    //   - bf16：BiSheng "not support bf16 type cast" 错误会阻止 C++ 标量层面
    //     的 bfloat16_t → float 转换；必须改走 vector Cast API（每次 1 元素）。
    //     这与 apply_adadelta BF16 标量加载方案一致。
    T_COMPUTE lrVal;
    T_COMPUTE alphaVal;
    T_COMPUTE signDecayVal;
    T_COMPUTE betaVal;
    if constexpr (std::is_same_v<T_IN, bfloat16_t>) {
        // 借用 lrBuf / alphaBuf / signDecayBuf / betaBuf 的前 1 元素做 1-elem Cast。
        // 这些 buf 在后续 Duplicate 之前不会被使用，可安全复用。
        LocalTensor<T_COMPUTE> lrTmp = lrBuf.template Get<T_COMPUTE>();
        LocalTensor<T_COMPUTE> alphaTmp = alphaBuf.template Get<T_COMPUTE>();
        LocalTensor<T_COMPUTE> sdTmp = signDecayBuf.template Get<T_COMPUTE>();
        LocalTensor<T_COMPUTE> betaTmp = betaBuf.template Get<T_COMPUTE>();
        Cast(lrTmp, lrLocalUb, AscendC::RoundMode::CAST_NONE, 1);
        Cast(alphaTmp, alphaLocalUb, AscendC::RoundMode::CAST_NONE, 1);
        Cast(sdTmp, signDecayLocalUb, AscendC::RoundMode::CAST_NONE, 1);
        Cast(betaTmp, betaLocalUb, AscendC::RoundMode::CAST_NONE, 1);
        PipeBarrier<PIPE_V>();
        lrVal = lrTmp.GetValue(0);
        alphaVal = alphaTmp.GetValue(0);
        signDecayVal = sdTmp.GetValue(0);
        betaVal = betaTmp.GetValue(0);
    } else {
        lrVal = static_cast<T_COMPUTE>(lrLocalUb.GetValue(0));
        alphaVal = static_cast<T_COMPUTE>(alphaLocalUb.GetValue(0));
        signDecayVal = static_cast<T_COMPUTE>(signDecayLocalUb.GetValue(0));
        betaVal = static_cast<T_COMPUTE>(betaLocalUb.GetValue(0));
    }

    lrQueue.FreeTensor(lrLocalUb);
    alphaQueue.FreeTensor(alphaLocalUb);
    signDecayQueue.FreeTensor(signDecayLocalUb);
    betaQueue.FreeTensor(betaLocalUb);

    // --- Allocate output buffer ---
    LocalTensor<T_IN> varOutLocal = varOutQueue.AllocTensor<T_IN>();

    // --- 计算视图 (T_COMPUTE / fp32) ---
    // fp32 路径：直接复用 VECIN 缓冲（T_IN==T_COMPUTE==float）
    // fp16/bf16 路径：Cast<float> 升精度到独立 fp32 TBuf
    LocalTensor<T_COMPUTE> varLocal;
    LocalTensor<T_COMPUTE> mLocal;
    LocalTensor<T_COMPUTE> gradLocal;

    if constexpr (std::is_same_v<T_IN, T_COMPUTE>) {
        varLocal = varLocalIn;
        mLocal = mLocalIn;
        gradLocal = gradLocalIn;
    } else {
        LocalTensor<T_COMPUTE> varF32 = varF32Buf.template Get<T_COMPUTE>();
        LocalTensor<T_COMPUTE> mF32 = mF32Buf.template Get<T_COMPUTE>();
        LocalTensor<T_COMPUTE> gradF32 = gradF32Buf.template Get<T_COMPUTE>();
        Cast(varF32, varLocalIn, AscendC::RoundMode::CAST_NONE, currentNum);
        Cast(mF32, mLocalIn, AscendC::RoundMode::CAST_NONE, currentNum);
        Cast(gradF32, gradLocalIn, AscendC::RoundMode::CAST_NONE, currentNum);
        varLocal = varF32;
        mLocal = mF32;
        gradLocal = gradF32;
    }

    // --- 中间 buffer ---
    LocalTensor<T_COMPUTE> lrDup = lrBuf.template Get<T_COMPUTE>();
    LocalTensor<T_COMPUTE> alphaDup = alphaBuf.template Get<T_COMPUTE>();
    LocalTensor<T_COMPUTE> sdDup = signDecayBuf.template Get<T_COMPUTE>();
    LocalTensor<T_COMPUTE> betaDup = betaBuf.template Get<T_COMPUTE>();
    LocalTensor<T_COMPUTE> betaM1 = betaM1Buf.template Get<T_COMPUTE>();
    LocalTensor<T_COMPUTE> mNew = mNewBuf.template Get<T_COMPUTE>();
    LocalTensor<T_COMPUTE> tmp = tmpBuf.template Get<T_COMPUTE>();
    LocalTensor<T_COMPUTE> signGrad = signGradBuf.template Get<T_COMPUTE>();
    LocalTensor<T_COMPUTE> signM = signMBuf.template Get<T_COMPUTE>();
    LocalTensor<T_COMPUTE> signGm = signGmBuf.template Get<T_COMPUTE>();
    LocalTensor<T_COMPUTE> scale = scaleBuf.template Get<T_COMPUTE>();
    LocalTensor<T_COMPUTE> update = updateBuf.template Get<T_COMPUTE>();

    LocalTensor<uint8_t> signTmp = signTmpBuf.Get<uint8_t>(signTmpSize_);
    LocalTensor<uint8_t> nanMask = nanMaskBuf.Get<uint8_t>(nanMaskSize_);

    // --- 标量 broadcast ---
    Duplicate<T_COMPUTE>(lrDup, lrVal, currentNum);
    Duplicate<T_COMPUTE>(alphaDup, alphaVal, currentNum);
    Duplicate<T_COMPUTE>(sdDup, signDecayVal, currentNum);
    Duplicate<T_COMPUTE>(betaDup, betaVal, currentNum);

    // NaN scalar (T_COMPUTE 类型)，通过位拷贝构造避免编译器优化字面量
    union {
        uint32_t bits;
        float f;
    } nanU32 = {0x7FC00000U}; // IEEE-754 quiet NaN
    T_COMPUTE nanScalar = static_cast<T_COMPUTE>(nanU32.f);

    // ==========================================================
    // Step 1: betaM1 = 1.0 - beta
    // ==========================================================
    Duplicate<T_COMPUTE>(tmp, T_COMPUTE(1.0), currentNum);
    Sub(betaM1, tmp, betaDup, currentNum);

    // ==========================================================
    // Step 2: m_new = beta * m + (1 - beta) * grad
    //   使用 Muls(mF32, beta) 减少一次 Duplicate
    // ==========================================================
    Muls(mNew, mLocal, betaVal, currentNum);
    Mul(tmp, betaM1, gradLocal, currentNum);
    Add(mNew, mNew, tmp, currentNum);

    // ==========================================================
    // Step 3: sign_grad = Sign(grad) + NaN-Patch
    //   AscendC::Sign 对 NaN 输入返回 0（非传播），需后续注入 NaN scalar
    //   Compare(EQ, grad, grad)：finite/Inf → 1, NaN → 0 (因为 NaN!=NaN)
    //   Select 模式 1：selMask=1 保留 signGrad；selMask=0 写入 nanScalar
    // ==========================================================
    Sign(signGrad, gradLocal, signTmp, currentNum);
    Compare(nanMask, gradLocal, gradLocal, CMPMODE::EQ, currentNum);
    Select(signGrad, nanMask, signGrad, nanScalar, SELMODE::VSEL_TENSOR_SCALAR_MODE, currentNum);

    // ==========================================================
    // Step 4: sign_m = Sign(m_new) + NaN-Patch
    // ==========================================================
    Sign(signM, mNew, signTmp, currentNum);
    Compare(nanMask, mNew, mNew, CMPMODE::EQ, currentNum);
    Select(signM, nanMask, signM, nanScalar, SELMODE::VSEL_TENSOR_SCALAR_MODE, currentNum);

    // ==========================================================
    // Step 5: sign_gm = sign_grad * sign_m
    //   sign_grad / sign_m 已含 NaN, NaN * X = NaN, NaN 自动传播
    // ==========================================================
    Mul(signGm, signGrad, signM, currentNum);

    // ==========================================================
    // Step 6: scale = alpha + sign_decay * sign_gm
    // ==========================================================
    Mul(tmp, sdDup, signGm, currentNum);
    Add(scale, alphaDup, tmp, currentNum);

    // ==========================================================
    // Step 7: update = lr * scale * grad
    //   乘法顺序按 dtype 分流：
    //   - fp16 / bf16 (T_IN == half / bfloat16_t)：(scale * grad) * lr  ← L1_161 顺序
    //     当 lr 接近 fp16/bf16 最小正常数时，先 lr*scale 会让中间值落入
    //     subnormal 区，触发 CAST_RINT 1 ULP 差异。先 scale*grad 保持
    //     normal 量级，再乘 lr 让 subnormal 边界舍入序更稳定。
    //     bf16 mantissa 7bit 较 fp16 (10bit) 更短，subnormal 边界更宽，
    //     该重排同样有保护作用。
    //   - fp32 (T_IN == float)：(lr * scale) * grad  ← 原顺序，避免溢出
    //     fp32 路径下 sign_decay 可能取 ±MAX_FLOAT32 (≈3.4e38)，scale 同量级；
    //     先 scale*grad (grad~O(10)) 会产生 3.4e39 → +Inf 溢出。先 lr*scale
    //     (lr~MIN_NORMAL≈1e-38) 把量级压回 O(1) 再乘 grad 即可避免溢出。
    //     fp32 无 subnormal 精度差异（mantissa 23bit）。
    // ==========================================================
    if constexpr (std::is_same_v<T_IN, half> || std::is_same_v<T_IN, bfloat16_t>) {
        Mul(tmp, scale, gradLocal, currentNum); // scale * grad (fp16/bf16 normal)
        Muls(update, tmp, lrVal, currentNum);   // * lr
    } else {
        Muls(tmp, scale, lrVal, currentNum);     // lr * scale (fp32 防溢出)
        Mul(update, tmp, gradLocal, currentNum); // * grad
    }

    // ==========================================================
    // Step 8: var_out_fp32 = var - update
    // Step 9: [fp16/bf16 only] Cast fp32 → fp16/bf16 with CAST_RINT
    // ==========================================================
    if constexpr (std::is_same_v<T_IN, T_COMPUTE>) {
        // fp32 路径：直接写到 varOutLocal
        Sub(varOutLocal, varLocal, update, currentNum);
    } else {
        // fp16/bf16 路径：先算 fp32, 再 CAST_RINT 回 half / bfloat16_t
        LocalTensor<T_COMPUTE> varOutF32 = varOutF32Buf.template Get<T_COMPUTE>();
        Sub(varOutF32, varLocal, update, currentNum);
        Cast(varOutLocal, varOutF32, AscendC::RoundMode::CAST_RINT, currentNum);
    }

    // --- Free inputs ---
    varQueue.FreeTensor(varLocalIn);
    mQueue.FreeTensor(mLocalIn);
    gradQueue.FreeTensor(gradLocalIn);

    // --- EnQue output ---
    varOutQueue.EnQue(varOutLocal);
}

// ============================================================================
// CopyOut
// ============================================================================
template <typename T_IN, typename T_COMPUTE>
__aicore__ inline void ApplyAddSignKernel<T_IN, T_COMPUTE>::CopyOut(int64_t progress, int64_t currentNum)
{
    LocalTensor<T_IN> varOutLocal = varOutQueue.DeQue<T_IN>();

    DataCopyParams params;
    params.blockCount = 1;
    params.blockLen = static_cast<uint16_t>(currentNum * sizeof(T_IN));
    params.srcStride = 0;
    params.dstStride = 0;
    DataCopyPad(varOutGM_[progress * ubLength_], varOutLocal, params);

    varOutQueue.FreeTensor(varOutLocal);
}

// ============================================================================
// Process: main loop
// ============================================================================
template <typename T_IN, typename T_COMPUTE>
__aicore__ inline void ApplyAddSignKernel<T_IN, T_COMPUTE>::Process()
{
    if (blockLength_ <= 0 || ubLength_ <= 0) {
        return;
    }
    int64_t loopCount = (blockLength_ + ubLength_ - 1) / ubLength_;
    for (int64_t i = 0; i < loopCount; i++) {
        int64_t currentNum = (i == (loopCount - 1)) ? (blockLength_ - ubLength_ * i) : ubLength_;
        if (currentNum <= 0) {
            break;
        }
        CopyIn(i, currentNum);
        Compute(currentNum);
        CopyOut(i, currentNum);
    }
}

} // namespace NsApplyAddSign

#endif // APPLY_ADD_SIGN_KERNEL_ARCH35_H
