/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

#ifndef SOFTSHRINK_GRAD_H
#define SOFTSHRINK_GRAD_H

#include "kernel_operator.h"
#include "kernel_tiling/kernel_tiling.h"
#include "softshrink_grad_tiling_data.h"
#ifndef __CCE_KT_TEST__
#include "softshrink_grad_tiling_key.h"
#endif

namespace NsSoftShrinkGrad {

using namespace AscendC;

// SoftShrinkGrad kernel using Ordinary Kernel-Side APIs (non-VF Function).
// Compute: output_y[i] = input_grad[i] if |input_x[i]| > lambd OR isnan(input_x[i]), else 0
// NaN protection per spec.yaml: NaN positions pass through input_grad.
template <typename T, int BUFFER_MODE>
class SoftShrinkGrad {
    static constexpr int32_t BUFFER_NUM = BUFFER_MODE ? 2 : 1;
    static constexpr bool NEED_PROMOTE = std::is_same_v<T, half> || std::is_same_v<T, bfloat16_t>;

public:
    __aicore__ inline SoftShrinkGrad(){};

    __aicore__ inline void Init(GM_ADDR inputGrad, GM_ADDR inputX, GM_ADDR outputY,
                                const SoftShrinkGradTilingData* tilingData);
    __aicore__ inline void Process();

private:
    __aicore__ inline void CopyIn(int64_t progress, int64_t currentNum);
    __aicore__ inline void CopyOut(int64_t progress, int64_t currentNum);
    __aicore__ inline void Compute(int64_t currentNum);

private:
    TPipe pipe;
    TQue<QuePosition::VECIN, BUFFER_NUM> inputQueueGrad;
    TQue<QuePosition::VECIN, BUFFER_NUM> inputQueueX;
    TQue<QuePosition::VECOUT, BUFFER_NUM> outputQueue;

    // Extra buffers for intermediate computation (not queued)
    TBuf<QuePosition::VECCALC> calcBuf;

    GlobalTensor<T> gmInputGrad;
    GlobalTensor<T> gmInputX;
    GlobalTensor<T> gmOutputY;

    int64_t blockLength_ = 0;
    int64_t ubLength_ = 0;
    int64_t maskBytes_ = 0; // 32B-aligned mask buffer size in bytes
    float lambd_ = 0.5f;
};

template <typename T, int BUFFER_MODE>
__aicore__ inline void SoftShrinkGrad<T, BUFFER_MODE>::Init(GM_ADDR inputGrad, GM_ADDR inputX, GM_ADDR outputY,
                                                            const SoftShrinkGradTilingData* tilingData)
{
    int64_t blockIdx = AscendC::GetBlockIdx();
    bool isLastBlock = (blockIdx == tilingData->blockNum - 1);
    int64_t blockTail = tilingData->dim0 - (tilingData->blockNum - 1) * tilingData->blockFormer;
    blockLength_ = isLastBlock ? blockTail : tilingData->blockFormer;
    ubLength_ = tilingData->ubFormer;
    lambd_ = tilingData->lambd;

    int64_t gmOffset = tilingData->blockFormer * blockIdx;
    gmInputGrad.SetGlobalBuffer((__gm__ T*)inputGrad + gmOffset, blockLength_);
    gmInputX.SetGlobalBuffer((__gm__ T*)inputX + gmOffset, blockLength_);
    gmOutputY.SetGlobalBuffer((__gm__ T*)outputY + gmOffset, blockLength_);

    // Allocate queued buffers for input grad, input x, and output
    pipe.InitBuffer(inputQueueGrad, BUFFER_NUM, ubLength_ * sizeof(T));
    pipe.InitBuffer(inputQueueX, BUFFER_NUM, ubLength_ * sizeof(T));
    pipe.InitBuffer(outputQueue, BUFFER_NUM, ubLength_ * sizeof(T));

    // Allocate intermediate calculation buffer
    // CompareScalar/Compare require count to occupy 256B-aligned space.
    // ubLength_ is already 256B-aligned from tiling.
    // We need 2 separate mask buffers: cmpMask for threshold comparison,
    // nanMask for NaN detection. Each needs ubLength_/8 bytes, 32B-aligned
    // for GetWithOffset bufOffset alignment requirement.
    constexpr int64_t ALIGN_32 = 32;
    maskBytes_ = ((ubLength_ + 7) / 8 + ALIGN_32 - 1) / ALIGN_32 * ALIGN_32;
    if constexpr (NEED_PROMOTE) {
        // FP16/BF16 path: gradFP32 + xFP32 + absX(FP32) + outFP32 = 4 FP32 buffers
        // + cmpMask + nanMask (2 uint8 mask buffers)
        int64_t calcSize = 4 * ubLength_ * static_cast<int64_t>(sizeof(float)) + 2 * maskBytes_;
        pipe.InitBuffer(calcBuf, calcSize);
    } else {
        // FP32 path: absX(FP32) = 1 FP32 buffer + cmpMask + nanMask
        int64_t calcSize = 1 * ubLength_ * static_cast<int64_t>(sizeof(float)) + 2 * maskBytes_;
        pipe.InitBuffer(calcBuf, calcSize);
    }
}

template <typename T, int BUFFER_MODE>
__aicore__ inline void SoftShrinkGrad<T, BUFFER_MODE>::CopyIn(int64_t progress, int64_t currentNum)
{
    LocalTensor<T> gradLocal = inputQueueGrad.template AllocTensor<T>();
    LocalTensor<T> xLocal = inputQueueX.template AllocTensor<T>();

    DataCopyExtParams copyParams;
    copyParams.blockCount = 1;
    copyParams.blockLen = currentNum * sizeof(T);
    copyParams.srcStride = 0;
    copyParams.dstStride = 0;

    DataCopyPad(gradLocal, gmInputGrad[progress * ubLength_], copyParams, {false, 0, 0, 0});
    DataCopyPad(xLocal, gmInputX[progress * ubLength_], copyParams, {false, 0, 0, 0});

    inputQueueGrad.EnQue(gradLocal);
    inputQueueX.EnQue(xLocal);
}

template <typename T, int BUFFER_MODE>
__aicore__ inline void SoftShrinkGrad<T, BUFFER_MODE>::CopyOut(int64_t progress, int64_t currentNum)
{
    LocalTensor<T> outLocal = outputQueue.template DeQue<T>();

    DataCopyExtParams copyParams;
    copyParams.blockCount = 1;
    copyParams.blockLen = currentNum * sizeof(T);
    copyParams.srcStride = 0;
    copyParams.dstStride = 0;

    DataCopyPad(gmOutputY[progress * ubLength_], outLocal, copyParams);
    outputQueue.FreeTensor(outLocal);
}

template <typename T, int BUFFER_MODE>
__aicore__ inline void SoftShrinkGrad<T, BUFFER_MODE>::Compute(int64_t currentNum)
{
    LocalTensor<T> gradLocal = inputQueueGrad.template DeQue<T>();
    LocalTensor<T> xLocal = inputQueueX.template DeQue<T>();
    LocalTensor<T> outLocal = outputQueue.template AllocTensor<T>();

    // CompareScalar and Compare require count to occupy a 256B-aligned span.
    // For FP32 data, 256B / 4B = 64 elements alignment.
    // ubFormer from tiling is already 256B aligned, but the tail block (currentNum)
    // may not be. We align up for comparison APIs. The extra elements in the
    // comparison result are harmless because Select uses the same aligned count
    // and the output beyond currentNum is not written back to GM.
    constexpr int64_t CMP_ALIGN_ELEMS = 256 / static_cast<int64_t>(sizeof(float)); // 64
    int64_t alignedNum = ((currentNum + CMP_ALIGN_ELEMS - 1) / CMP_ALIGN_ELEMS) * CMP_ALIGN_ELEMS;
    // Ensure alignedNum does not exceed ubLength_ (buffer allocation size)
    if (alignedNum > ubLength_) {
        alignedNum = ubLength_;
    }

    if constexpr (NEED_PROMOTE) {
        // ---- FP16/BF16 promote-to-FP32 path ----
        // Partition calcBuf into FP32 intermediate buffers using GetWithOffset.
        // Layout: [gradFP32 | xFP32 | absX | outFP32 | cmpMask | nanMask]
        // Each FP32 buffer: ubLength_ * sizeof(float) bytes
        // Each mask buffer: maskBytes_ bytes (32B-aligned)
        int64_t fp32BufBytes = ubLength_ * static_cast<int64_t>(sizeof(float));
        LocalTensor<float> gradFP32 = calcBuf.GetWithOffset<float>(ubLength_, 0);
        LocalTensor<float> xFP32 = calcBuf.GetWithOffset<float>(ubLength_, fp32BufBytes);
        LocalTensor<float> absX = calcBuf.GetWithOffset<float>(ubLength_, 2 * fp32BufBytes);
        LocalTensor<float> outFP32 = calcBuf.GetWithOffset<float>(ubLength_, 3 * fp32BufBytes);
        LocalTensor<uint8_t> cmpMask = calcBuf.GetWithOffset<uint8_t>(maskBytes_, 4 * fp32BufBytes);
        LocalTensor<uint8_t> nanMask = calcBuf.GetWithOffset<uint8_t>(maskBytes_, 4 * fp32BufBytes + maskBytes_);

        // Zero-init intermediate FP32 buffers to prevent garbage from uninitialized
        // tail elements (when currentNum < alignedNum) affecting comparison results.
        Duplicate(gradFP32, 0.0f, alignedNum);
        Duplicate(xFP32, 0.0f, alignedNum);

        // Cast inputs to FP32 (CAST_NONE for upcasting)
        // Use currentNum (not alignedNum) for Cast: only cast valid data.
        // The buffers beyond currentNum are already zeroed above.
        Cast(gradFP32, gradLocal, RoundMode::CAST_NONE, currentNum);
        Cast(xFP32, xLocal, RoundMode::CAST_NONE, currentNum);

        // Compute |x| in FP32
        Abs(absX, xFP32, alignedNum);

        // Compare |x| > lambd -> cmpMask (uint8 bitmask)
        // Use alignedNum (256B aligned) for CompareScalar as required by API
        CompareScalar(cmpMask, absX, lambd_, CMPMODE::GT, alignedNum);

        // Select: cmpMask=1 -> gradFP32, cmpMask=0 -> 0.0f
        // Using Select mode 1 (VSEL_TENSOR_SCALAR_MODE): tensor + scalar
        Select(outFP32, cmpMask, gradFP32, 0.0f, SELMODE::VSEL_TENSOR_SCALAR_MODE, alignedNum);

        // NaN protection: for NaN positions in input_x, output should be input_grad.
        // IEEE 754: NaN comparisons always return false, so CompareScalar(GT) with NaN
        // gives cmpMask=0, Select gives 0. Override those positions with grad.
        // Detect NaN: x != x is true for NaN (IEEE 754)
        Compare(nanMask, xFP32, xFP32, CMPMODE::NE, alignedNum);

        // For NaN positions (nanMask=1), override outFP32 with gradFP32
        // Use Select mode 2 (VSEL_TENSOR_TENSOR_MODE): two tensors, continuous mask
        Select(outFP32, nanMask, gradFP32, outFP32, SELMODE::VSEL_TENSOR_TENSOR_MODE, alignedNum);

        // Cast back to original dtype (CAST_ROUND for downcasting)
        Cast(outLocal, outFP32, RoundMode::CAST_ROUND, currentNum);
    } else {
        // ---- FP32 direct compute path ----
        // Layout: [absX | cmpMask | nanMask]
        int64_t fp32BufBytes = ubLength_ * static_cast<int64_t>(sizeof(float));
        LocalTensor<float> absX = calcBuf.GetWithOffset<float>(ubLength_, 0);
        LocalTensor<uint8_t> cmpMask = calcBuf.GetWithOffset<uint8_t>(maskBytes_, fp32BufBytes);
        LocalTensor<uint8_t> nanMask = calcBuf.GetWithOffset<uint8_t>(maskBytes_, fp32BufBytes + maskBytes_);

        // Compute |x|
        Abs(absX, xLocal, alignedNum);

        // Compare |x| > lambd (256B aligned count)
        CompareScalar(cmpMask, absX, lambd_, CMPMODE::GT, alignedNum);

        // Select: cmpMask=1 -> grad, cmpMask=0 -> 0
        Select(outLocal, cmpMask, gradLocal, static_cast<T>(0), SELMODE::VSEL_TENSOR_SCALAR_MODE, alignedNum);

        // NaN protection: x != x for NaN detection (256B aligned count)
        Compare(nanMask, xLocal, xLocal, CMPMODE::NE, alignedNum);

        // For NaN positions (nanMask=1), override with grad
        // Use Select mode 2 (VSEL_TENSOR_TENSOR_MODE) for continuous mask consumption
        Select(outLocal, nanMask, gradLocal, outLocal, SELMODE::VSEL_TENSOR_TENSOR_MODE, alignedNum);
    }

    outputQueue.template EnQue<T>(outLocal);
    inputQueueGrad.FreeTensor(gradLocal);
    inputQueueX.FreeTensor(xLocal);
}

template <typename T, int BUFFER_MODE>
__aicore__ inline void SoftShrinkGrad<T, BUFFER_MODE>::Process()
{
    int64_t loopCount = (blockLength_ + ubLength_ - 1) / ubLength_;
    for (int64_t i = 0; i < loopCount; i++) {
        int64_t currentNum = (i == (loopCount - 1)) ? (blockLength_ - ubLength_ * i) : ubLength_;
        CopyIn(i, currentNum);
        Compute(currentNum);
        CopyOut(i, currentNum);
    }
}

} // namespace NsSoftShrinkGrad

#endif // SOFTSHRINK_GRAD_H
