/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file foreach_copy_tiling_arch35.h
 * \brief Tiling data structure and compile info for foreach_copy (arch35 host side)
 */

#ifndef OPS_NN_FOREACH_COPY_TILING_ARCH35_HOST_H
#define OPS_NN_FOREACH_COPY_TILING_ARCH35_HOST_H

#include "platform/platform_info.h"

constexpr int32_t MAX_TENSOR_NUM_FOREACH_COPY_HOST = 128;

struct ForeachCopyTilingData {
    int32_t needCoreNum;
    int32_t tensorNum;
    int32_t tensorStart;
    int64_t tensorOffset;
    int64_t totalElements;
    uint64_t dtypeKey;
    int64_t numels[MAX_TENSOR_NUM_FOREACH_COPY_HOST];
};

struct ForeachCopyCompileInfo {
    int64_t coreNum;
    int64_t ubSize;
};

#endif // OPS_NN_FOREACH_COPY_TILING_ARCH35_HOST_H
