/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */
/* Generated By CANNBot */

/*!
 * \file foreach_div_list_tiling.cpp
 * \brief Tiling implementation for foreach_div_list operator.
 *        Computes core split based on maxTensorElements, stores per-tensor
 *        element counts in tilingData, and allocates workspace for
 *        tensor metadata (addresses + element counts).
 */

#include <vector>
#include <algorithm>
#include "register/op_def_registry.h"
#include "tiling/tiling_api.h"
#include "platform/platform_info.h"
#include "log/log.h"
#include "foreach_div_list_tiling.h"

using namespace AscendC;

namespace optiling {

constexpr int64_t DCACHE_SIZE = 128 * 1024;
constexpr int64_t SINGLE_CORE_MIN_ELEMENTS = 1024;
constexpr int64_t INPUT_IDX_X1 = 0;
constexpr int32_t WS_ALIGN = 128;

// Get tiling key from dtype (SE order: FP32=0, FP16=1, BF16=2)
static uint64_t GetTilingKeyByDtype(ge::DataType dtype)
{
    switch (dtype) {
        case ge::DT_FLOAT:
            return 0;
        case ge::DT_FLOAT16:
            return 1;
        case ge::DT_BF16:
            return 2;
        default:
            return 0;
    }
}

static ge::graphStatus GetPlatformInfoFallback(gert::TilingContext* context, int64_t& coreNum, int64_t& ubSize)
{
    auto compileInfo = reinterpret_cast<const ForeachDivListCompileInfo*>(context->GetCompileInfo());
    if (compileInfo != nullptr && compileInfo->coreNum > 0 && compileInfo->ubSize > 0) {
        coreNum = compileInfo->coreNum;
        ubSize = compileInfo->ubSize;
        return ge::GRAPH_SUCCESS;
    }
    fe::PlatFormInfos* platformInfoPtr = context->GetPlatformInfo();
    if (platformInfoPtr != nullptr) {
        auto ascendcPlatform = platform_ascendc::PlatformAscendC(platformInfoPtr);
        coreNum = ascendcPlatform.GetCoreNumAiv();
        uint64_t ub = 0;
        ascendcPlatform.GetCoreMemSize(platform_ascendc::CoreMemType::UB, ub);
        ubSize = static_cast<int64_t>(ub);
        if (coreNum > 0 && ubSize > 0) {
            return ge::GRAPH_SUCCESS;
        }
    }
    return ge::GRAPH_FAILED;
}

static int64_t ComputeWorkspaceSize(int32_t tensorCount)
{
    // Workspace layout: 8 + tensorCount * 8 * 4
    // ws[0]: tensorCount (int64_t)
    // ws[1..tensorCount]: elementCounts
    // ws[tensorCount+1..2*tensorCount]: x1Addrs
    // ws[2*tensorCount+1..3*tensorCount]: x2Addrs
    // ws[3*tensorCount+1..4*tensorCount]: yAddrs
    int64_t rawSize = 8 + static_cast<int64_t>(tensorCount) * 8 * 4;
    // Align to WS_ALIGN (128B)
    return ((rawSize + WS_ALIGN - 1) / WS_ALIGN) * WS_ALIGN;
}

static ge::graphStatus ForeachDivListTilingFunc(gert::TilingContext* context)
{
    // 1. Get platform info
    int64_t coreNum = 0;
    int64_t ubSize = 0;
    OP_CHECK_IF(GetPlatformInfoFallback(context, coreNum, ubSize) != ge::GRAPH_SUCCESS,
                OP_LOGE(context, "Failed to get platform info"), return ge::GRAPH_FAILED);
    OP_CHECK_IF((ubSize <= DCACHE_SIZE), OP_LOGE(context, "ubSize %ld <= DCACHE_SIZE %ld", ubSize, DCACHE_SIZE),
                return ge::GRAPH_FAILED);
    ubSize = ubSize - DCACHE_SIZE;

    // 2. Get tensor count from dynamic input x1
    auto computeNodeInfoPtr = context->GetComputeNodeInfo();
    OP_CHECK_NULL_WITH_CONTEXT(context, computeNodeInfoPtr);
    auto idxInstanceInfoPtr = computeNodeInfoPtr->GetInputInstanceInfo(INPUT_IDX_X1);
    OP_CHECK_NULL_WITH_CONTEXT(context, idxInstanceInfoPtr);
    uint64_t tensorNum = idxInstanceInfoPtr->GetInstanceNum();

    OP_CHECK_IF((static_cast<int32_t>(tensorNum) > MAX_TENSOR_NUM_FOREACH_DIV_LIST),
                OP_LOGE(context, "tensorNum %lu exceeds MAX_TENSOR_NUM_FOREACH_DIV_LIST %d", tensorNum,
                        MAX_TENSOR_NUM_FOREACH_DIV_LIST),
                return ge::GRAPH_FAILED);

    // 3. Compute per-tensor element counts, totalElements, maxTensorElements
    int64_t totalElements = 0;
    int32_t maxTensorElements = 0;
    ge::DataType dataType = ge::DT_FLOAT;
    ForeachDivListTilingData* tilingData = context->GetTilingData<ForeachDivListTilingData>();

    for (uint64_t i = 0; i < tensorNum; i++) {
        auto idxTensorShapePtr = context->GetDynamicInputShape(INPUT_IDX_X1, i);
        OP_CHECK_NULL_WITH_CONTEXT(context, idxTensorShapePtr);
        auto idxTensorShape = idxTensorShapePtr->GetStorageShape();
        int64_t numel = idxTensorShape.GetShapeSize();
        tilingData->elementCounts[i] = numel;
        totalElements += numel;
        if (numel > maxTensorElements) {
            maxTensorElements = static_cast<int32_t>(numel);
        }
        if (i == 0) {
            auto idxTensorDtypePtr = context->GetDynamicInputDesc(INPUT_IDX_X1, i);
            OP_CHECK_NULL_WITH_CONTEXT(context, idxTensorDtypePtr);
            dataType = idxTensorDtypePtr->GetDataType();
        }
    }

    // 4. Compute core split based on maxTensorElements (MDE design)
    int64_t needCoreNum = 1;
    if (maxTensorElements >= SINGLE_CORE_MIN_ELEMENTS) {
        needCoreNum = std::min(coreNum, (static_cast<int64_t>(maxTensorElements) + SINGLE_CORE_MIN_ELEMENTS - 1) /
                                            SINGLE_CORE_MIN_ELEMENTS);
    }

    // 5. Fill TilingData (aligned with MDE)
    tilingData->needCoreNum = static_cast<int32_t>(needCoreNum);
    tilingData->totalElements = totalElements;
    tilingData->tensorCount = static_cast<int32_t>(tensorNum);
    tilingData->maxTensorElements = maxTensorElements;

    // 6. Set context
    context->SetBlockDim(needCoreNum);
    context->SetTilingKey(GetTilingKeyByDtype(dataType));

    // 7. Set local memory size
    auto res = context->SetLocalMemorySize(static_cast<uint32_t>(ubSize));
    OP_CHECK_IF((res != ge::GRAPH_SUCCESS), OP_LOGE(context, "SetLocalMemorySize ubSize=%ld failed", ubSize),
                return ge::GRAPH_FAILED);

    // 8. Set workspace size (user workspace + system workspace)
    int64_t userWorkspaceSize = ComputeWorkspaceSize(static_cast<int32_t>(tensorNum));
    auto ascendcPlatform = platform_ascendc::PlatformAscendC(context->GetPlatformInfo());
    uint64_t sysWorkspaceSize = ascendcPlatform.GetLibApiWorkSpaceSize();
    size_t* currentWorkspace = context->GetWorkspaceSizes(1);
    currentWorkspace[0] = static_cast<size_t>(userWorkspaceSize + static_cast<int64_t>(sysWorkspaceSize));

    return ge::GRAPH_SUCCESS;
}

// TilingParse callback
static ge::graphStatus TilingParseForForeachDivList(gert::TilingParseContext* context)
{
    auto compileInfo = context->GetCompiledInfo<ForeachDivListCompileInfo>();
    OP_CHECK_NULL_WITH_CONTEXT(context, compileInfo);
    auto platformInfo = context->GetPlatformInfo();
    OP_CHECK_NULL_WITH_CONTEXT(context, platformInfo);
    auto ascendcPlatform = platform_ascendc::PlatformAscendC(platformInfo);
    compileInfo->coreNum = ascendcPlatform.GetCoreNumAiv();
    OP_CHECK_IF((compileInfo->coreNum <= 0), OP_LOGE(context, "Failed to get core num."), return ge::GRAPH_FAILED);
    uint64_t ubSize;
    ascendcPlatform.GetCoreMemSize(platform_ascendc::CoreMemType::UB, ubSize);
    compileInfo->ubSize = static_cast<int64_t>(ubSize);
    OP_CHECK_IF((compileInfo->ubSize <= 0), OP_LOGE(context, "Failed to get ub size."), return ge::GRAPH_FAILED);
    return ge::GRAPH_SUCCESS;
}

// Tiling registration (three-part: .Tiling() + .TilingParse<>())
IMPL_OP_OPTILING(ForeachDivList)
    .Tiling(ForeachDivListTilingFunc)
    .TilingParse<ForeachDivListCompileInfo>(TilingParseForForeachDivList);

} // namespace optiling