/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */
/* Generated By CANNBot */

/*!
 * \file foreach_div_list_tiling.h
 * \brief Tiling data structure and compile info for foreach_div_list.
 *        Aligned with MDE: {needCoreNum, totalElements, tensorCount,
 *        maxTensorElements} plus per-tensor elementCounts array.
 */

#ifndef OPS_NN_FOREACH_DIV_LIST_TILING_H
#define OPS_NN_FOREACH_DIV_LIST_TILING_H

#include "platform/platform_info.h"

constexpr int32_t MAX_TENSOR_NUM_FOREACH_DIV_LIST = 256;

struct ForeachDivListTilingData {
    int32_t needCoreNum;
    int64_t totalElements;
    int32_t tensorCount;
    int32_t maxTensorElements;
    int64_t elementCounts[MAX_TENSOR_NUM_FOREACH_DIV_LIST];
};

struct ForeachDivListCompileInfo {
    int64_t coreNum;
    int64_t ubSize;
};

#endif // OPS_NN_FOREACH_DIV_LIST_TILING_H
