/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/*!
 * \file rms_norm_grad_quant_tiling_key.h
 * \brief
 */

#ifndef RMS_NORM_GRAD_QUANT_TILING_KEY_H
#define RMS_NORM_GRAD_QUANT_TILING_KEY_H

#include "ascendc/host_api/tiling/template_argument.h"
// RmsNormGrad tiling key
#define COMPUTE_MODE_DX_FULL_LOAD 0
#define COMPUTE_MODE_DX_SPLIT_D 1

#define COMPUTE_MODE_DGAMMA_FULL_LOAD 0
#define COMPUTE_MODE_DGAMMA_BIG_M 1
#define COMPUTE_MODE_DGAMMA_WITH_LARGE_ROWS 2
#define COMPUTE_MODE_DGAMMA_EMPTY 3

// Quant tiling Key
#define COMPUTE_MODE_WITH_OFFSET_X 0
#define COMPUTE_MODE_WITHOUT_OFFSET_X 1

#define COMPUTE_MODE_DIV_MODE 0
#define COMPUTE_MODE_NOT_DIV_MODE 1

ASCENDC_TPL_ARGS_DECL(RmsNormGradQuant,
                      ASCENDC_TPL_UINT_DECL(COMPUTE_DX_MODE, ASCENDC_TPL_2_BW, ASCENDC_TPL_UI_LIST,
                                            COMPUTE_MODE_DX_FULL_LOAD, COMPUTE_MODE_DX_SPLIT_D),
                      ASCENDC_TPL_UINT_DECL(COMPUTE_DGAMMA_MODE, ASCENDC_TPL_4_BW, ASCENDC_TPL_UI_LIST,
                                            COMPUTE_MODE_DGAMMA_FULL_LOAD, COMPUTE_MODE_DGAMMA_BIG_M,
                                            COMPUTE_MODE_DGAMMA_WITH_LARGE_ROWS, COMPUTE_MODE_DGAMMA_EMPTY),
                      ASCENDC_TPL_BOOL_DECL(COMPUTE_OFFSET_X_MODE, COMPUTE_MODE_WITH_OFFSET_X,
                                            COMPUTE_MODE_WITHOUT_OFFSET_X),
                      ASCENDC_TPL_BOOL_DECL(COMPUTE_DIV_MODE, COMPUTE_MODE_DIV_MODE, COMPUTE_MODE_NOT_DIV_MODE));

ASCENDC_TPL_SEL(
    // DX_FULL_LOAD + DGAMMA_FULL_LOAD combinations
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DX_MODE, ASCENDC_TPL_UI_LIST, COMPUTE_MODE_DX_FULL_LOAD),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DGAMMA_MODE, ASCENDC_TPL_UI_LIST, COMPUTE_MODE_DGAMMA_FULL_LOAD),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_OFFSET_X_MODE, COMPUTE_MODE_WITH_OFFSET_X),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_DIV_MODE, COMPUTE_MODE_DIV_MODE),
                         ASCENDC_TPL_TILING_STRUCT_SEL(RmsNormGradQuantRegbaseTilingData)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DX_MODE, ASCENDC_TPL_UI_LIST, COMPUTE_MODE_DX_FULL_LOAD),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DGAMMA_MODE, ASCENDC_TPL_UI_LIST, COMPUTE_MODE_DGAMMA_FULL_LOAD),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_OFFSET_X_MODE, COMPUTE_MODE_WITH_OFFSET_X),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_DIV_MODE, COMPUTE_MODE_NOT_DIV_MODE),
                         ASCENDC_TPL_TILING_STRUCT_SEL(RmsNormGradQuantRegbaseTilingData)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DX_MODE, ASCENDC_TPL_UI_LIST, COMPUTE_MODE_DX_FULL_LOAD),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DGAMMA_MODE, ASCENDC_TPL_UI_LIST, COMPUTE_MODE_DGAMMA_FULL_LOAD),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_OFFSET_X_MODE, COMPUTE_MODE_WITHOUT_OFFSET_X),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_DIV_MODE, COMPUTE_MODE_DIV_MODE),
                         ASCENDC_TPL_TILING_STRUCT_SEL(RmsNormGradQuantRegbaseTilingData)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DX_MODE, ASCENDC_TPL_UI_LIST, COMPUTE_MODE_DX_FULL_LOAD),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DGAMMA_MODE, ASCENDC_TPL_UI_LIST, COMPUTE_MODE_DGAMMA_FULL_LOAD),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_OFFSET_X_MODE, COMPUTE_MODE_WITHOUT_OFFSET_X),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_DIV_MODE, COMPUTE_MODE_NOT_DIV_MODE),
                         ASCENDC_TPL_TILING_STRUCT_SEL(RmsNormGradQuantRegbaseTilingData)),
    // DX_SPLIT_D + DGAMMA_FULL_LOAD combinations
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DX_MODE, ASCENDC_TPL_UI_LIST, COMPUTE_MODE_DX_SPLIT_D),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DGAMMA_MODE, ASCENDC_TPL_UI_LIST, COMPUTE_MODE_DGAMMA_FULL_LOAD),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_OFFSET_X_MODE, COMPUTE_MODE_WITH_OFFSET_X),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_DIV_MODE, COMPUTE_MODE_DIV_MODE),
                         ASCENDC_TPL_TILING_STRUCT_SEL(RmsNormGradQuantRegbaseTilingData)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DX_MODE, ASCENDC_TPL_UI_LIST, COMPUTE_MODE_DX_SPLIT_D),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DGAMMA_MODE, ASCENDC_TPL_UI_LIST, COMPUTE_MODE_DGAMMA_FULL_LOAD),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_OFFSET_X_MODE, COMPUTE_MODE_WITH_OFFSET_X),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_DIV_MODE, COMPUTE_MODE_NOT_DIV_MODE),
                         ASCENDC_TPL_TILING_STRUCT_SEL(RmsNormGradQuantRegbaseTilingData)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DX_MODE, ASCENDC_TPL_UI_LIST, COMPUTE_MODE_DX_SPLIT_D),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DGAMMA_MODE, ASCENDC_TPL_UI_LIST, COMPUTE_MODE_DGAMMA_FULL_LOAD),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_OFFSET_X_MODE, COMPUTE_MODE_WITHOUT_OFFSET_X),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_DIV_MODE, COMPUTE_MODE_DIV_MODE),
                         ASCENDC_TPL_TILING_STRUCT_SEL(RmsNormGradQuantRegbaseTilingData)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DX_MODE, ASCENDC_TPL_UI_LIST, COMPUTE_MODE_DX_SPLIT_D),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DGAMMA_MODE, ASCENDC_TPL_UI_LIST, COMPUTE_MODE_DGAMMA_FULL_LOAD),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_OFFSET_X_MODE, COMPUTE_MODE_WITHOUT_OFFSET_X),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_DIV_MODE, COMPUTE_MODE_NOT_DIV_MODE),
                         ASCENDC_TPL_TILING_STRUCT_SEL(RmsNormGradQuantRegbaseTilingData)),
    // DX_FULL_LOAD + DGAMMA_WITH_LARGE_ROWS combinations
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DX_MODE, ASCENDC_TPL_UI_LIST, COMPUTE_MODE_DX_FULL_LOAD),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DGAMMA_MODE, ASCENDC_TPL_UI_LIST,
                                              COMPUTE_MODE_DGAMMA_WITH_LARGE_ROWS),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_OFFSET_X_MODE, COMPUTE_MODE_WITH_OFFSET_X),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_DIV_MODE, COMPUTE_MODE_DIV_MODE),
                         ASCENDC_TPL_TILING_STRUCT_SEL(RmsNormGradQuantRegbaseTilingData)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DX_MODE, ASCENDC_TPL_UI_LIST, COMPUTE_MODE_DX_FULL_LOAD),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DGAMMA_MODE, ASCENDC_TPL_UI_LIST,
                                              COMPUTE_MODE_DGAMMA_WITH_LARGE_ROWS),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_OFFSET_X_MODE, COMPUTE_MODE_WITH_OFFSET_X),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_DIV_MODE, COMPUTE_MODE_NOT_DIV_MODE),
                         ASCENDC_TPL_TILING_STRUCT_SEL(RmsNormGradQuantRegbaseTilingData)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DX_MODE, ASCENDC_TPL_UI_LIST, COMPUTE_MODE_DX_FULL_LOAD),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DGAMMA_MODE, ASCENDC_TPL_UI_LIST,
                                              COMPUTE_MODE_DGAMMA_WITH_LARGE_ROWS),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_OFFSET_X_MODE, COMPUTE_MODE_WITHOUT_OFFSET_X),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_DIV_MODE, COMPUTE_MODE_DIV_MODE),
                         ASCENDC_TPL_TILING_STRUCT_SEL(RmsNormGradQuantRegbaseTilingData)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DX_MODE, ASCENDC_TPL_UI_LIST, COMPUTE_MODE_DX_FULL_LOAD),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DGAMMA_MODE, ASCENDC_TPL_UI_LIST,
                                              COMPUTE_MODE_DGAMMA_WITH_LARGE_ROWS),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_OFFSET_X_MODE, COMPUTE_MODE_WITHOUT_OFFSET_X),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_DIV_MODE, COMPUTE_MODE_NOT_DIV_MODE),
                         ASCENDC_TPL_TILING_STRUCT_SEL(RmsNormGradQuantRegbaseTilingData)),
    // DX_SPLIT_D + DGAMMA_WITH_LARGE_ROWS combinations
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DX_MODE, ASCENDC_TPL_UI_LIST, COMPUTE_MODE_DX_SPLIT_D),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DGAMMA_MODE, ASCENDC_TPL_UI_LIST,
                                              COMPUTE_MODE_DGAMMA_WITH_LARGE_ROWS),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_OFFSET_X_MODE, COMPUTE_MODE_WITH_OFFSET_X),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_DIV_MODE, COMPUTE_MODE_DIV_MODE),
                         ASCENDC_TPL_TILING_STRUCT_SEL(RmsNormGradQuantRegbaseTilingData)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DX_MODE, ASCENDC_TPL_UI_LIST, COMPUTE_MODE_DX_SPLIT_D),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DGAMMA_MODE, ASCENDC_TPL_UI_LIST,
                                              COMPUTE_MODE_DGAMMA_WITH_LARGE_ROWS),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_OFFSET_X_MODE, COMPUTE_MODE_WITH_OFFSET_X),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_DIV_MODE, COMPUTE_MODE_NOT_DIV_MODE),
                         ASCENDC_TPL_TILING_STRUCT_SEL(RmsNormGradQuantRegbaseTilingData)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DX_MODE, ASCENDC_TPL_UI_LIST, COMPUTE_MODE_DX_SPLIT_D),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DGAMMA_MODE, ASCENDC_TPL_UI_LIST,
                                              COMPUTE_MODE_DGAMMA_WITH_LARGE_ROWS),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_OFFSET_X_MODE, COMPUTE_MODE_WITHOUT_OFFSET_X),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_DIV_MODE, COMPUTE_MODE_DIV_MODE),
                         ASCENDC_TPL_TILING_STRUCT_SEL(RmsNormGradQuantRegbaseTilingData)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DX_MODE, ASCENDC_TPL_UI_LIST, COMPUTE_MODE_DX_SPLIT_D),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DGAMMA_MODE, ASCENDC_TPL_UI_LIST,
                                              COMPUTE_MODE_DGAMMA_WITH_LARGE_ROWS),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_OFFSET_X_MODE, COMPUTE_MODE_WITHOUT_OFFSET_X),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_DIV_MODE, COMPUTE_MODE_NOT_DIV_MODE),
                         ASCENDC_TPL_TILING_STRUCT_SEL(RmsNormGradQuantRegbaseTilingData)),
    // DX_FULL_LOAD + DGAMMA_BIG_M combinations
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DX_MODE, ASCENDC_TPL_UI_LIST, COMPUTE_MODE_DX_FULL_LOAD),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DGAMMA_MODE, ASCENDC_TPL_UI_LIST, COMPUTE_MODE_DGAMMA_BIG_M),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_OFFSET_X_MODE, COMPUTE_MODE_WITH_OFFSET_X),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_DIV_MODE, COMPUTE_MODE_DIV_MODE),
                         ASCENDC_TPL_TILING_STRUCT_SEL(RmsNormGradQuantRegbaseBigMTilingData)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DX_MODE, ASCENDC_TPL_UI_LIST, COMPUTE_MODE_DX_FULL_LOAD),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DGAMMA_MODE, ASCENDC_TPL_UI_LIST, COMPUTE_MODE_DGAMMA_BIG_M),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_OFFSET_X_MODE, COMPUTE_MODE_WITH_OFFSET_X),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_DIV_MODE, COMPUTE_MODE_NOT_DIV_MODE),
                         ASCENDC_TPL_TILING_STRUCT_SEL(RmsNormGradQuantRegbaseBigMTilingData)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DX_MODE, ASCENDC_TPL_UI_LIST, COMPUTE_MODE_DX_FULL_LOAD),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DGAMMA_MODE, ASCENDC_TPL_UI_LIST, COMPUTE_MODE_DGAMMA_BIG_M),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_OFFSET_X_MODE, COMPUTE_MODE_WITHOUT_OFFSET_X),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_DIV_MODE, COMPUTE_MODE_DIV_MODE),
                         ASCENDC_TPL_TILING_STRUCT_SEL(RmsNormGradQuantRegbaseBigMTilingData)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DX_MODE, ASCENDC_TPL_UI_LIST, COMPUTE_MODE_DX_FULL_LOAD),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DGAMMA_MODE, ASCENDC_TPL_UI_LIST, COMPUTE_MODE_DGAMMA_BIG_M),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_OFFSET_X_MODE, COMPUTE_MODE_WITHOUT_OFFSET_X),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_DIV_MODE, COMPUTE_MODE_NOT_DIV_MODE),
                         ASCENDC_TPL_TILING_STRUCT_SEL(RmsNormGradQuantRegbaseBigMTilingData)),
    // DX_SPLIT_D + DGAMMA_BIG_M combinations
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DX_MODE, ASCENDC_TPL_UI_LIST, COMPUTE_MODE_DX_SPLIT_D),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DGAMMA_MODE, ASCENDC_TPL_UI_LIST, COMPUTE_MODE_DGAMMA_BIG_M),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_OFFSET_X_MODE, COMPUTE_MODE_WITH_OFFSET_X),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_DIV_MODE, COMPUTE_MODE_DIV_MODE),
                         ASCENDC_TPL_TILING_STRUCT_SEL(RmsNormGradQuantRegbaseBigMTilingData)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DX_MODE, ASCENDC_TPL_UI_LIST, COMPUTE_MODE_DX_SPLIT_D),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DGAMMA_MODE, ASCENDC_TPL_UI_LIST, COMPUTE_MODE_DGAMMA_BIG_M),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_OFFSET_X_MODE, COMPUTE_MODE_WITH_OFFSET_X),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_DIV_MODE, COMPUTE_MODE_NOT_DIV_MODE),
                         ASCENDC_TPL_TILING_STRUCT_SEL(RmsNormGradQuantRegbaseBigMTilingData)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DX_MODE, ASCENDC_TPL_UI_LIST, COMPUTE_MODE_DX_SPLIT_D),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DGAMMA_MODE, ASCENDC_TPL_UI_LIST, COMPUTE_MODE_DGAMMA_BIG_M),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_OFFSET_X_MODE, COMPUTE_MODE_WITHOUT_OFFSET_X),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_DIV_MODE, COMPUTE_MODE_DIV_MODE),
                         ASCENDC_TPL_TILING_STRUCT_SEL(RmsNormGradQuantRegbaseBigMTilingData)),
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DX_MODE, ASCENDC_TPL_UI_LIST, COMPUTE_MODE_DX_SPLIT_D),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DGAMMA_MODE, ASCENDC_TPL_UI_LIST, COMPUTE_MODE_DGAMMA_BIG_M),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_OFFSET_X_MODE, COMPUTE_MODE_WITHOUT_OFFSET_X),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_DIV_MODE, COMPUTE_MODE_NOT_DIV_MODE),
                         ASCENDC_TPL_TILING_STRUCT_SEL(RmsNormGradQuantRegbaseBigMTilingData)),
    // DX_FULL_LOAD + DGAMMA_EMPTY combination
    ASCENDC_TPL_ARGS_SEL(ASCENDC_TPL_KERNEL_TYPE_SEL(ASCENDC_TPL_AIV_ONLY),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DX_MODE, ASCENDC_TPL_UI_LIST, COMPUTE_MODE_DX_FULL_LOAD),
                         ASCENDC_TPL_UINT_SEL(COMPUTE_DGAMMA_MODE, ASCENDC_TPL_UI_LIST, COMPUTE_MODE_DGAMMA_EMPTY),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_OFFSET_X_MODE, COMPUTE_MODE_WITH_OFFSET_X),
                         ASCENDC_TPL_BOOL_SEL(COMPUTE_DIV_MODE, COMPUTE_MODE_DIV_MODE),
                         ASCENDC_TPL_TILING_STRUCT_SEL(RmsNormGradQuantRegbaseEmptyTilingData)));
#endif
