/**
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 */

/* Generated By CANNBot */

/*!
 * \file hard_sigmoid_grad.h
 * \brief HardSigmoidGrad unified kernel template (arch35).
 *
 * Single template class covering all three dtypes:
 *   - HardSigmoidGrad<float>       → fp32 native compute (no Cast)
 *   - HardSigmoidGrad<half>        → Cast→fp32 compute → Cast back (CAST_RINT)
 *   - HardSigmoidGrad<bfloat16_t>  → Cast→fp32 compute → Cast back (CAST_ROUND)
 *
 * The Cast widening for half/bf16 avoids fp16 ε≈9.77e-4 boundary precision risk
 * at x≈±3 (HardSigmoid拐点); the fp32 specialization skips the Cast and operates
 * directly on the input queue buffers, avoiding 2 extra fp32 UB slots.
 *
 * Two paths are unified via `if constexpr (std::is_same_v<T, float>)`:
 *   - InitBuffer: cast buffers (gradFp32Buf / selfFp32Buf) only allocated when T ≠ float
 *   - Compute: select between fp32-native arithmetic and Cast→fp32→Cast pipeline
 *
 * Common per-core split (ComputePerCoreLength) and tile loop (RunTileLoop<>)
 * live in hard_sigmoid_grad_common.h.
 *
 * NOTE: Host ubFactor is aligned on max(ubBlockSize, 256B/sizeof(fp32))=64 fp32
 * elements, so CompareScalar's 256B-rounded read window stays inside tmpBuf for
 * any currentNum ≤ ubLength_.
 */
#ifndef HARD_SIGMOID_GRAD_H
#define HARD_SIGMOID_GRAD_H

#include "kernel_operator.h"
#include "kernel_tiling/kernel_tiling.h"
#include "hard_sigmoid_grad_tiling_data.h"
#include "hard_sigmoid_grad_tiling_key.h"

namespace NsHardSigmoidGrad {

using namespace AscendC;

// ─── Per-core slice + tile loop helpers ──────────────────────────────────────
// Used to live in hard_sigmoid_grad_common.h to dedup between the (now-unified)
// fp32 and cast kernel classes. After the fp32/half/bf16 paths merged into a
// single template HardSigmoidGrad<T>, only one caller remains, so the helpers
// were folded back here for locality.
//
// Precondition: tilingData != nullptr. Caller passes the address of a local
// HardSigmoidGradTilingData populated by GET_TILING_DATA_WITH_STRUCT (kernel-side
// macro that copies the host-prepared tilingData from GM to a stack object), so
// the pointer is always valid. No runtime null check is performed here to keep
// the __aicore__ helper branch-free.
__aicore__ inline int64_t ComputePerCoreLength(const HardSigmoidGradTilingData* tilingData)
{
    int64_t remainder = tilingData->totalLength - tilingData->blockFactor * AscendC::GetBlockIdx();
    return (remainder > tilingData->blockFactor) ? tilingData->blockFactor : remainder;
}

template <typename KernelT>
__aicore__ inline void RunTileLoop(KernelT& op, int64_t blockLength, int64_t ubLength)
{
    if (blockLength <= 0) {
        return;
    }
    int64_t loopCount = (blockLength + ubLength - 1) / ubLength;
    for (int64_t i = 0; i < loopCount; i++) {
        int64_t currentNum = (i == (loopCount - 1)) ? (blockLength - ubLength * i) : ubLength;
        op.CopyIn(i, currentNum);
        op.Compute(currentNum);
        op.CopyOut(i, currentNum);
    }
}

// Down-cast RoundMode trait for the cast path.
// half  → CAST_RINT  (nearest, banker's rounding)
// bf16  → CAST_ROUND (truncate to nearest)
// fp32 specialization unused (fp32 path skips Cast); declared for completeness only.
template <typename T>
struct CastDownRound;

template <>
struct CastDownRound<half> {
    static constexpr RoundMode value = RoundMode::CAST_RINT;
};

template <>
struct CastDownRound<bfloat16_t> {
    static constexpr RoundMode value = RoundMode::CAST_ROUND;
};

template <typename T>
class HardSigmoidGrad {
    static constexpr int32_t BUFFER_NUM = 2;                       // double buffer
    static constexpr bool kCastNeeded = !std::is_same<T, float>::value;

public:
    __aicore__ inline HardSigmoidGrad() {};

    __aicore__ inline void Init(GM_ADDR gradOutput, GM_ADDR self, GM_ADDR gradInput,
                                 const HardSigmoidGradTilingData* tilingData);
    __aicore__ inline void Process();

    // Public so RunTileLoop<KernelT>() in hard_sigmoid_grad_common.h can drive
    // the CopyIn → Compute → CopyOut sequence without friending.
    __aicore__ inline void CopyIn(int64_t progress, int64_t currentNum);
    __aicore__ inline void Compute(int64_t currentNum);
    __aicore__ inline void CopyOut(int64_t progress, int64_t currentNum);

private:
    TPipe pipe;
    TQue<QuePosition::VECIN, BUFFER_NUM> gradOutputQueue;
    TQue<QuePosition::VECIN, BUFFER_NUM> selfQueue;
    TQue<QuePosition::VECOUT, BUFFER_NUM> gradInputQueue;
    // Always allocated: tmp buffer for alpha*x+beta (fp32 for cast path, T=float for fp32 path).
    TBuf<QuePosition::VECCALC> tmpBuf;
    // Mask buffer for CompareScalar bitmask.
    TBuf<QuePosition::VECCALC> maskBuf;
    // Cast-path scratch (only InitBuffer'd when kCastNeeded; declared unconditionally
    // because TBuf is a thin handle and unused declarations have no UB footprint).
    TBuf<QuePosition::VECCALC> gradFp32Buf;
    TBuf<QuePosition::VECCALC> selfFp32Buf;

    GlobalTensor<T> gmGradOutput;
    GlobalTensor<T> gmSelf;
    GlobalTensor<T> gmGradInput;

    int64_t blockLength_ = 0;
    int64_t ubLength_ = 0;
    float alpha_ = 0.16666666f;
    float beta_ = 0.5f;
};

template <typename T>
__aicore__ inline void HardSigmoidGrad<T>::Init(
    GM_ADDR gradOutput, GM_ADDR self, GM_ADDR gradInput,
    const HardSigmoidGradTilingData* tilingData)
{
    blockLength_ = ComputePerCoreLength(tilingData);
    if (blockLength_ <= 0) {
        return;
    }
    ubLength_ = tilingData->ubFactor;
    alpha_ = tilingData->alpha;
    beta_ = tilingData->beta;

    gmGradOutput.SetGlobalBuffer((__gm__ T*)gradOutput + tilingData->blockFactor * AscendC::GetBlockIdx(), blockLength_);
    gmSelf.SetGlobalBuffer((__gm__ T*)self + tilingData->blockFactor * AscendC::GetBlockIdx(), blockLength_);
    gmGradInput.SetGlobalBuffer((__gm__ T*)gradInput + tilingData->blockFactor * AscendC::GetBlockIdx(), blockLength_);

    pipe.InitBuffer(gradOutputQueue, BUFFER_NUM, ubLength_ * sizeof(T));
    pipe.InitBuffer(selfQueue, BUFFER_NUM, ubLength_ * sizeof(T));
    pipe.InitBuffer(gradInputQueue, BUFFER_NUM, ubLength_ * sizeof(T));
    // tmp buffer: fp32 element size for the cast path (CompareScalar/Muls/Adds
    // happen in fp32), T-sized for the fp32 native path. Both branches produce
    // a buffer large enough for ubLength_ elements of the compute precision.
    if constexpr (kCastNeeded) {
        pipe.InitBuffer(tmpBuf, ubLength_ * sizeof(float));
        pipe.InitBuffer(gradFp32Buf, ubLength_ * sizeof(float));
        pipe.InitBuffer(selfFp32Buf, ubLength_ * sizeof(float));
    } else {
        pipe.InitBuffer(tmpBuf, ubLength_ * sizeof(T));
    }
    // Mask buffer: N fp32 elements → N/8 uint8 bytes, 32-byte aligned.
    int64_t maskBufSize = ((ubLength_ + 7) / 8 + 31) / 32 * 32;
    if (maskBufSize < 32) maskBufSize = 32;
    pipe.InitBuffer(maskBuf, maskBufSize);
}

template <typename T>
__aicore__ inline void HardSigmoidGrad<T>::CopyIn(int64_t progress, int64_t currentNum)
{
    LocalTensor<T> gradLocal = gradOutputQueue.template AllocTensor<T>();
    LocalTensor<T> selfLocal = selfQueue.template AllocTensor<T>();

    DataCopyParams copyParams;
    copyParams.blockCount = 1;
    copyParams.blockLen = currentNum * sizeof(T);
    copyParams.srcStride = 0;
    copyParams.dstStride = 0;

    DataCopyPad(gradLocal, gmGradOutput[progress * ubLength_], copyParams, {false, 0, 0, 0});
    DataCopyPad(selfLocal, gmSelf[progress * ubLength_], copyParams, {false, 0, 0, 0});

    gradOutputQueue.EnQue(gradLocal);
    selfQueue.EnQue(selfLocal);
}

template <typename T>
__aicore__ inline void HardSigmoidGrad<T>::Compute(int64_t currentNum)
{
    LocalTensor<T> gradLocal = gradOutputQueue.template DeQue<T>();
    LocalTensor<T> selfLocal = selfQueue.template DeQue<T>();
    LocalTensor<T> resultLocal = gradInputQueue.template AllocTensor<T>();
    LocalTensor<uint8_t> maskLocal = maskBuf.Get<uint8_t>();

    // Align count to 256-byte boundary for CompareScalar.
    // CompareScalar always works in fp32 for the cast path → 256/4 = 64 elements.
    // For fp32 native path → 256/sizeof(T) = 64 (T=float).
    constexpr int64_t COMPARE_ALIGN =
        kCastNeeded ? static_cast<int64_t>(64) : static_cast<int64_t>(256 / sizeof(T));
    int64_t alignedCount = (currentNum + COMPARE_ALIGN - 1) / COMPARE_ALIGN * COMPARE_ALIGN;

    if constexpr (kCastNeeded) {
        // ── Cast→fp32→Cast back pipeline (half / bf16) ──
        LocalTensor<float> gradFp32 = gradFp32Buf.Get<float>();
        LocalTensor<float> selfFp32 = selfFp32Buf.Get<float>();
        LocalTensor<float> tmp = tmpBuf.Get<float>();

        // API-1 fix: pre-fill the FULL alignedCount window with -1.0 (outside (0,1))
        // BEFORE compute. Guarantees CompareScalar tail bits at [currentNum, alignedCount)
        // are deterministic. Host-side ubFactor is 256B-aligned ⇒ alignedCount ≤ ubLength_.
        Duplicate(tmp, -1.0f, alignedCount);

        // Step 1: Cast T → fp32 (lossless widening for both half and bf16).
        Cast(gradFp32, gradLocal, RoundMode::CAST_NONE, currentNum);
        Cast(selfFp32, selfLocal, RoundMode::CAST_NONE, currentNum);

        // Step 2: tmp = alpha * selfFp32 + beta  (in fp32).
        Muls(tmp, selfFp32, alpha_, currentNum);
        Adds(tmp, tmp, beta_, currentNum);

        // Step 3: result-in-fp32 = gradOutputFp32 * alpha  (reuse selfFp32 buffer).
        Muls(selfFp32, gradFp32, alpha_, currentNum);

        // Step 4: mask = (tmp > 0), select.
        CompareScalar(maskLocal, tmp, 0.0f, CMPMODE::GT, alignedCount);
        Select(selfFp32, maskLocal, selfFp32, 0.0f, SELMODE::VSEL_TENSOR_SCALAR_MODE, currentNum);

        // Step 5: mask = (tmp < 1), select.
        CompareScalar(maskLocal, tmp, 1.0f, CMPMODE::LT, alignedCount);
        Select(selfFp32, maskLocal, selfFp32, 0.0f, SELMODE::VSEL_TENSOR_SCALAR_MODE, currentNum);

        // Step 6: Cast fp32 result → T (per-T RoundMode trait).
        Cast(resultLocal, selfFp32, CastDownRound<T>::value, currentNum);
    } else {
        // ── fp32 native pipeline (T = float) ──
        LocalTensor<T> tmpLocal = tmpBuf.Get<T>();

        Duplicate(tmpLocal, static_cast<T>(-1.0f), alignedCount);

        // Step 1: tmp = alpha * self + beta.
        Muls(tmpLocal, selfLocal, static_cast<T>(alpha_), currentNum);
        Adds(tmpLocal, tmpLocal, static_cast<T>(beta_), currentNum);

        // Step 2: result = grad_output * alpha.
        Muls(resultLocal, gradLocal, static_cast<T>(alpha_), currentNum);

        // Step 3: mask = (tmp > 0), select.
        CompareScalar(maskLocal, tmpLocal, static_cast<T>(0), CMPMODE::GT, alignedCount);
        Select(resultLocal, maskLocal, resultLocal, static_cast<T>(0),
               SELMODE::VSEL_TENSOR_SCALAR_MODE, currentNum);

        // Step 4: mask = (tmp < 1), select.
        CompareScalar(maskLocal, tmpLocal, static_cast<T>(1), CMPMODE::LT, alignedCount);
        Select(resultLocal, maskLocal, resultLocal, static_cast<T>(0),
               SELMODE::VSEL_TENSOR_SCALAR_MODE, currentNum);
    }

    gradInputQueue.template EnQue<T>(resultLocal);
    gradOutputQueue.FreeTensor(gradLocal);
    selfQueue.FreeTensor(selfLocal);
}

template <typename T>
__aicore__ inline void HardSigmoidGrad<T>::CopyOut(int64_t progress, int64_t currentNum)
{
    LocalTensor<T> resultLocal = gradInputQueue.template DeQue<T>();

    DataCopyParams copyParams;
    copyParams.blockCount = 1;
    copyParams.blockLen = currentNum * sizeof(T);
    copyParams.srcStride = 0;
    copyParams.dstStride = 0;

    DataCopyPad(gmGradInput[progress * ubLength_], resultLocal, copyParams);
    gradInputQueue.FreeTensor(resultLocal);
}

template <typename T>
__aicore__ inline void HardSigmoidGrad<T>::Process()
{
    RunTileLoop(*this, blockLength_, ubLength_);
}

} // namespace NsHardSigmoidGrad
#endif // HARD_SIGMOID_GRAD_H
